// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const allowAuditPurge = `-- name: AllowAuditPurge :exec
SELECT set_config('piilot.audit_purge', 'on', true)
`

// A appeler dans la transaction de la purge, juste avant elle.
func (q *Queries) AllowAuditPurge(ctx context.Context) error {
	_, err := q.db.Exec(ctx, allowAuditPurge)
	return err
}

const countAudit = `-- name: CountAudit :one
SELECT count(*)::integer FROM audit_log
WHERE ($1::text IS NULL OR action LIKE $1::text)
  AND ($2::uuid IS NULL OR actor_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR at < $4::timestamptz)
  AND ($5::text IS NULL
       OR actor_email ILIKE '%' || $5::text || '%'
       OR target_id ILIKE '%' || $5::text || '%'
       OR ip ILIKE '%' || $5::text || '%'
       OR details::text ILIKE '%' || $5::text || '%')
`

type CountAuditParams struct {
	Action  *string    `json:"action"`
	ActorID *uuid.UUID `json:"actor_id"`
	Since   *time.Time `json:"since"`
	Until   *time.Time `json:"until"`
	Search  *string    `json:"search"`
}

func (q *Queries) CountAudit(ctx context.Context, arg CountAuditParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAudit,
		arg.Action,
		arg.ActorID,
		arg.Since,
		arg.Until,
		arg.Search,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertAudit = `-- name: InsertAudit :exec

INSERT INTO audit_log (actor_id, actor_email, action, target_type, target_id, ip, user_agent, details)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type InsertAuditParams struct {
	ActorID    *uuid.UUID `json:"actor_id"`
	ActorEmail string     `json:"actor_email"`
	Action     string     `json:"action"`
	TargetType string     `json:"target_type"`
	TargetID   string     `json:"target_id"`
	Ip         string     `json:"ip"`
	UserAgent  string     `json:"user_agent"`
	Details    []byte     `json:"details"`
}

// Journal d'audit : en ajout seul. Ni UPDATE ni DELETE ici, sauf la purge de
// retention, que le declencheur n'admet que declaree.
func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorID,
		arg.ActorEmail,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Ip,
		arg.UserAgent,
		arg.Details,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, actor_id, actor_email, action, target_type, target_id, ip, user_agent, details FROM audit_log
WHERE ($1::text IS NULL OR action LIKE $1::text)
  AND ($2::uuid IS NULL OR actor_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR at < $4::timestamptz)
  AND ($5::text IS NULL
       OR actor_email ILIKE '%' || $5::text || '%'
       OR target_id ILIKE '%' || $5::text || '%'
       OR ip ILIKE '%' || $5::text || '%'
       OR details::text ILIKE '%' || $5::text || '%')
ORDER BY at DESC, id
LIMIT $7 OFFSET $6
`

type ListAuditParams struct {
	Action  *string    `json:"action"`
	ActorID *uuid.UUID `json:"actor_id"`
	Since   *time.Time `json:"since"`
	Until   *time.Time `json:"until"`
	Search  *string    `json:"search"`
	Skip    int32      `json:"skip"`
	MaxRows int32      `json:"max_rows"`
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.Action,
		arg.ActorID,
		arg.Since,
		arg.Until,
		arg.Search,
		arg.Skip,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Ip,
			&i.UserAgent,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAudit = `-- name: PurgeAudit :execrows
DELETE FROM audit_log WHERE at < now() - make_interval(days => $1::integer)
`

func (q *Queries) PurgeAudit(ctx context.Context, days int32) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAudit, days)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
