// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backups.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const abandonStaleBackups = `-- name: AbandonStaleBackups :exec
UPDATE app_backups
SET status = 'failed', finished_at = now(), error = 'Interrompue'
WHERE status = 'running' AND started_at < now() - interval '6 hours'
`

// Une sauvegarde restee « en cours » plus de six heures vient d'une commande
// interrompue : elle ne doit pas passer pour en route.
func (q *Queries) AbandonStaleBackups(ctx context.Context) error {
	_, err := q.db.Exec(ctx, abandonStaleBackups)
	return err
}

const createBackup = `-- name: CreateBackup :one

INSERT INTO app_backups (status) VALUES ('running')
RETURNING id, started_at, finished_at, status, location, size_bytes, error
`

// Sauvegardes : la commande `backup` ecrit ici, l'ecran des parametres et la
// tache de fond qui previent les admins y lisent.
func (q *Queries) CreateBackup(ctx context.Context) (AppBackup, error) {
	row := q.db.QueryRow(ctx, createBackup)
	var i AppBackup
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Location,
		&i.SizeBytes,
		&i.Error,
	)
	return i, err
}

const finishBackup = `-- name: FinishBackup :exec
UPDATE app_backups
SET finished_at = now(),
    status      = $1,
    location    = $2,
    size_bytes  = $3,
    error       = $4
WHERE id = $5
`

type FinishBackupParams struct {
	Status    string    `json:"status"`
	Location  string    `json:"location"`
	SizeBytes int64     `json:"size_bytes"`
	Error     string    `json:"error"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) FinishBackup(ctx context.Context, arg FinishBackupParams) error {
	_, err := q.db.Exec(ctx, finishBackup,
		arg.Status,
		arg.Location,
		arg.SizeBytes,
		arg.Error,
		arg.ID,
	)
	return err
}

const getLastSuccessfulBackup = `-- name: GetLastSuccessfulBackup :one
SELECT id, started_at, finished_at, status, location, size_bytes, error FROM app_backups
WHERE status = 'done'
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLastSuccessfulBackup(ctx context.Context) (AppBackup, error) {
	row := q.db.QueryRow(ctx, getLastSuccessfulBackup)
	var i AppBackup
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Location,
		&i.SizeBytes,
		&i.Error,
	)
	return i, err
}

const lastNotificationOfKind = `-- name: LastNotificationOfKind :one
SELECT coalesce(max(created_at), to_timestamp(0))::timestamptz AS at
FROM notifications
WHERE kind = $1
`

// Quand une alerte globale a ete emise pour la derniere fois, toutes
// personnes confondues : une alerte par jour suffit.
func (q *Queries) LastNotificationOfKind(ctx context.Context, kind string) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastNotificationOfKind, kind)
	var at time.Time
	err := row.Scan(&at)
	return at, err
}

const listBackups = `-- name: ListBackups :many
SELECT id, started_at, finished_at, status, location, size_bytes, error FROM app_backups
ORDER BY started_at DESC
LIMIT 20
`

func (q *Queries) ListBackups(ctx context.Context) ([]AppBackup, error) {
	rows, err := q.db.Query(ctx, listBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppBackup{}
	for rows.Next() {
		var i AppBackup
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Location,
			&i.SizeBytes,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneBackupRows = `-- name: PruneBackupRows :exec
DELETE FROM app_backups WHERE started_at < now() - interval '120 days'
`

// Le journal n'a pas a remonter plus loin que la retention la plus longue.
func (q *Queries) PruneBackupRows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneBackupRows)
	return err
}
