// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const listDailyActivity = `-- name: ListDailyActivity :many
SELECT day, tasks_done, tickets_opened, deliverables_submitted
FROM daily_activity
WHERE day BETWEEN $1::date AND $2::date
ORDER BY day
LIMIT 366
`

type ListDailyActivityParams struct {
	FromDay time.Time `json:"from_day"`
	ToDay   time.Time `json:"to_day"`
}

// Carte « Activite par jour » : une ligne par jour actif de la periode,
// precalculee par declencheur. Les jours sans ligne sont des jours vides.
func (q *Queries) ListDailyActivity(ctx context.Context, arg ListDailyActivityParams) ([]DailyActivity, error) {
	rows, err := q.db.Query(ctx, listDailyActivity, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyActivity{}
	for rows.Next() {
		var i DailyActivity
		if err := rows.Scan(
			&i.Day,
			&i.TasksDone,
			&i.TicketsOpened,
			&i.DeliverablesSubmitted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectWorkload = `-- name: ListProjectWorkload :many
SELECT
    p.id,
    p.name,
    c.name AS client_name,
    p.hours_sold,
    p.hours_spent
FROM projects p
JOIN clients c ON c.id = p.client_id
WHERE p.deleted_at IS NULL
  AND NOT p.is_internal
  AND p.status NOT IN ('livre', 'hebergement')
  AND p.hours_sold > 0
ORDER BY p.hours_spent / p.hours_sold DESC, p.id
LIMIT 8
`

type ListProjectWorkloadRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	ClientName string    `json:"client_name"`
	HoursSold  float64   `json:"hours_sold"`
	HoursSpent float64   `json:"hours_spent"`
}

// Graphique « Charge par projet » : les projets en cours les plus avances
// dans leur budget.
//
// Tri sur la part consommee, pas sur les heures : c'est la derive que le
// graphique doit montrer d'abord. Huit barres tiennent dans la demi-largeur
// du tableau de bord ; au-dela, la liste des projets triee par budget prend
// le relais. Lu sur les heures precalculees, aucune somme au rendu.
func (q *Queries) ListProjectWorkload(ctx context.Context) ([]ListProjectWorkloadRow, error) {
	rows, err := q.db.Query(ctx, listProjectWorkload)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectWorkloadRow{}
	for rows.Next() {
		var i ListProjectWorkloadRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientName,
			&i.HoursSold,
			&i.HoursSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamDay = `-- name: ListTeamDay :many
SELECT
    u.id,
    u.firstname,
    u.lastname,
    u.avatar_url,
    coalesce(sum(e.minutes) FILTER (WHERE e.spent_on = $1::date), 0)::bigint AS today_minutes,
    coalesce(sum(e.minutes) FILTER (WHERE e.spent_on = $1::date AND NOT p.is_internal), 0)::bigint
        AS today_billable_minutes,
    coalesce(sum(e.minutes), 0)::bigint AS week_minutes,
    -- Chaine vide sans saisie du jour : la jointure laterale est externe, et
    -- sqlc ne sait pas qu'elle peut rendre NULL.
    coalesce(last.project_name, '')::text AS last_project,
    coalesce(last.task_title, '')::text   AS last_task
FROM users u
LEFT JOIN time_entries e
       ON e.user_id = u.id
      AND e.deleted_at IS NULL
      AND e.spent_on BETWEEN $2::date AND $1::date
LEFT JOIN projects p ON p.id = e.project_id
LEFT JOIN LATERAL (
    SELECT lp.name AS project_name, lt.title AS task_title
    FROM time_entries le
    JOIN projects lp ON lp.id = le.project_id
    LEFT JOIN tasks lt ON lt.id = le.task_id
    WHERE le.user_id = u.id
      AND le.deleted_at IS NULL
      AND le.spent_on = $1::date
    ORDER BY le.created_at DESC
    LIMIT 1
) AS last ON true
WHERE u.deleted_at IS NULL
  AND u.role IN ('admin', 'team')
GROUP BY u.id, last.project_name, last.task_title
ORDER BY today_minutes DESC, week_minutes DESC, u.firstname, u.lastname, u.id
LIMIT 50
`

type ListTeamDayParams struct {
	Today     time.Time `json:"today"`
	WeekStart time.Time `json:"week_start"`
}

type ListTeamDayRow struct {
	ID                   uuid.UUID `json:"id"`
	Firstname            string    `json:"firstname"`
	Lastname             string    `json:"lastname"`
	AvatarUrl            *string   `json:"avatar_url"`
	TodayMinutes         int64     `json:"today_minutes"`
	TodayBillableMinutes int64     `json:"today_billable_minutes"`
	WeekMinutes          int64     `json:"week_minutes"`
	LastProject          string    `json:"last_project"`
	LastTask             string    `json:"last_task"`
}

// Carte « Equipe aujourd'hui » : ce que chaque membre a saisi aujourd'hui et
// depuis lundi, et sur quoi il a pointe en dernier.
//
// Une somme au rendu, contrairement a la regle du projet. Elle est admise
// parce qu'elle ne porte que sur la semaine en cours — quelques dizaines de
// saisies par personne — et passe par l'index (user_id, spent_on). Un
// precalcul par personne et par jour dupliquerait la table des saisies sans
// rien faire gagner a cette echelle.
// Derniere saisie du jour : ce qui dit « sur quoi il travaille ».
func (q *Queries) ListTeamDay(ctx context.Context, arg ListTeamDayParams) ([]ListTeamDayRow, error) {
	rows, err := q.db.Query(ctx, listTeamDay, arg.Today, arg.WeekStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamDayRow{}
	for rows.Next() {
		var i ListTeamDayRow
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.AvatarUrl,
			&i.TodayMinutes,
			&i.TodayBillableMinutes,
			&i.WeekMinutes,
			&i.LastProject,
			&i.LastTask,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
