// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliverables.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const countDeliverables = `-- name: CountDeliverables :one
SELECT count(*)
FROM deliverables d
JOIN projects p ON p.id = d.project_id AND p.deleted_at IS NULL
JOIN clients c ON c.id = p.client_id AND c.deleted_at IS NULL
LEFT JOIN deliverable_versions v ON v.id = d.current_version_id
WHERE d.deleted_at IS NULL
  AND ($1::text IS NULL
       OR coalesce(v.decision, 'brouillon') = $1::text)
  AND ($2::uuid IS NULL OR d.project_id = $2::uuid)
  AND ($3::text IS NULL
       OR d.title ILIKE '%' || $3::text || '%')
`

type CountDeliverablesParams struct {
	Status    *string    `json:"status"`
	ProjectID *uuid.UUID `json:"project_id"`
	Search    *string    `json:"search"`
}

// Total pour la pagination, aux memes conditions que la liste.
func (q *Queries) CountDeliverables(ctx context.Context, arg CountDeliverablesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliverables, arg.Status, arg.ProjectID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeliverable = `-- name: CreateDeliverable :one
INSERT INTO deliverables (project_id, title, description, created_by)
VALUES (
    $1, $2,
    $3, $4
)
RETURNING id
`

type CreateDeliverableParams struct {
	ProjectID   uuid.UUID  `json:"project_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

// Le livrable nait sans version : c'est la soumission qui lui en donne une.
func (q *Queries) CreateDeliverable(ctx context.Context, arg CreateDeliverableParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createDeliverable,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createDeliverableVersion = `-- name: CreateDeliverableVersion :one
INSERT INTO deliverable_versions (
    deliverable_id, numero, attachment_id, url, submitted_by
)
VALUES (
    $1, $2,
    $3, $4, $5
)
RETURNING id
`

type CreateDeliverableVersionParams struct {
	DeliverableID uuid.UUID  `json:"deliverable_id"`
	Numero        int32      `json:"numero"`
	AttachmentID  *uuid.UUID `json:"attachment_id"`
	Url           string     `json:"url"`
	SubmittedBy   *uuid.UUID `json:"submitted_by"`
}

func (q *Queries) CreateDeliverableVersion(ctx context.Context, arg CreateDeliverableVersionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createDeliverableVersion,
		arg.DeliverableID,
		arg.Numero,
		arg.AttachmentID,
		arg.Url,
		arg.SubmittedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const decideDeliverableVersion = `-- name: DecideDeliverableVersion :exec
UPDATE deliverable_versions
SET decision   = $1,
    decided_at = now(),
    decided_by = $2,
    feedback   = $3
WHERE id = $4 AND decision = 'en_attente'
`

type DecideDeliverableVersionParams struct {
	Decision  string     `json:"decision"`
	DecidedBy *uuid.UUID `json:"decided_by"`
	Feedback  string     `json:"feedback"`
	ID        uuid.UUID  `json:"id"`
}

// Enregistre la reponse du client sur une version precise.
//
// La clause sur `decision` rend la requete rejouable sans degat : une decision
// deja prise ne se reecrit pas, et l'appelant lit zero ligne touchee plutot que
// d'ecraser la date et l'auteur d'origine.
func (q *Queries) DecideDeliverableVersion(ctx context.Context, arg DecideDeliverableVersionParams) error {
	_, err := q.db.Exec(ctx, decideDeliverableVersion,
		arg.Decision,
		arg.DecidedBy,
		arg.Feedback,
		arg.ID,
	)
	return err
}

const getDeliverable = `-- name: GetDeliverable :one
SELECT
    d.id,
    d.title,
    d.created_at,
    coalesce(v.decision, 'brouillon') AS status,
    p.id   AS project_id,
    p.name AS project_name,
    c.id   AS client_id,
    c.name AS client_name,
    v.id           AS version_id,
    v.numero       AS version_numero,
    v.url          AS version_url,
    v.attachment_id,
    v.submitted_at,
    v.decided_at,
    v.feedback,
    s.id         AS submitter_id,
    s.firstname  AS submitter_firstname,
    s.lastname   AS submitter_lastname,
    s.avatar_url AS submitter_avatar_url
FROM deliverables d
JOIN projects p ON p.id = d.project_id AND p.deleted_at IS NULL
JOIN clients c ON c.id = p.client_id AND c.deleted_at IS NULL
LEFT JOIN deliverable_versions v ON v.id = d.current_version_id
LEFT JOIN users s ON s.id = v.submitted_by AND s.deleted_at IS NULL
WHERE d.id = $1 AND d.deleted_at IS NULL
`

type GetDeliverableRow struct {
	ID                 uuid.UUID  `json:"id"`
	Title              string     `json:"title"`
	CreatedAt          time.Time  `json:"created_at"`
	Status             string     `json:"status"`
	ProjectID          uuid.UUID  `json:"project_id"`
	ProjectName        string     `json:"project_name"`
	ClientID           uuid.UUID  `json:"client_id"`
	ClientName         string     `json:"client_name"`
	VersionID          *uuid.UUID `json:"version_id"`
	VersionNumero      *int32     `json:"version_numero"`
	VersionUrl         *string    `json:"version_url"`
	AttachmentID       *uuid.UUID `json:"attachment_id"`
	SubmittedAt        *time.Time `json:"submitted_at"`
	DecidedAt          *time.Time `json:"decided_at"`
	Feedback           *string    `json:"feedback"`
	SubmitterID        *uuid.UUID `json:"submitter_id"`
	SubmitterFirstname *string    `json:"submitter_firstname"`
	SubmitterLastname  *string    `json:"submitter_lastname"`
	SubmitterAvatarUrl *string    `json:"submitter_avatar_url"`
}

// Un livrable et sa version courante, aux memes colonnes que la liste : le
// depot et la decision rendent la ligne telle que l'ecran la reaffiche.
func (q *Queries) GetDeliverable(ctx context.Context, id uuid.UUID) (GetDeliverableRow, error) {
	row := q.db.QueryRow(ctx, getDeliverable, id)
	var i GetDeliverableRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.Status,
		&i.ProjectID,
		&i.ProjectName,
		&i.ClientID,
		&i.ClientName,
		&i.VersionID,
		&i.VersionNumero,
		&i.VersionUrl,
		&i.AttachmentID,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.Feedback,
		&i.SubmitterID,
		&i.SubmitterFirstname,
		&i.SubmitterLastname,
		&i.SubmitterAvatarUrl,
	)
	return i, err
}

const listDeliverableVersions = `-- name: ListDeliverableVersions :many
SELECT
    v.id,
    v.numero,
    v.url,
    v.attachment_id,
    v.submitted_at,
    v.decision,
    v.decided_at,
    v.feedback,
    s.id         AS submitter_id,
    s.firstname  AS submitter_firstname,
    s.lastname   AS submitter_lastname,
    s.avatar_url AS submitter_avatar_url,
    r.id         AS decider_id,
    r.firstname  AS decider_firstname,
    r.lastname   AS decider_lastname,
    r.avatar_url AS decider_avatar_url,
    -- A quel titre la decision a ete rendue : le client lui-meme, ou l'agence
    -- qui enregistre une reponse recue ailleurs. Les deux portent le droit.
    r.role       AS decider_role
FROM deliverable_versions v
LEFT JOIN users s ON s.id = v.submitted_by AND s.deleted_at IS NULL
LEFT JOIN users r ON r.id = v.decided_by AND r.deleted_at IS NULL
WHERE v.deliverable_id = $1
ORDER BY v.numero
`

type ListDeliverableVersionsRow struct {
	ID                 uuid.UUID  `json:"id"`
	Numero             int32      `json:"numero"`
	Url                string     `json:"url"`
	AttachmentID       *uuid.UUID `json:"attachment_id"`
	SubmittedAt        time.Time  `json:"submitted_at"`
	Decision           string     `json:"decision"`
	DecidedAt          *time.Time `json:"decided_at"`
	Feedback           string     `json:"feedback"`
	SubmitterID        *uuid.UUID `json:"submitter_id"`
	SubmitterFirstname *string    `json:"submitter_firstname"`
	SubmitterLastname  *string    `json:"submitter_lastname"`
	SubmitterAvatarUrl *string    `json:"submitter_avatar_url"`
	DeciderID          *uuid.UUID `json:"decider_id"`
	DeciderFirstname   *string    `json:"decider_firstname"`
	DeciderLastname    *string    `json:"decider_lastname"`
	DeciderAvatarUrl   *string    `json:"decider_avatar_url"`
	DeciderRole        *string    `json:"decider_role"`
}

// Le fil complet d'un livrable, de la premiere version a la derniere : c'est
// la trace que le module existe pour garder.
func (q *Queries) ListDeliverableVersions(ctx context.Context, deliverableID uuid.UUID) ([]ListDeliverableVersionsRow, error) {
	rows, err := q.db.Query(ctx, listDeliverableVersions, deliverableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliverableVersionsRow{}
	for rows.Next() {
		var i ListDeliverableVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Url,
			&i.AttachmentID,
			&i.SubmittedAt,
			&i.Decision,
			&i.DecidedAt,
			&i.Feedback,
			&i.SubmitterID,
			&i.SubmitterFirstname,
			&i.SubmitterLastname,
			&i.SubmitterAvatarUrl,
			&i.DeciderID,
			&i.DeciderFirstname,
			&i.DeciderLastname,
			&i.DeciderAvatarUrl,
			&i.DeciderRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliverables = `-- name: ListDeliverables :many

SELECT
    d.id,
    d.title,
    d.created_at,
    coalesce(v.decision, 'brouillon') AS status,
    p.id   AS project_id,
    p.name AS project_name,
    c.id   AS client_id,
    c.name AS client_name,
    v.id           AS version_id,
    v.numero       AS version_numero,
    v.url          AS version_url,
    v.attachment_id,
    v.submitted_at,
    v.decided_at,
    v.feedback,
    s.id         AS submitter_id,
    s.firstname  AS submitter_firstname,
    s.lastname   AS submitter_lastname,
    s.avatar_url AS submitter_avatar_url
FROM deliverables d
JOIN projects p ON p.id = d.project_id AND p.deleted_at IS NULL
JOIN clients c ON c.id = p.client_id AND c.deleted_at IS NULL
LEFT JOIN deliverable_versions v ON v.id = d.current_version_id
LEFT JOIN users s ON s.id = v.submitted_by AND s.deleted_at IS NULL
WHERE d.deleted_at IS NULL
  AND ($1::text IS NULL
       OR coalesce(v.decision, 'brouillon') = $1::text)
  AND ($2::uuid IS NULL OR d.project_id = $2::uuid)
  AND ($3::text IS NULL
       OR d.title ILIKE '%' || $3::text || '%')
ORDER BY v.submitted_at DESC NULLS LAST, d.created_at DESC, d.id
LIMIT $5 OFFSET $4
`

type ListDeliverablesParams struct {
	Status     *string    `json:"status"`
	ProjectID  *uuid.UUID `json:"project_id"`
	Search     *string    `json:"search"`
	PageOffset int32      `json:"page_offset"`
	PageSize   int32      `json:"page_size"`
}

type ListDeliverablesRow struct {
	ID                 uuid.UUID  `json:"id"`
	Title              string     `json:"title"`
	CreatedAt          time.Time  `json:"created_at"`
	Status             string     `json:"status"`
	ProjectID          uuid.UUID  `json:"project_id"`
	ProjectName        string     `json:"project_name"`
	ClientID           uuid.UUID  `json:"client_id"`
	ClientName         string     `json:"client_name"`
	VersionID          *uuid.UUID `json:"version_id"`
	VersionNumero      *int32     `json:"version_numero"`
	VersionUrl         *string    `json:"version_url"`
	AttachmentID       *uuid.UUID `json:"attachment_id"`
	SubmittedAt        *time.Time `json:"submitted_at"`
	DecidedAt          *time.Time `json:"decided_at"`
	Feedback           *string    `json:"feedback"`
	SubmitterID        *uuid.UUID `json:"submitter_id"`
	SubmitterFirstname *string    `json:"submitter_firstname"`
	SubmitterLastname  *string    `json:"submitter_lastname"`
	SubmitterAvatarUrl *string    `json:"submitter_avatar_url"`
}

// Livrables.
//
// L'etat d'un livrable n'est pas une colonne : c'est la decision de sa version
// courante, et l'absence de version vaut brouillon. Toutes les requetes qui
// l'affichent joignent donc `deliverable_versions` sur `current_version_id` —
// une jointure sur cle primaire, pas un LATERAL par ligne.
// L'ecran « Livrables » du module, qui traverse les projets.
//
// Trie du plus recemment soumis au plus ancien, les brouillons en queue : c'est
// l'ordre dans lequel on reprend un dossier. L'anciennete d'une attente se lit
// sur `submitted_at`, que l'ecran compare a maintenant — une duree renvoyee ici
// serait fausse des la seconde suivante.
func (q *Queries) ListDeliverables(ctx context.Context, arg ListDeliverablesParams) ([]ListDeliverablesRow, error) {
	rows, err := q.db.Query(ctx, listDeliverables,
		arg.Status,
		arg.ProjectID,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliverablesRow{}
	for rows.Next() {
		var i ListDeliverablesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.Status,
			&i.ProjectID,
			&i.ProjectName,
			&i.ClientID,
			&i.ClientName,
			&i.VersionID,
			&i.VersionNumero,
			&i.VersionUrl,
			&i.AttachmentID,
			&i.SubmittedAt,
			&i.DecidedAt,
			&i.Feedback,
			&i.SubmitterID,
			&i.SubmitterFirstname,
			&i.SubmitterLastname,
			&i.SubmitterAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeliverable = `-- name: LockDeliverable :one
SELECT id, project_id, current_version_id
FROM deliverables
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

type LockDeliverableRow struct {
	ID               uuid.UUID  `json:"id"`
	ProjectID        uuid.UUID  `json:"project_id"`
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
}

// Verrou avant d'ajouter une version ou de trancher : deux soumissions
// simultanees prendraient sinon le meme numero.
func (q *Queries) LockDeliverable(ctx context.Context, id uuid.UUID) (LockDeliverableRow, error) {
	row := q.db.QueryRow(ctx, lockDeliverable, id)
	var i LockDeliverableRow
	err := row.Scan(&i.ID, &i.ProjectID, &i.CurrentVersionID)
	return i, err
}

const nextDeliverableVersionNumero = `-- name: NextDeliverableVersionNumero :one
SELECT coalesce(max(numero), 0) + 1
FROM deliverable_versions
WHERE deliverable_id = $1
`

// Le numero suivant, sous le verrou pose juste avant.
func (q *Queries) NextDeliverableVersionNumero(ctx context.Context, deliverableID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextDeliverableVersionNumero, deliverableID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setDeliverableCurrentVersion = `-- name: SetDeliverableCurrentVersion :exec
UPDATE deliverables
SET current_version_id = $1,
    updated_at = now()
WHERE id = $2
`

type SetDeliverableCurrentVersionParams struct {
	VersionID *uuid.UUID `json:"version_id"`
	ID        uuid.UUID  `json:"id"`
}

// La version qui vient d'etre soumise devient celle que l'ecran montre.
func (q *Queries) SetDeliverableCurrentVersion(ctx context.Context, arg SetDeliverableCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setDeliverableCurrentVersion, arg.VersionID, arg.ID)
	return err
}

const touchDeliverable = `-- name: TouchDeliverable :exec
UPDATE deliverables SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchDeliverable(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDeliverable, id)
	return err
}
