// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbound.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const claimPendingInbound = `-- name: ClaimPendingInbound :one
SELECT id, received_at, source, message_id, from_address, from_name, subject, excerpt, attachment_count, raw, status, reason, client_id, ticket_id, attempts, error, processed_at FROM inbound_emails
WHERE status = 'pending'
ORDER BY received_at
LIMIT 1
FOR UPDATE SKIP LOCKED
`

// Le prochain e-mail a ranger, verrouille le temps de le traiter : deux
// instances pendant un deploiement ne rangent pas deux fois le meme.
func (q *Queries) ClaimPendingInbound(ctx context.Context) (InboundEmail, error) {
	row := q.db.QueryRow(ctx, claimPendingInbound)
	var i InboundEmail
	err := row.Scan(
		&i.ID,
		&i.ReceivedAt,
		&i.Source,
		&i.MessageID,
		&i.FromAddress,
		&i.FromName,
		&i.Subject,
		&i.Excerpt,
		&i.AttachmentCount,
		&i.Raw,
		&i.Status,
		&i.Reason,
		&i.ClientID,
		&i.TicketID,
		&i.Attempts,
		&i.Error,
		&i.ProcessedAt,
	)
	return i, err
}

const countHeldInbound = `-- name: CountHeldInbound :one
SELECT count(*)::integer FROM inbound_emails WHERE status = 'held'
`

func (q *Queries) CountHeldInbound(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countHeldInbound)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countTicketsOpenedByEmailFrom = `-- name: CountTicketsOpenedByEmailFrom :one
SELECT count(*)::integer FROM inbound_emails
WHERE from_address = $1
  AND status = 'processed' AND reason = 'created'
  AND received_at > now() - interval '1 hour'
`

// Les tickets qu'une adresse a ouverts par e-mail dans l'heure : au-dela d'un
// seuil, deux robots se repondent, et l'e-mail attend un humain.
func (q *Queries) CountTicketsOpenedByEmailFrom(ctx context.Context, fromAddress string) (int32, error) {
	row := q.db.QueryRow(ctx, countTicketsOpenedByEmailFrom, fromAddress)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const failInboundAttempt = `-- name: FailInboundAttempt :exec
UPDATE inbound_emails SET
    attempts = attempts + 1,
    error    = $1,
    status   = CASE WHEN attempts + 1 >= 5 THEN 'failed' ELSE 'pending' END
WHERE id = $2
`

type FailInboundAttemptParams struct {
	Error string    `json:"error"`
	ID    uuid.UUID `json:"id"`
}

// Une erreur passagere (base, disque) : on reessaie, cinq fois au plus.
func (q *Queries) FailInboundAttempt(ctx context.Context, arg FailInboundAttemptParams) error {
	_, err := q.db.Exec(ctx, failInboundAttempt, arg.Error, arg.ID)
	return err
}

const findActiveUserByEmail = `-- name: FindActiveUserByEmail :one
SELECT id, role, client_id, firstname, lastname
FROM users
WHERE email = $1 AND deleted_at IS NULL AND disabled_at IS NULL
`

type FindActiveUserByEmailRow struct {
	ID        uuid.UUID  `json:"id"`
	Role      string     `json:"role"`
	ClientID  *uuid.UUID `json:"client_id"`
	Firstname string     `json:"firstname"`
	Lastname  string     `json:"lastname"`
}

func (q *Queries) FindActiveUserByEmail(ctx context.Context, email string) (FindActiveUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findActiveUserByEmail, email)
	var i FindActiveUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.ClientID,
		&i.Firstname,
		&i.Lastname,
	)
	return i, err
}

const findContactsByEmail = `-- name: FindContactsByEmail :many
SELECT ct.id, ct.client_id, ct.firstname, ct.lastname
FROM contacts ct
JOIN clients c ON c.id = ct.client_id AND c.deleted_at IS NULL
WHERE ct.email = $1 AND ct.deleted_at IS NULL
LIMIT 10
`

type FindContactsByEmailRow struct {
	ID        uuid.UUID  `json:"id"`
	ClientID  *uuid.UUID `json:"client_id"`
	Firstname string     `json:"firstname"`
	Lastname  string     `json:"lastname"`
}

// Les contacts du CRM qui portent cette adresse, sur des clients actifs.
func (q *Queries) FindContactsByEmail(ctx context.Context, email *string) ([]FindContactsByEmailRow, error) {
	rows, err := q.db.Query(ctx, findContactsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindContactsByEmailRow{}
	for rows.Next() {
		var i FindContactsByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Firstname,
			&i.Lastname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishInboundEmail = `-- name: FinishInboundEmail :exec
UPDATE inbound_emails SET
    status       = $1,
    reason       = $2,
    client_id    = $3,
    ticket_id    = $4,
    error        = $5,
    processed_at = now()
WHERE id = $6
`

type FinishInboundEmailParams struct {
	Status   string     `json:"status"`
	Reason   string     `json:"reason"`
	ClientID *uuid.UUID `json:"client_id"`
	TicketID *uuid.UUID `json:"ticket_id"`
	Error    string     `json:"error"`
	ID       uuid.UUID  `json:"id"`
}

func (q *Queries) FinishInboundEmail(ctx context.Context, arg FinishInboundEmailParams) error {
	_, err := q.db.Exec(ctx, finishInboundEmail,
		arg.Status,
		arg.Reason,
		arg.ClientID,
		arg.TicketID,
		arg.Error,
		arg.ID,
	)
	return err
}

const getInboundEmail = `-- name: GetInboundEmail :one
SELECT e.id, e.received_at, e.source, e.message_id, e.from_address, e.from_name, e.subject, e.excerpt, e.attachment_count, e.raw, e.status, e.reason, e.client_id, e.ticket_id, e.attempts, e.error, e.processed_at, c.name AS client_name
FROM inbound_emails e
LEFT JOIN clients c ON c.id = e.client_id AND c.deleted_at IS NULL
WHERE e.id = $1
`

type GetInboundEmailRow struct {
	ID              uuid.UUID  `json:"id"`
	ReceivedAt      time.Time  `json:"received_at"`
	Source          string     `json:"source"`
	MessageID       string     `json:"message_id"`
	FromAddress     string     `json:"from_address"`
	FromName        string     `json:"from_name"`
	Subject         string     `json:"subject"`
	Excerpt         string     `json:"excerpt"`
	AttachmentCount int32      `json:"attachment_count"`
	Raw             []byte     `json:"raw"`
	Status          string     `json:"status"`
	Reason          string     `json:"reason"`
	ClientID        *uuid.UUID `json:"client_id"`
	TicketID        *uuid.UUID `json:"ticket_id"`
	Attempts        int32      `json:"attempts"`
	Error           string     `json:"error"`
	ProcessedAt     *time.Time `json:"processed_at"`
	ClientName      *string    `json:"client_name"`
}

func (q *Queries) GetInboundEmail(ctx context.Context, id uuid.UUID) (GetInboundEmailRow, error) {
	row := q.db.QueryRow(ctx, getInboundEmail, id)
	var i GetInboundEmailRow
	err := row.Scan(
		&i.ID,
		&i.ReceivedAt,
		&i.Source,
		&i.MessageID,
		&i.FromAddress,
		&i.FromName,
		&i.Subject,
		&i.Excerpt,
		&i.AttachmentCount,
		&i.Raw,
		&i.Status,
		&i.Reason,
		&i.ClientID,
		&i.TicketID,
		&i.Attempts,
		&i.Error,
		&i.ProcessedAt,
		&i.ClientName,
	)
	return i, err
}

const getInboundSettings = `-- name: GetInboundSettings :one

SELECT id, address, imap_enabled, imap_host, imap_port, imap_security, imap_username, imap_password_enc, imap_folder, webhook_secret, last_poll_at, last_poll_error, poll_requested_at, updated_at FROM inbound_mail_settings WHERE id = 1
`

// E-mail entrant : reglages, file des e-mails recus, tri.
func (q *Queries) GetInboundSettings(ctx context.Context) (InboundMailSetting, error) {
	row := q.db.QueryRow(ctx, getInboundSettings)
	var i InboundMailSetting
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.ImapEnabled,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapSecurity,
		&i.ImapUsername,
		&i.ImapPasswordEnc,
		&i.ImapFolder,
		&i.WebhookSecret,
		&i.LastPollAt,
		&i.LastPollError,
		&i.PollRequestedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectClientForTriage = `-- name: GetProjectClientForTriage :one
SELECT client_id FROM projects
WHERE id = $1 AND deleted_at IS NULL AND NOT is_internal
`

// Le client d'un projet choisi au tri. Un projet interne n'en a pas a qui
// repondre : il est refuse.
func (q *Queries) GetProjectClientForTriage(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProjectClientForTriage, id)
	var client_id uuid.UUID
	err := row.Scan(&client_id)
	return client_id, err
}

const inboundStats = `-- name: InboundStats :one
SELECT
    count(*) FILTER (WHERE status = 'pending')::integer AS pending,
    count(*) FILTER (WHERE status = 'held')::integer    AS held,
    count(*) FILTER (WHERE status = 'processed' AND processed_at > now() - interval '24 hours')::integer AS processed_day,
    count(*) FILTER (WHERE status = 'failed' AND received_at > now() - interval '7 days')::integer AS failed_week
FROM inbound_emails
WHERE status IN ('pending', 'held') OR received_at > now() - interval '7 days'
`

type InboundStatsRow struct {
	Pending      int32 `json:"pending"`
	Held         int32 `json:"held"`
	ProcessedDay int32 `json:"processed_day"`
	FailedWeek   int32 `json:"failed_week"`
}

func (q *Queries) InboundStats(ctx context.Context) (InboundStatsRow, error) {
	row := q.db.QueryRow(ctx, inboundStats)
	var i InboundStatsRow
	err := row.Scan(
		&i.Pending,
		&i.Held,
		&i.ProcessedDay,
		&i.FailedWeek,
	)
	return i, err
}

const insertInboundEmail = `-- name: InsertInboundEmail :many
INSERT INTO inbound_emails (source, message_id, from_address, from_name, subject, excerpt, attachment_count, raw)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
ON CONFLICT (message_id) WHERE message_id <> '' DO NOTHING
RETURNING id
`

type InsertInboundEmailParams struct {
	Source          string `json:"source"`
	MessageID       string `json:"message_id"`
	FromAddress     string `json:"from_address"`
	FromName        string `json:"from_name"`
	Subject         string `json:"subject"`
	Excerpt         string `json:"excerpt"`
	AttachmentCount int32  `json:"attachment_count"`
	Raw             []byte `json:"raw"`
}

// Un e-mail deja recu — releve rejouee, webhook renvoye — ne rentre pas une
// seconde fois : la ligne n'est pas rendue.
func (q *Queries) InsertInboundEmail(ctx context.Context, arg InsertInboundEmailParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, insertInboundEmail,
		arg.Source,
		arg.MessageID,
		arg.FromAddress,
		arg.FromName,
		arg.Subject,
		arg.Excerpt,
		arg.AttachmentCount,
		arg.Raw,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeldInbound = `-- name: ListHeldInbound :many
SELECT e.id, e.received_at, e.source, e.from_address, e.from_name, e.subject, e.excerpt,
       e.attachment_count, e.reason, e.client_id, c.name AS client_name
FROM inbound_emails e
LEFT JOIN clients c ON c.id = e.client_id AND c.deleted_at IS NULL
WHERE e.status = 'held'
ORDER BY e.received_at DESC, e.id
LIMIT $2 OFFSET $1
`

type ListHeldInboundParams struct {
	Skip    int32 `json:"skip"`
	MaxRows int32 `json:"max_rows"`
}

type ListHeldInboundRow struct {
	ID              uuid.UUID  `json:"id"`
	ReceivedAt      time.Time  `json:"received_at"`
	Source          string     `json:"source"`
	FromAddress     string     `json:"from_address"`
	FromName        string     `json:"from_name"`
	Subject         string     `json:"subject"`
	Excerpt         string     `json:"excerpt"`
	AttachmentCount int32      `json:"attachment_count"`
	Reason          string     `json:"reason"`
	ClientID        *uuid.UUID `json:"client_id"`
	ClientName      *string    `json:"client_name"`
}

// Les e-mails a trier, les plus recents d'abord.
func (q *Queries) ListHeldInbound(ctx context.Context, arg ListHeldInboundParams) ([]ListHeldInboundRow, error) {
	rows, err := q.db.Query(ctx, listHeldInbound, arg.Skip, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeldInboundRow{}
	for rows.Next() {
		var i ListHeldInboundRow
		if err := rows.Scan(
			&i.ID,
			&i.ReceivedAt,
			&i.Source,
			&i.FromAddress,
			&i.FromName,
			&i.Subject,
			&i.Excerpt,
			&i.AttachmentCount,
			&i.Reason,
			&i.ClientID,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketProjectsOfClient = `-- name: ListTicketProjectsOfClient :many
SELECT p.id, p.name, p.status
FROM projects p
WHERE p.client_id = $1
  AND p.deleted_at IS NULL
  AND NOT p.is_internal
  AND p.status IN ('cadrage', 'production', 'attente', 'hebergement')
ORDER BY p.updated_at DESC, p.id
LIMIT 20
`

type ListTicketProjectsOfClientRow struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Status string    `json:"status"`
}

// Les projets d'un client qui recoivent des tickets : en cours, en attente,
// ou heberges. Un projet livre et clos n'en attend plus.
func (q *Queries) ListTicketProjectsOfClient(ctx context.Context, clientID uuid.UUID) ([]ListTicketProjectsOfClientRow, error) {
	rows, err := q.db.Query(ctx, listTicketProjectsOfClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketProjectsOfClientRow{}
	for rows.Next() {
		var i ListTicketProjectsOfClientRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketProjectsOfClients = `-- name: ListTicketProjectsOfClients :many
SELECT p.client_id, p.id, p.name
FROM projects p
WHERE p.client_id = ANY($1::uuid[])
  AND p.deleted_at IS NULL
  AND NOT p.is_internal
  AND p.status IN ('cadrage', 'production', 'attente', 'hebergement')
ORDER BY p.updated_at DESC, p.id
LIMIT 500
`

type ListTicketProjectsOfClientsRow struct {
	ClientID uuid.UUID `json:"client_id"`
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
}

// Les memes, pour plusieurs clients d'un coup : la liste a trier propose a
// chaque e-mail les projets de son client.
func (q *Queries) ListTicketProjectsOfClients(ctx context.Context, clientIds []uuid.UUID) ([]ListTicketProjectsOfClientsRow, error) {
	rows, err := q.db.Query(ctx, listTicketProjectsOfClients, clientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketProjectsOfClientsRow{}
	for rows.Next() {
		var i ListTicketProjectsOfClientsRow
		if err := rows.Scan(&i.ClientID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriageRecipients = `-- name: ListTriageRecipients :many
SELECT id FROM users
WHERE role = 'admin' AND deleted_at IS NULL AND disabled_at IS NULL
LIMIT 50
`

// Qui prevenir d'un e-mail a trier : les administrateurs actifs.
func (q *Queries) ListTriageRecipients(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTriageRecipients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInboundEmail = `-- name: LockInboundEmail :one
SELECT id, received_at, source, message_id, from_address, from_name, subject, excerpt, attachment_count, raw, status, reason, client_id, ticket_id, attempts, error, processed_at FROM inbound_emails WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockInboundEmail(ctx context.Context, id uuid.UUID) (InboundEmail, error) {
	row := q.db.QueryRow(ctx, lockInboundEmail, id)
	var i InboundEmail
	err := row.Scan(
		&i.ID,
		&i.ReceivedAt,
		&i.Source,
		&i.MessageID,
		&i.FromAddress,
		&i.FromName,
		&i.Subject,
		&i.Excerpt,
		&i.AttachmentCount,
		&i.Raw,
		&i.Status,
		&i.Reason,
		&i.ClientID,
		&i.TicketID,
		&i.Attempts,
		&i.Error,
		&i.ProcessedAt,
	)
	return i, err
}

const recordInboundPoll = `-- name: RecordInboundPoll :exec
UPDATE inbound_mail_settings
SET last_poll_at = now(), last_poll_error = $1, poll_requested_at = NULL
WHERE id = 1
`

func (q *Queries) RecordInboundPoll(ctx context.Context, error string) error {
	_, err := q.db.Exec(ctx, recordInboundPoll, error)
	return err
}

const requestInboundPoll = `-- name: RequestInboundPoll :exec
UPDATE inbound_mail_settings SET poll_requested_at = now() WHERE id = 1
`

func (q *Queries) RequestInboundPoll(ctx context.Context) error {
	_, err := q.db.Exec(ctx, requestInboundPoll)
	return err
}

const setInboundWebhookSecret = `-- name: SetInboundWebhookSecret :exec
UPDATE inbound_mail_settings SET webhook_secret = $1, updated_at = now() WHERE id = 1
`

func (q *Queries) SetInboundWebhookSecret(ctx context.Context, secret string) error {
	_, err := q.db.Exec(ctx, setInboundWebhookSecret, secret)
	return err
}

const updateInboundSettings = `-- name: UpdateInboundSettings :exec
UPDATE inbound_mail_settings SET
    address           = $1,
    imap_enabled      = $2,
    imap_host         = $3,
    imap_port         = $4,
    imap_security     = $5,
    imap_username     = $6,
    imap_folder       = $7,
    imap_password_enc = CASE WHEN $8::boolean THEN $9 ELSE imap_password_enc END,
    updated_at        = now()
WHERE id = 1
`

type UpdateInboundSettingsParams struct {
	Address         string `json:"address"`
	ImapEnabled     bool   `json:"imap_enabled"`
	ImapHost        string `json:"imap_host"`
	ImapPort        int32  `json:"imap_port"`
	ImapSecurity    string `json:"imap_security"`
	ImapUsername    string `json:"imap_username"`
	ImapFolder      string `json:"imap_folder"`
	SetPassword     bool   `json:"set_password"`
	ImapPasswordEnc []byte `json:"imap_password_enc"`
}

// Le mot de passe n'est remplace que s'il est fourni : l'ecran ne le relit
// jamais, et un champ laisse vide garde celui en place.
func (q *Queries) UpdateInboundSettings(ctx context.Context, arg UpdateInboundSettingsParams) error {
	_, err := q.db.Exec(ctx, updateInboundSettings,
		arg.Address,
		arg.ImapEnabled,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapSecurity,
		arg.ImapUsername,
		arg.ImapFolder,
		arg.SetPassword,
		arg.ImapPasswordEnc,
	)
	return err
}
