// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations SET accepted_at = now(), user_id = $2, updated_at = now()
WHERE id = $1
`

type AcceptInvitationParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) error {
	_, err := q.db.Exec(ctx, acceptInvitation, arg.ID, arg.UserID)
	return err
}

const countOpenInvitations = `-- name: CountOpenInvitations :one
SELECT count(*) FROM invitations WHERE accepted_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) CountOpenInvitations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenInvitations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentPasswordResets = `-- name: CountRecentPasswordResets :one
SELECT count(*) FROM password_resets
WHERE user_id = $1 AND created_at > now() - interval '1 hour'
`

// Borne par compte : un tiers qui connait une adresse ne doit pas pouvoir la
// noyer sous les e-mails de reinitialisation.
func (q *Queries) CountRecentPasswordResets(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentPasswordResets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (email, firstname, lastname, role, client_id, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, firstname, lastname, role, client_id, token_hash, invited_by, expires_at, accepted_at, revoked_at, user_id, created_at, updated_at
`

type CreateInvitationParams struct {
	Email     string     `json:"email"`
	Firstname string     `json:"firstname"`
	Lastname  string     `json:"lastname"`
	Role      string     `json:"role"`
	ClientID  *uuid.UUID `json:"client_id"`
	TokenHash []byte     `json:"token_hash"`
	InvitedBy *uuid.UUID `json:"invited_by"`
	ExpiresAt time.Time  `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.Firstname,
		arg.Lastname,
		arg.Role,
		arg.ClientID,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.ClientID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getClientName = `-- name: GetClientName :one
SELECT name FROM clients WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetClientName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getClientName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, email, firstname, lastname, role, client_id, token_hash, invited_by, expires_at, accepted_at, revoked_at, user_id, created_at, updated_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitation(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.ClientID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT
    i.id, i.email, i.firstname, i.lastname, i.role, i.client_id, i.token_hash, i.invited_by, i.expires_at, i.accepted_at, i.revoked_at, i.user_id, i.created_at, i.updated_at,
    coalesce(btrim(u.firstname || ' ' || u.lastname), '')::text AS inviter_name,
    coalesce(c.name, '')::text                                   AS client_name
FROM invitations i
LEFT JOIN users u   ON u.id = i.invited_by
LEFT JOIN clients c ON c.id = i.client_id
WHERE i.token_hash = $1
`

type GetInvitationByTokenRow struct {
	ID          uuid.UUID  `json:"id"`
	Email       string     `json:"email"`
	Firstname   string     `json:"firstname"`
	Lastname    string     `json:"lastname"`
	Role        string     `json:"role"`
	ClientID    *uuid.UUID `json:"client_id"`
	TokenHash   []byte     `json:"token_hash"`
	InvitedBy   *uuid.UUID `json:"invited_by"`
	ExpiresAt   time.Time  `json:"expires_at"`
	AcceptedAt  *time.Time `json:"accepted_at"`
	RevokedAt   *time.Time `json:"revoked_at"`
	UserID      *uuid.UUID `json:"user_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	InviterName string     `json:"inviter_name"`
	ClientName  string     `json:"client_name"`
}

// Page d'acceptation : l'invitation, qui l'a envoyee et pour quel client.
// Rendue meme expiree ou deja acceptee : c'est l'appelant qui dit pourquoi le
// lien ne vaut plus, et l'ecran l'explique.
func (q *Queries) GetInvitationByToken(ctx context.Context, tokenHash []byte) (GetInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, tokenHash)
	var i GetInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.ClientID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InviterName,
		&i.ClientName,
	)
	return i, err
}

const getOpenInvitationByEmail = `-- name: GetOpenInvitationByEmail :one
SELECT id, email, firstname, lastname, role, client_id, token_hash, invited_by, expires_at, accepted_at, revoked_at, user_id, created_at, updated_at FROM invitations
WHERE email = $1 AND accepted_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) GetOpenInvitationByEmail(ctx context.Context, email string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getOpenInvitationByEmail, email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.ClientID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordReset = `-- name: GetPasswordReset :one
SELECT r.id, r.user_id, r.token_hash, r.expires_at, r.used_at, r.created_at, u.email, u.firstname, u.disabled_at AS user_disabled_at, u.deleted_at AS user_deleted_at
FROM password_resets r
JOIN users u ON u.id = r.user_id
WHERE r.token_hash = $1
`

type GetPasswordResetRow struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	TokenHash      []byte     `json:"token_hash"`
	ExpiresAt      time.Time  `json:"expires_at"`
	UsedAt         *time.Time `json:"used_at"`
	CreatedAt      time.Time  `json:"created_at"`
	Email          string     `json:"email"`
	Firstname      string     `json:"firstname"`
	UserDisabledAt *time.Time `json:"user_disabled_at"`
	UserDeletedAt  *time.Time `json:"user_deleted_at"`
}

func (q *Queries) GetPasswordReset(ctx context.Context, tokenHash []byte) (GetPasswordResetRow, error) {
	row := q.db.QueryRow(ctx, getPasswordReset, tokenHash)
	var i GetPasswordResetRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Email,
		&i.Firstname,
		&i.UserDisabledAt,
		&i.UserDeletedAt,
	)
	return i, err
}

const invalidateUserPasswordResets = `-- name: InvalidateUserPasswordResets :exec
UPDATE password_resets SET used_at = now()
WHERE user_id = $1 AND used_at IS NULL
`

// Un mot de passe change rend caducs les autres liens en circulation.
func (q *Queries) InvalidateUserPasswordResets(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateUserPasswordResets, userID)
	return err
}

const listOpenInvitations = `-- name: ListOpenInvitations :many
SELECT
    i.id, i.email, i.firstname, i.lastname, i.role, i.client_id, i.token_hash, i.invited_by, i.expires_at, i.accepted_at, i.revoked_at, i.user_id, i.created_at, i.updated_at,
    coalesce(btrim(u.firstname || ' ' || u.lastname), '')::text AS inviter_name,
    coalesce(c.name, '')::text                                   AS client_name
FROM invitations i
LEFT JOIN users u   ON u.id = i.invited_by
LEFT JOIN clients c ON c.id = i.client_id
WHERE i.accepted_at IS NULL AND i.revoked_at IS NULL
ORDER BY i.created_at DESC
LIMIT 100
`

type ListOpenInvitationsRow struct {
	ID          uuid.UUID  `json:"id"`
	Email       string     `json:"email"`
	Firstname   string     `json:"firstname"`
	Lastname    string     `json:"lastname"`
	Role        string     `json:"role"`
	ClientID    *uuid.UUID `json:"client_id"`
	TokenHash   []byte     `json:"token_hash"`
	InvitedBy   *uuid.UUID `json:"invited_by"`
	ExpiresAt   time.Time  `json:"expires_at"`
	AcceptedAt  *time.Time `json:"accepted_at"`
	RevokedAt   *time.Time `json:"revoked_at"`
	UserID      *uuid.UUID `json:"user_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	InviterName string     `json:"inviter_name"`
	ClientName  string     `json:"client_name"`
}

// Onglet « Invitations » : celles qui attendent une reponse, expirees
// comprises — c'est la qu'on les renvoie. Bornee : une agence n'a pas cent
// invitations en attente, et au-dela le probleme n'est pas l'affichage.
func (q *Queries) ListOpenInvitations(ctx context.Context) ([]ListOpenInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listOpenInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenInvitationsRow{}
	for rows.Next() {
		var i ListOpenInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Firstname,
			&i.Lastname,
			&i.Role,
			&i.ClientID,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InviterName,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewInvitation = `-- name: RenewInvitation :one
UPDATE invitations
SET token_hash = $2, expires_at = $3, updated_at = now()
WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
RETURNING id, email, firstname, lastname, role, client_id, token_hash, invited_by, expires_at, accepted_at, revoked_at, user_id, created_at, updated_at
`

type RenewInvitationParams struct {
	ID        uuid.UUID `json:"id"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Renvoyer une invitation remplace son jeton : l'ancien lien cesse de valoir.
func (q *Queries) RenewInvitation(ctx context.Context, arg RenewInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, renewInvitation, arg.ID, arg.TokenHash, arg.ExpiresAt)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.ClientID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE invitations SET revoked_at = now(), updated_at = now()
WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) RevokeInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeInvitation, id)
	return err
}
