// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	uuid "github.com/google/uuid"
)

type AppBackup struct {
	ID         uuid.UUID  `json:"id"`
	StartedAt  time.Time  `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
	Status     string     `json:"status"`
	Location   string     `json:"location"`
	SizeBytes  int64      `json:"size_bytes"`
	Error      string     `json:"error"`
}

type AppReleaseCheck struct {
	ID               bool       `json:"id"`
	Version          string     `json:"version"`
	Name             string     `json:"name"`
	Url              string     `json:"url"`
	PublishedAt      *time.Time `json:"published_at"`
	CheckedAt        time.Time  `json:"checked_at"`
	Error            string     `json:"error"`
	Etag             string     `json:"etag"`
	CheckRequestedAt *time.Time `json:"check_requested_at"`
	NotifiedVersion  string     `json:"notified_version"`
}

type AppUpdateRequest struct {
	ID            uuid.UUID  `json:"id"`
	RequestedBy   *uuid.UUID `json:"requested_by"`
	FromVersion   string     `json:"from_version"`
	TargetVersion string     `json:"target_version"`
	Status        string     `json:"status"`
	Step          string     `json:"step"`
	Error         string     `json:"error"`
	CreatedAt     time.Time  `json:"created_at"`
	StartedAt     *time.Time `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
}

type AppUpdater struct {
	ID       bool      `json:"id"`
	Version  string    `json:"version"`
	Target   string    `json:"target"`
	Error    string    `json:"error"`
	LastSeen time.Time `json:"last_seen"`
}

type Attachment struct {
	ID               uuid.UUID  `json:"id"`
	ProjectID        *uuid.UUID `json:"project_id"`
	Filename         string     `json:"filename"`
	ContentType      string     `json:"content_type"`
	SizeBytes        int64      `json:"size_bytes"`
	StorageKey       string     `json:"storage_key"`
	UploadedBy       *uuid.UUID `json:"uploaded_by"`
	CreatedAt        time.Time  `json:"created_at"`
	TaskID           *uuid.UUID `json:"task_id"`
	SharedWithClient bool       `json:"shared_with_client"`
	TicketID         *uuid.UUID `json:"ticket_id"`
}

type AuditLog struct {
	ID         uuid.UUID  `json:"id"`
	At         time.Time  `json:"at"`
	ActorID    *uuid.UUID `json:"actor_id"`
	ActorEmail string     `json:"actor_email"`
	Action     string     `json:"action"`
	TargetType string     `json:"target_type"`
	TargetID   string     `json:"target_id"`
	Ip         string     `json:"ip"`
	UserAgent  string     `json:"user_agent"`
	Details    []byte     `json:"details"`
}

type Client struct {
	ID                uuid.UUID  `json:"id"`
	Name              string     `json:"name"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	DeletedAt         *time.Time `json:"deleted_at"`
	ProjectsActive    int32      `json:"projects_active"`
	PortalUsers       int32      `json:"portal_users"`
	PrimaryContactID  *uuid.UUID `json:"primary_contact_id"`
	Status            string     `json:"status"`
	AccountManagerID  *uuid.UUID `json:"account_manager_id"`
	Website           string     `json:"website"`
	Phone             string     `json:"phone"`
	Address           string     `json:"address"`
	PostalCode        string     `json:"postal_code"`
	City              string     `json:"city"`
	Country           string     `json:"country"`
	Siret             string     `json:"siret"`
	VatNumber         string     `json:"vat_number"`
	StatusChangedAt   time.Time  `json:"status_changed_at"`
	Kind              string     `json:"kind"`
	LegalName         string     `json:"legal_name"`
	LegalForm         string     `json:"legal_form"`
	RegistryCheckedAt *time.Time `json:"registry_checked_at"`
}

type ClientInteraction struct {
	ID         uuid.UUID  `json:"id"`
	ClientID   uuid.UUID  `json:"client_id"`
	Kind       string     `json:"kind"`
	Body       string     `json:"body"`
	OccurredAt time.Time  `json:"occurred_at"`
	AuthorID   *uuid.UUID `json:"author_id"`
	ProjectID  *uuid.UUID `json:"project_id"`
	Payload    []byte     `json:"payload"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Contact struct {
	ID        uuid.UUID  `json:"id"`
	ClientID  *uuid.UUID `json:"client_id"`
	Firstname string     `json:"firstname"`
	Lastname  string     `json:"lastname"`
	Role      string     `json:"role"`
	Email     *string    `json:"email"`
	Phone     string     `json:"phone"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type DailyActivity struct {
	Day                   time.Time `json:"day"`
	TasksDone             int32     `json:"tasks_done"`
	TicketsOpened         int32     `json:"tickets_opened"`
	DeliverablesSubmitted int32     `json:"deliverables_submitted"`
}

type Deliverable struct {
	ID               uuid.UUID  `json:"id"`
	ProjectID        uuid.UUID  `json:"project_id"`
	Title            string     `json:"title"`
	Description      string     `json:"description"`
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
	CreatedAt        time.Time  `json:"created_at"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	UpdatedAt        time.Time  `json:"updated_at"`
	DeletedAt        *time.Time `json:"deleted_at"`
	MilestoneID      *uuid.UUID `json:"milestone_id"`
}

type DeliverableVersion struct {
	ID            uuid.UUID  `json:"id"`
	DeliverableID uuid.UUID  `json:"deliverable_id"`
	Numero        int32      `json:"numero"`
	AttachmentID  *uuid.UUID `json:"attachment_id"`
	Url           string     `json:"url"`
	SubmittedAt   time.Time  `json:"submitted_at"`
	SubmittedBy   *uuid.UUID `json:"submitted_by"`
	Decision      string     `json:"decision"`
	DecidedAt     *time.Time `json:"decided_at"`
	DecidedBy     *uuid.UUID `json:"decided_by"`
	Feedback      string     `json:"feedback"`
	RemindedAt    *time.Time `json:"reminded_at"`
}

type Deployment struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Provider    string    `json:"provider"`
	Kind        string    `json:"kind"`
	Name        string    `json:"name"`
	Url         string    `json:"url"`
	Environment string    `json:"environment"`
	DeployedAt  time.Time `json:"deployed_at"`
}

type EmailOutbox struct {
	ID            uuid.UUID  `json:"id"`
	Kind          string     `json:"kind"`
	ToAddress     string     `json:"to_address"`
	Subject       string     `json:"subject"`
	TextBody      string     `json:"text_body"`
	HtmlBody      string     `json:"html_body"`
	Status        string     `json:"status"`
	Attempts      int32      `json:"attempts"`
	NextAttemptAt time.Time  `json:"next_attempt_at"`
	LastError     string     `json:"last_error"`
	CreatedAt     time.Time  `json:"created_at"`
	SentAt        *time.Time `json:"sent_at"`
	ReplyTo       string     `json:"reply_to"`
	MessageID     string     `json:"message_id"`
	InReplyTo     string     `json:"in_reply_to"`
}

type GitWebhook struct {
	ID        bool      `json:"id"`
	Secret    string    `json:"secret"`
	UpdatedAt time.Time `json:"updated_at"`
}

type InboundEmail struct {
	ID              uuid.UUID  `json:"id"`
	ReceivedAt      time.Time  `json:"received_at"`
	Source          string     `json:"source"`
	MessageID       string     `json:"message_id"`
	FromAddress     string     `json:"from_address"`
	FromName        string     `json:"from_name"`
	Subject         string     `json:"subject"`
	Excerpt         string     `json:"excerpt"`
	AttachmentCount int32      `json:"attachment_count"`
	Raw             []byte     `json:"raw"`
	Status          string     `json:"status"`
	Reason          string     `json:"reason"`
	ClientID        *uuid.UUID `json:"client_id"`
	TicketID        *uuid.UUID `json:"ticket_id"`
	Attempts        int32      `json:"attempts"`
	Error           string     `json:"error"`
	ProcessedAt     *time.Time `json:"processed_at"`
}

type InboundMailSetting struct {
	ID              int32      `json:"id"`
	Address         string     `json:"address"`
	ImapEnabled     bool       `json:"imap_enabled"`
	ImapHost        string     `json:"imap_host"`
	ImapPort        int32      `json:"imap_port"`
	ImapSecurity    string     `json:"imap_security"`
	ImapUsername    string     `json:"imap_username"`
	ImapPasswordEnc []byte     `json:"imap_password_enc"`
	ImapFolder      string     `json:"imap_folder"`
	WebhookSecret   string     `json:"webhook_secret"`
	LastPollAt      *time.Time `json:"last_poll_at"`
	LastPollError   string     `json:"last_poll_error"`
	PollRequestedAt *time.Time `json:"poll_requested_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type Invitation struct {
	ID         uuid.UUID  `json:"id"`
	Email      string     `json:"email"`
	Firstname  string     `json:"firstname"`
	Lastname   string     `json:"lastname"`
	Role       string     `json:"role"`
	ClientID   *uuid.UUID `json:"client_id"`
	TokenHash  []byte     `json:"token_hash"`
	InvitedBy  *uuid.UUID `json:"invited_by"`
	ExpiresAt  time.Time  `json:"expires_at"`
	AcceptedAt *time.Time `json:"accepted_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	UserID     *uuid.UUID `json:"user_id"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type Milestone struct {
	ID                      uuid.UUID  `json:"id"`
	ProjectID               uuid.UUID  `json:"project_id"`
	Title                   string     `json:"title"`
	Description             string     `json:"description"`
	DueOn                   *time.Time `json:"due_on"`
	Position                int32      `json:"position"`
	CompletedAt             *time.Time `json:"completed_at"`
	DeliverablesTotal       int32      `json:"deliverables_total"`
	DeliverablesValidated   int32      `json:"deliverables_validated"`
	CreatedBy               *uuid.UUID `json:"created_by"`
	CreatedAt               time.Time  `json:"created_at"`
	UpdatedAt               time.Time  `json:"updated_at"`
	CompletedByDeliverables bool       `json:"completed_by_deliverables"`
}

type Notification struct {
	ID            uuid.UUID  `json:"id"`
	UserID        uuid.UUID  `json:"user_id"`
	ActorID       *uuid.UUID `json:"actor_id"`
	Kind          string     `json:"kind"`
	Payload       []byte     `json:"payload"`
	TaskID        *uuid.UUID `json:"task_id"`
	ProjectID     *uuid.UUID `json:"project_id"`
	ReadAt        *time.Time `json:"read_at"`
	CreatedAt     time.Time  `json:"created_at"`
	TicketID      *uuid.UUID `json:"ticket_id"`
	DeliverableID *uuid.UUID `json:"deliverable_id"`
}

type PasswordReset struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash []byte     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type Permission struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

type Project struct {
	ID                  uuid.UUID  `json:"id"`
	ClientID            uuid.UUID  `json:"client_id"`
	Name                string     `json:"name"`
	Status              string     `json:"status"`
	Progress            int16      `json:"progress"`
	HoursSold           float64    `json:"hours_sold"`
	HoursSpent          float64    `json:"hours_spent"`
	StartsOn            *time.Time `json:"starts_on"`
	DueOn               *time.Time `json:"due_on"`
	TasksTotal          int32      `json:"tasks_total"`
	TasksDone           int32      `json:"tasks_done"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	DeletedAt           *time.Time `json:"deleted_at"`
	Description         string     `json:"description"`
	Priority            string     `json:"priority"`
	FigmaUrl            string     `json:"figma_url"`
	ProdUrl             string     `json:"prod_url"`
	PreprodUrl          string     `json:"preprod_url"`
	DeliverablesPending int32      `json:"deliverables_pending"`
	IsInternal          bool       `json:"is_internal"`
	LogoKey             *string    `json:"logo_key"`
	RepoUrl             string     `json:"repo_url"`
}

type ProjectFavorite struct {
	UserID    uuid.UUID `json:"user_id"`
	ProjectID uuid.UUID `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ProjectMember struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ProjectService struct {
	ProjectID uuid.UUID `json:"project_id"`
	ServiceID uuid.UUID `json:"service_id"`
}

type ProjectTemplate struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type ProjectTemplateMilestone struct {
	ID         uuid.UUID `json:"id"`
	TemplateID uuid.UUID `json:"template_id"`
	Title      string    `json:"title"`
	OffsetDays int32     `json:"offset_days"`
	Position   int32     `json:"position"`
}

type ProjectTemplateService struct {
	TemplateID uuid.UUID `json:"template_id"`
	ServiceID  uuid.UUID `json:"service_id"`
}

type ProjectTemplateTask struct {
	ID          uuid.UUID `json:"id"`
	TemplateID  uuid.UUID `json:"template_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Priority    string    `json:"priority"`
	OffsetDays  *int32    `json:"offset_days"`
	Position    int32     `json:"position"`
}

type PullRequest struct {
	ID        uuid.UUID  `json:"id"`
	ProjectID uuid.UUID  `json:"project_id"`
	Provider  string     `json:"provider"`
	Number    int64      `json:"number"`
	Title     string     `json:"title"`
	Url       string     `json:"url"`
	Branch    string     `json:"branch"`
	Author    string     `json:"author"`
	State     string     `json:"state"`
	OpenedAt  *time.Time `json:"opened_at"`
	MergedAt  *time.Time `json:"merged_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type PullRequestLink struct {
	PullRequestID uuid.UUID  `json:"pull_request_id"`
	TicketID      *uuid.UUID `json:"ticket_id"`
	TaskID        *uuid.UUID `json:"task_id"`
}

type RefreshToken struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash []byte      `json:"token_hash"`
	UserAgent string      `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
	ExpiresAt time.Time   `json:"expires_at"`
	RevokedAt *time.Time  `json:"revoked_at"`
	CreatedAt time.Time   `json:"created_at"`
}

type Role struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Label     string    `json:"label"`
	IsSystem  bool      `json:"is_system"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type Service struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Color       string     `json:"color"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}

type SidebarApp struct {
	ID                 uuid.UUID  `json:"id"`
	Name               string     `json:"name"`
	Url                string     `json:"url"`
	LogoKey            *string    `json:"logo_key"`
	Color              string     `json:"color"`
	Position           int32      `json:"position"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
	DeletedAt          *time.Time `json:"deleted_at"`
	LogoIsFavicon      bool       `json:"logo_is_favicon"`
	FaviconAttemptedAt *time.Time `json:"favicon_attempted_at"`
}

type Subtask struct {
	ID        uuid.UUID `json:"id"`
	TaskID    uuid.UUID `json:"task_id"`
	Label     string    `json:"label"`
	Done      bool      `json:"done"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Task struct {
	ID               uuid.UUID  `json:"id"`
	ProjectID        uuid.UUID  `json:"project_id"`
	Title            string     `json:"title"`
	Description      string     `json:"description"`
	Status           string     `json:"status"`
	Tag              string     `json:"tag"`
	StartsOn         *time.Time `json:"starts_on"`
	DueOn            *time.Time `json:"due_on"`
	Hours            *float64   `json:"hours"`
	Note             string     `json:"note"`
	Position         int32      `json:"position"`
	CompletedAt      *time.Time `json:"completed_at"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	DeletedAt        *time.Time `json:"deleted_at"`
	Priority         string     `json:"priority"`
	SubtasksTotal    int32      `json:"subtasks_total"`
	SubtasksDone     int32      `json:"subtasks_done"`
	CommentsCount    int32      `json:"comments_count"`
	AttachmentsCount int32      `json:"attachments_count"`
	Numero           int64      `json:"numero"`
}

type TaskActivity struct {
	ID        uuid.UUID  `json:"id"`
	TaskID    uuid.UUID  `json:"task_id"`
	ActorID   *uuid.UUID `json:"actor_id"`
	Kind      string     `json:"kind"`
	Payload   []byte     `json:"payload"`
	CreatedAt time.Time  `json:"created_at"`
}

type TaskAssignee struct {
	TaskID    uuid.UUID `json:"task_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type TaskComment struct {
	ID        uuid.UUID  `json:"id"`
	TaskID    uuid.UUID  `json:"task_id"`
	AuthorID  *uuid.UUID `json:"author_id"`
	Body      string     `json:"body"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type TaskService struct {
	TaskID    uuid.UUID `json:"task_id"`
	ServiceID uuid.UUID `json:"service_id"`
}

type Ticket struct {
	ID             uuid.UUID  `json:"id"`
	Numero         int64      `json:"numero"`
	ProjectID      uuid.UUID  `json:"project_id"`
	Subject        string     `json:"subject"`
	Description    string     `json:"description"`
	Tracker        string     `json:"tracker"`
	Status         string     `json:"status"`
	Priority       string     `json:"priority"`
	AssigneeID     *uuid.UUID `json:"assignee_id"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
	ClientVisible  bool       `json:"client_visible"`
	RequesterEmail *string    `json:"requester_email"`
	RequesterName  string     `json:"requester_name"`
}

type TicketEvent struct {
	ID        uuid.UUID  `json:"id"`
	TicketID  uuid.UUID  `json:"ticket_id"`
	ActorID   *uuid.UUID `json:"actor_id"`
	Field     string     `json:"field"`
	OldValue  string     `json:"old_value"`
	NewValue  string     `json:"new_value"`
	CreatedAt time.Time  `json:"created_at"`
}

type TicketMessage struct {
	ID          uuid.UUID  `json:"id"`
	TicketID    uuid.UUID  `json:"ticket_id"`
	AuthorID    *uuid.UUID `json:"author_id"`
	Body        string     `json:"body"`
	IsInternal  bool       `json:"is_internal"`
	CreatedAt   time.Time  `json:"created_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	ViaEmail    bool       `json:"via_email"`
	SenderName  string     `json:"sender_name"`
	SenderEmail string     `json:"sender_email"`
}

type TicketReplyTemplate struct {
	ID        uuid.UUID  `json:"id"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	CreatedBy *uuid.UUID `json:"created_by"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type TimeEntry struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	ProjectID uuid.UUID  `json:"project_id"`
	TaskID    *uuid.UUID `json:"task_id"`
	ServiceID *uuid.UUID `json:"service_id"`
	SpentOn   time.Time  `json:"spent_on"`
	Minutes   int32      `json:"minutes"`
	Note      string     `json:"note"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type TimeTimer struct {
	UserID    uuid.UUID  `json:"user_id"`
	ProjectID uuid.UUID  `json:"project_id"`
	TaskID    *uuid.UUID `json:"task_id"`
	Note      string     `json:"note"`
	StartedAt time.Time  `json:"started_at"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	Firstname    string     `json:"firstname"`
	Lastname     string     `json:"lastname"`
	Role         string     `json:"role"`
	AvatarUrl    *string    `json:"avatar_url"`
	TotpSecret   *string    `json:"totp_secret"`
	LastLoginAt  *time.Time `json:"last_login_at"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	Gender       string     `json:"gender"`
	Phone        string     `json:"phone"`
	Address      string     `json:"address"`
	PostalCode   string     `json:"postal_code"`
	City         string     `json:"city"`
	Country      string     `json:"country"`
	ClientID     *uuid.UUID `json:"client_id"`
	DisabledAt   *time.Time `json:"disabled_at"`
	BookingUrl   string     `json:"booking_url"`
}
