// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: my_work.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const listMyDeliverablesToSubmit = `-- name: ListMyDeliverablesToSubmit :many
SELECT
    d.id,
    d.title,
    p.id   AS project_id,
    p.name AS project_name,
    v.numero     AS version,
    v.decided_at AS decided_at,
    coalesce(v.feedback, '')::text AS feedback,
    count(*) OVER () AS total
FROM project_members pm
JOIN projects p     ON p.id = pm.project_id AND p.deleted_at IS NULL AND p.status <> 'livre'
JOIN deliverables d ON d.project_id = p.id AND d.deleted_at IS NULL
LEFT JOIN deliverable_versions v ON v.id = d.current_version_id
WHERE pm.user_id = $1
  AND (d.current_version_id IS NULL OR v.decision = 'retours')
ORDER BY (v.decision = 'retours') DESC NULLS LAST, v.decided_at DESC NULLS LAST, d.created_at DESC, d.id
LIMIT $2
`

type ListMyDeliverablesToSubmitParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PageSize int32     `json:"page_size"`
}

type ListMyDeliverablesToSubmitRow struct {
	ID          uuid.UUID  `json:"id"`
	Title       string     `json:"title"`
	ProjectID   uuid.UUID  `json:"project_id"`
	ProjectName string     `json:"project_name"`
	Version     *int32     `json:"version"`
	DecidedAt   *time.Time `json:"decided_at"`
	Feedback    string     `json:"feedback"`
	Total       int64      `json:"total"`
}

// Les livrables a deposer dans les projets d'une personne : ceux qui n'ont
// encore aucune version, et ceux dont le client a renvoye des retours. Ce qui
// attend la decision du client n'y figure pas — la balle n'est pas dans le
// camp de l'equipe.
func (q *Queries) ListMyDeliverablesToSubmit(ctx context.Context, arg ListMyDeliverablesToSubmitParams) ([]ListMyDeliverablesToSubmitRow, error) {
	rows, err := q.db.Query(ctx, listMyDeliverablesToSubmit, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyDeliverablesToSubmitRow{}
	for rows.Next() {
		var i ListMyDeliverablesToSubmitRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProjectID,
			&i.ProjectName,
			&i.Version,
			&i.DecidedAt,
			&i.Feedback,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyOpenTasks = `-- name: ListMyOpenTasks :many

SELECT
    t.id,
    t.title,
    t.status,
    t.priority,
    t.due_on,
    p.id   AS project_id,
    p.name AS project_name,
    count(*) OVER () AS total,
    count(*) FILTER (WHERE t.due_on < $1::date) OVER () AS overdue
FROM task_assignees ta
JOIN tasks t    ON t.id = ta.task_id AND t.deleted_at IS NULL
JOIN projects p ON p.id = t.project_id AND p.deleted_at IS NULL
WHERE ta.user_id = $2
  AND t.status <> 'done'
ORDER BY t.due_on ASC NULLS LAST, t.updated_at DESC, t.id
LIMIT $3
`

type ListMyOpenTasksParams struct {
	Today    time.Time `json:"today"`
	UserID   uuid.UUID `json:"user_id"`
	PageSize int32     `json:"page_size"`
}

type ListMyOpenTasksRow struct {
	ID          uuid.UUID  `json:"id"`
	Title       string     `json:"title"`
	Status      string     `json:"status"`
	Priority    string     `json:"priority"`
	DueOn       *time.Time `json:"due_on"`
	ProjectID   uuid.UUID  `json:"project_id"`
	ProjectName string     `json:"project_name"`
	Total       int64      `json:"total"`
	Overdue     int64      `json:"overdue"`
}

// Page « Mon travail » : ce qui attend une personne, dans tous ses projets.
//
// Cinq requetes bornees plutot qu'une seule : chaque bloc a son ordre et sa
// limite, et les reunir demanderait des UNION aux colonnes forcees qui ne se
// liraient plus.
// Les taches non terminees d'une personne, les plus pressantes d'abord : en
// retard, puis par echeance, puis sans echeance.
//
// Les deux comptes portent sur toutes les lignes, pas sur la page : l'ecran
// annonce « 12 en retard » meme quand il n'en montre que les premieres.
func (q *Queries) ListMyOpenTasks(ctx context.Context, arg ListMyOpenTasksParams) ([]ListMyOpenTasksRow, error) {
	rows, err := q.db.Query(ctx, listMyOpenTasks, arg.Today, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyOpenTasksRow{}
	for rows.Next() {
		var i ListMyOpenTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.DueOn,
			&i.ProjectID,
			&i.ProjectName,
			&i.Total,
			&i.Overdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyOpenTickets = `-- name: ListMyOpenTickets :many
SELECT
    t.id,
    t.numero,
    t.subject,
    t.status,
    t.priority,
    t.updated_at,
    p.id   AS project_id,
    p.name AS project_name,
    count(*) OVER () AS total
FROM tickets t
JOIN projects p ON p.id = t.project_id AND p.deleted_at IS NULL
WHERE t.assignee_id = $1
  AND t.deleted_at IS NULL
  AND t.status NOT IN ('done', 'annule')
ORDER BY
    array_position(ARRAY['critical', 'urgent', 'high', 'normal', 'low'], t.priority),
    t.updated_at DESC,
    t.id
LIMIT $2
`

type ListMyOpenTicketsParams struct {
	UserID   *uuid.UUID `json:"user_id"`
	PageSize int32      `json:"page_size"`
}

type ListMyOpenTicketsRow struct {
	ID          uuid.UUID `json:"id"`
	Numero      int64     `json:"numero"`
	Subject     string    `json:"subject"`
	Status      string    `json:"status"`
	Priority    string    `json:"priority"`
	UpdatedAt   time.Time `json:"updated_at"`
	ProjectID   uuid.UUID `json:"project_id"`
	ProjectName string    `json:"project_name"`
	Total       int64     `json:"total"`
}

// Les tickets ouverts confies a une personne, les plus urgents d'abord.
func (q *Queries) ListMyOpenTickets(ctx context.Context, arg ListMyOpenTicketsParams) ([]ListMyOpenTicketsRow, error) {
	rows, err := q.db.Query(ctx, listMyOpenTickets, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyOpenTicketsRow{}
	for rows.Next() {
		var i ListMyOpenTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Subject,
			&i.Status,
			&i.Priority,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.ProjectName,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyProjects = `-- name: ListMyProjects :many
SELECT
    p.id,
    p.name,
    p.status,
    p.progress,
    p.due_on,
    p.tasks_total,
    p.tasks_done,
    c.name AS client_name
FROM project_members pm
JOIN projects p ON p.id = pm.project_id AND p.deleted_at IS NULL AND p.status <> 'livre'
JOIN clients c  ON c.id = p.client_id
WHERE pm.user_id = $1
ORDER BY p.due_on ASC NULLS LAST, p.name
LIMIT $2
`

type ListMyProjectsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PageSize int32     `json:"page_size"`
}

type ListMyProjectsRow struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Status     string     `json:"status"`
	Progress   int16      `json:"progress"`
	DueOn      *time.Time `json:"due_on"`
	TasksTotal int32      `json:"tasks_total"`
	TasksDone  int32      `json:"tasks_done"`
	ClientName string     `json:"client_name"`
}

// Les projets en cours ou une personne intervient, les plus proches de leur
// echeance d'abord. Les compteurs de taches sont ceux tenus par les
// declencheurs : aucun comptage ici.
func (q *Queries) ListMyProjects(ctx context.Context, arg ListMyProjectsParams) ([]ListMyProjectsRow, error) {
	rows, err := q.db.Query(ctx, listMyProjects, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyProjectsRow{}
	for rows.Next() {
		var i ListMyProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Progress,
			&i.DueOn,
			&i.TasksTotal,
			&i.TasksDone,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMyWeekMinutes = `-- name: SumMyWeekMinutes :one
SELECT coalesce(sum(minutes), 0)::bigint
FROM time_entries
WHERE user_id = $1
  AND deleted_at IS NULL
  AND spent_on >= $2::date
  AND spent_on <  $2::date + 7
`

type SumMyWeekMinutesParams struct {
	UserID    uuid.UUID `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
}

// Le temps saisi par une personne sur une semaine. Au plus quelques dizaines
// de lignes, lues par l'index (user_id, spent_on).
func (q *Queries) SumMyWeekMinutes(ctx context.Context, arg SumMyWeekMinutesParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumMyWeekMinutes, arg.UserID, arg.WeekStart)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
