// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portal.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const listPortalRecipientsOfProject = `-- name: ListPortalRecipientsOfProject :many
SELECT u.id, u.email, u.firstname
FROM projects p
JOIN users u ON u.client_id = p.client_id
WHERE p.id = $1
  AND NOT p.is_internal
  AND u.role = 'client'
  AND u.deleted_at IS NULL
  AND u.disabled_at IS NULL
LIMIT 50
`

type ListPortalRecipientsOfProjectRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Firstname string    `json:"firstname"`
}

// Les comptes du portail a prevenir pour un projet : ceux de son client,
// actifs. Les projets internes n'ont pas de client a prevenir.
func (q *Queries) ListPortalRecipientsOfProject(ctx context.Context, projectID uuid.UUID) ([]ListPortalRecipientsOfProjectRow, error) {
	rows, err := q.db.Query(ctx, listPortalRecipientsOfProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPortalRecipientsOfProjectRow{}
	for rows.Next() {
		var i ListPortalRecipientsOfProjectRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Firstname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalGetDeliverable = `-- name: PortalGetDeliverable :one
SELECT
    d.id,
    d.title,
    d.description,
    d.current_version_id,
    p.id   AS project_id,
    p.name AS project_name,
    ms.title AS milestone_title
FROM users u
JOIN projects p     ON p.client_id = u.client_id AND p.deleted_at IS NULL AND NOT p.is_internal
JOIN deliverables d ON d.project_id = p.id AND d.deleted_at IS NULL AND d.current_version_id IS NOT NULL
LEFT JOIN milestones ms ON ms.id = d.milestone_id
WHERE u.id = $1
  AND d.id = $2
  AND u.role = 'client'
  AND u.deleted_at IS NULL
  AND u.disabled_at IS NULL
`

type PortalGetDeliverableParams struct {
	UserID        uuid.UUID `json:"user_id"`
	DeliverableID uuid.UUID `json:"deliverable_id"`
}

type PortalGetDeliverableRow struct {
	ID               uuid.UUID  `json:"id"`
	Title            string     `json:"title"`
	Description      string     `json:"description"`
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
	ProjectID        uuid.UUID  `json:"project_id"`
	ProjectName      string     `json:"project_name"`
	MilestoneTitle   *string    `json:"milestone_title"`
}

// Un livrable soumis d'un projet du client de l'appelant.
func (q *Queries) PortalGetDeliverable(ctx context.Context, arg PortalGetDeliverableParams) (PortalGetDeliverableRow, error) {
	row := q.db.QueryRow(ctx, portalGetDeliverable, arg.UserID, arg.DeliverableID)
	var i PortalGetDeliverableRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CurrentVersionID,
		&i.ProjectID,
		&i.ProjectName,
		&i.MilestoneTitle,
	)
	return i, err
}

const portalGetFile = `-- name: PortalGetFile :one
SELECT a.id, a.project_id, a.filename, a.content_type, a.size_bytes, a.storage_key, a.uploaded_by, a.created_at, a.task_id, a.shared_with_client, a.ticket_id
FROM users u
JOIN projects p ON p.client_id = u.client_id AND p.deleted_at IS NULL AND NOT p.is_internal
JOIN attachments a ON a.id = $1
WHERE u.id = $2
  AND u.role = 'client'
  AND u.deleted_at IS NULL
  AND u.disabled_at IS NULL
  AND (
      (a.project_id = p.id AND a.shared_with_client)
      OR EXISTS (
          SELECT 1
          FROM deliverable_versions v
          JOIN deliverables d ON d.id = v.deliverable_id AND d.deleted_at IS NULL
          WHERE v.attachment_id = a.id AND d.project_id = p.id
      )
      OR EXISTS (
          SELECT 1
          FROM tickets t
          WHERE t.id = a.ticket_id AND t.project_id = p.id AND t.client_visible AND t.deleted_at IS NULL
      )
  )
LIMIT 1
`

type PortalGetFileParams struct {
	FileID uuid.UUID `json:"file_id"`
	UserID uuid.UUID `json:"user_id"`
}

// Un fichier que l'appelant peut telecharger : partage sur un de ses projets,
// porte par une version d'un de ses livrables, ou joint a un de ses tickets.
func (q *Queries) PortalGetFile(ctx context.Context, arg PortalGetFileParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, portalGetFile, arg.FileID, arg.UserID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.TaskID,
		&i.SharedWithClient,
		&i.TicketID,
	)
	return i, err
}

const portalGetProject = `-- name: PortalGetProject :one
SELECT
    p.id,
    p.name,
    p.description,
    p.status,
    p.progress,
    p.starts_on,
    p.due_on,
    p.tasks_total,
    p.tasks_done,
    p.deliverables_pending,
    p.logo_key,
    c.name AS client_name
FROM users u
JOIN projects p ON p.client_id = u.client_id AND p.deleted_at IS NULL AND NOT p.is_internal
JOIN clients c  ON c.id = p.client_id
WHERE u.id = $1
  AND p.id = $2
  AND u.role = 'client'
  AND u.deleted_at IS NULL
  AND u.disabled_at IS NULL
`

type PortalGetProjectParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type PortalGetProjectRow struct {
	ID                  uuid.UUID  `json:"id"`
	Name                string     `json:"name"`
	Description         string     `json:"description"`
	Status              string     `json:"status"`
	Progress            int16      `json:"progress"`
	StartsOn            *time.Time `json:"starts_on"`
	DueOn               *time.Time `json:"due_on"`
	TasksTotal          int32      `json:"tasks_total"`
	TasksDone           int32      `json:"tasks_done"`
	DeliverablesPending int32      `json:"deliverables_pending"`
	LogoKey             *string    `json:"logo_key"`
	ClientName          string     `json:"client_name"`
}

// Un projet du client de l'appelant. Aucune ligne s'il appartient a un autre.
func (q *Queries) PortalGetProject(ctx context.Context, arg PortalGetProjectParams) (PortalGetProjectRow, error) {
	row := q.db.QueryRow(ctx, portalGetProject, arg.UserID, arg.ProjectID)
	var i PortalGetProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Progress,
		&i.StartsOn,
		&i.DueOn,
		&i.TasksTotal,
		&i.TasksDone,
		&i.DeliverablesPending,
		&i.LogoKey,
		&i.ClientName,
	)
	return i, err
}

const portalListDeliverables = `-- name: PortalListDeliverables :many
SELECT
    d.id,
    d.title,
    d.description,
    v.decision AS status,
    v.numero   AS version_numero,
    v.url      AS version_url,
    v.attachment_id,
    v.submitted_at,
    v.decided_at,
    v.feedback,
    ms.title AS milestone_title
FROM deliverables d
JOIN deliverable_versions v ON v.id = d.current_version_id
LEFT JOIN milestones ms ON ms.id = d.milestone_id
WHERE d.project_id = $1
  AND d.deleted_at IS NULL
ORDER BY (v.decision = 'en_attente') DESC, v.submitted_at DESC, d.id
LIMIT 200
`

type PortalListDeliverablesRow struct {
	ID             uuid.UUID  `json:"id"`
	Title          string     `json:"title"`
	Description    string     `json:"description"`
	Status         string     `json:"status"`
	VersionNumero  int32      `json:"version_numero"`
	VersionUrl     string     `json:"version_url"`
	AttachmentID   *uuid.UUID `json:"attachment_id"`
	SubmittedAt    time.Time  `json:"submitted_at"`
	DecidedAt      *time.Time `json:"decided_at"`
	Feedback       string     `json:"feedback"`
	MilestoneTitle *string    `json:"milestone_title"`
}

// Les livrables soumis d'un projet. Un brouillon — rien encore de depose —
// ne regarde pas le client.
func (q *Queries) PortalListDeliverables(ctx context.Context, projectID uuid.UUID) ([]PortalListDeliverablesRow, error) {
	rows, err := q.db.Query(ctx, portalListDeliverables, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortalListDeliverablesRow{}
	for rows.Next() {
		var i PortalListDeliverablesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.VersionNumero,
			&i.VersionUrl,
			&i.AttachmentID,
			&i.SubmittedAt,
			&i.DecidedAt,
			&i.Feedback,
			&i.MilestoneTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalListProjectTeam = `-- name: PortalListProjectTeam :many
SELECT
    u.id,
    u.firstname,
    u.lastname,
    u.email,
    u.phone,
    u.booking_url,
    u.avatar_url,
    (u.id = c.account_manager_id)::boolean AS is_account_manager
FROM projects p
JOIN clients c ON c.id = p.client_id
JOIN users u
  ON u.id = c.account_manager_id
  OR u.id IN (SELECT pm.user_id FROM project_members pm WHERE pm.project_id = p.id)
WHERE p.id = $1
  AND u.role <> 'client'
  AND u.deleted_at IS NULL
  AND u.disabled_at IS NULL
ORDER BY (u.id = c.account_manager_id) DESC, u.firstname, u.lastname, u.id
LIMIT 20
`

type PortalListProjectTeamRow struct {
	ID               uuid.UUID `json:"id"`
	Firstname        string    `json:"firstname"`
	Lastname         string    `json:"lastname"`
	Email            string    `json:"email"`
	Phone            string    `json:"phone"`
	BookingUrl       string    `json:"booking_url"`
	AvatarUrl        *string   `json:"avatar_url"`
	IsAccountManager bool      `json:"is_account_manager"`
}

// Les interlocuteurs d'un projet : le charge de compte du client, puis les
// membres de l'equipe du projet. Jamais un compte du portail, jamais un
// compte ferme. Le telephone et le lien de rendez-vous sont ceux que chacun
// a renseignes dans Mon compte.
func (q *Queries) PortalListProjectTeam(ctx context.Context, projectID uuid.UUID) ([]PortalListProjectTeamRow, error) {
	rows, err := q.db.Query(ctx, portalListProjectTeam, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortalListProjectTeamRow{}
	for rows.Next() {
		var i PortalListProjectTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.Phone,
			&i.BookingUrl,
			&i.AvatarUrl,
			&i.IsAccountManager,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalListProjects = `-- name: PortalListProjects :many

SELECT
    p.id,
    p.name,
    p.description,
    p.status,
    p.progress,
    p.starts_on,
    p.due_on,
    p.tasks_total,
    p.tasks_done,
    p.deliverables_pending,
    p.logo_key,
    -- La jointure LATERAL rend des nuls quand il n'y a plus de jalon a venir :
    -- le titre devient vide plutot que nul, l'echeance reste nullable.
    coalesce(nm.title, '')::text AS next_milestone_title,
    nm.due_on AS next_milestone_due_on,
    greatest(p.updated_at, la.at)::timestamptz AS last_activity_at
FROM users u
JOIN projects p ON p.client_id = u.client_id AND p.deleted_at IS NULL AND NOT p.is_internal
LEFT JOIN LATERAL (
    SELECT m.title, m.due_on
    FROM milestones m
    WHERE m.project_id = p.id AND m.completed_at IS NULL
    ORDER BY m.due_on NULLS LAST, m.position
    LIMIT 1
) nm ON true
LEFT JOIN LATERAL (
    SELECT max(v.submitted_at) AS at
    FROM deliverables d
    JOIN deliverable_versions v ON v.id = d.current_version_id
    WHERE d.project_id = p.id AND d.deleted_at IS NULL
) la ON true
WHERE u.id = $1
  AND u.role = 'client'
  AND u.deleted_at IS NULL
  AND u.disabled_at IS NULL
ORDER BY (p.status = 'livre'), last_activity_at DESC, p.id
LIMIT 100
`

type PortalListProjectsRow struct {
	ID                  uuid.UUID  `json:"id"`
	Name                string     `json:"name"`
	Description         string     `json:"description"`
	Status              string     `json:"status"`
	Progress            int16      `json:"progress"`
	StartsOn            *time.Time `json:"starts_on"`
	DueOn               *time.Time `json:"due_on"`
	TasksTotal          int32      `json:"tasks_total"`
	TasksDone           int32      `json:"tasks_done"`
	DeliverablesPending int32      `json:"deliverables_pending"`
	LogoKey             *string    `json:"logo_key"`
	NextMilestoneTitle  string     `json:"next_milestone_title"`
	NextMilestoneDueOn  *time.Time `json:"next_milestone_due_on"`
	LastActivityAt      time.Time  `json:"last_activity_at"`
}

// Portail client.
//
// Chaque requete part de l'appelant : son compte, son role client, son client.
// L'isolation tient dans le SQL et non dans le code qui l'appelle — un
// identifiant de projet ou de livrable venu d'un autre client ne rend aucune
// ligne, exactement comme un identifiant qui n'existe pas.
//
// Les projets internes et les projets supprimes n'existent pas pour le portail.
// Les projets du client de l'appelant, les plus recemment actifs d'abord, avec
// leur prochain jalon et leur derniere activite. Les compteurs viennent des
// declencheurs ; les deux LATERAL sont bornes a une ligne par projet.
func (q *Queries) PortalListProjects(ctx context.Context, userID uuid.UUID) ([]PortalListProjectsRow, error) {
	rows, err := q.db.Query(ctx, portalListProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortalListProjectsRow{}
	for rows.Next() {
		var i PortalListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Progress,
			&i.StartsOn,
			&i.DueOn,
			&i.TasksTotal,
			&i.TasksDone,
			&i.DeliverablesPending,
			&i.LogoKey,
			&i.NextMilestoneTitle,
			&i.NextMilestoneDueOn,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalListSharedFiles = `-- name: PortalListSharedFiles :many
SELECT id, filename, content_type, size_bytes, created_at
FROM attachments
WHERE project_id = $1 AND shared_with_client
ORDER BY created_at DESC
LIMIT 100
`

type PortalListSharedFilesRow struct {
	ID          uuid.UUID `json:"id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	CreatedAt   time.Time `json:"created_at"`
}

// Les fichiers que l'agence a choisi de partager. Interne par defaut.
func (q *Queries) PortalListSharedFiles(ctx context.Context, projectID *uuid.UUID) ([]PortalListSharedFilesRow, error) {
	rows, err := q.db.Query(ctx, portalListSharedFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortalListSharedFilesRow{}
	for rows.Next() {
		var i PortalListSharedFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
