// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_templates.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const addTemplateMilestone = `-- name: AddTemplateMilestone :exec
INSERT INTO project_template_milestones (template_id, title, offset_days, position)
VALUES ($1, $2, $3, $4)
`

type AddTemplateMilestoneParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	Title      string    `json:"title"`
	OffsetDays int32     `json:"offset_days"`
	Position   int32     `json:"position"`
}

func (q *Queries) AddTemplateMilestone(ctx context.Context, arg AddTemplateMilestoneParams) error {
	_, err := q.db.Exec(ctx, addTemplateMilestone,
		arg.TemplateID,
		arg.Title,
		arg.OffsetDays,
		arg.Position,
	)
	return err
}

const addTemplateService = `-- name: AddTemplateService :exec
INSERT INTO project_template_services (template_id, service_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTemplateServiceParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	ServiceID  uuid.UUID `json:"service_id"`
}

func (q *Queries) AddTemplateService(ctx context.Context, arg AddTemplateServiceParams) error {
	_, err := q.db.Exec(ctx, addTemplateService, arg.TemplateID, arg.ServiceID)
	return err
}

const addTemplateTask = `-- name: AddTemplateTask :exec
INSERT INTO project_template_tasks (template_id, title, description, priority, offset_days, position)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AddTemplateTaskParams struct {
	TemplateID  uuid.UUID `json:"template_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Priority    string    `json:"priority"`
	OffsetDays  *int32    `json:"offset_days"`
	Position    int32     `json:"position"`
}

func (q *Queries) AddTemplateTask(ctx context.Context, arg AddTemplateTaskParams) error {
	_, err := q.db.Exec(ctx, addTemplateTask,
		arg.TemplateID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.OffsetDays,
		arg.Position,
	)
	return err
}

const clearTemplateContent = `-- name: ClearTemplateContent :exec
WITH m AS (DELETE FROM project_template_milestones WHERE project_template_milestones.template_id = $1),
     s AS (DELETE FROM project_template_services WHERE project_template_services.template_id = $1)
DELETE FROM project_template_tasks WHERE project_template_tasks.template_id = $1
`

// Le contenu d'un modele s'enregistre d'un bloc : on efface puis on reecrit,
// dans la meme transaction. Un modele n'a pas d'historique a garder.
func (q *Queries) ClearTemplateContent(ctx context.Context, templateID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearTemplateContent, templateID)
	return err
}

const countProjectTemplates = `-- name: CountProjectTemplates :one
SELECT count(*) FROM project_templates
`

func (q *Queries) CountProjectTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProjectTemplate = `-- name: CreateProjectTemplate :one
INSERT INTO project_templates (name, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_by, created_at, updated_at
`

type CreateProjectTemplateParams struct {
	Name        string     `json:"name"`
	Description string     `json:"description"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProjectTemplate(ctx context.Context, arg CreateProjectTemplateParams) (ProjectTemplate, error) {
	row := q.db.QueryRow(ctx, createProjectTemplate, arg.Name, arg.Description, arg.CreatedBy)
	var i ProjectTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectTemplate = `-- name: DeleteProjectTemplate :execrows
DELETE FROM project_templates WHERE id = $1
`

func (q *Queries) DeleteProjectTemplate(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectTemplate = `-- name: GetProjectTemplate :one
SELECT id, name, description, created_by, created_at, updated_at FROM project_templates WHERE id = $1
`

func (q *Queries) GetProjectTemplate(ctx context.Context, id uuid.UUID) (ProjectTemplate, error) {
	row := q.db.QueryRow(ctx, getProjectTemplate, id)
	var i ProjectTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectTemplates = `-- name: ListProjectTemplates :many

SELECT
    t.id,
    t.name,
    t.description,
    t.updated_at,
    (SELECT count(*) FROM project_template_milestones m WHERE m.template_id = t.id) AS milestones,
    (SELECT count(*) FROM project_template_tasks k WHERE k.template_id = t.id) AS tasks
FROM project_templates t
ORDER BY lower(t.name)
LIMIT $2 OFFSET $1
`

type ListProjectTemplatesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

type ListProjectTemplatesRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	UpdatedAt   time.Time `json:"updated_at"`
	Milestones  int64     `json:"milestones"`
	Tasks       int64     `json:"tasks"`
}

// Modeles de projet.
// Les modeles, par ordre alphabetique, avec ce qu'ils contiennent. Les deux
// comptes portent sur quelques lignes par modele, lues par index ; une agence
// tient une poignee de modeles.
func (q *Queries) ListProjectTemplates(ctx context.Context, arg ListProjectTemplatesParams) ([]ListProjectTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listProjectTemplates, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectTemplatesRow{}
	for rows.Next() {
		var i ListProjectTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UpdatedAt,
			&i.Milestones,
			&i.Tasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateMilestones = `-- name: ListTemplateMilestones :many
SELECT id, template_id, title, offset_days, position FROM project_template_milestones
WHERE template_id = $1
ORDER BY position, offset_days
LIMIT 100
`

func (q *Queries) ListTemplateMilestones(ctx context.Context, templateID uuid.UUID) ([]ProjectTemplateMilestone, error) {
	rows, err := q.db.Query(ctx, listTemplateMilestones, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTemplateMilestone{}
	for rows.Next() {
		var i ProjectTemplateMilestone
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Title,
			&i.OffsetDays,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateServices = `-- name: ListTemplateServices :many
SELECT s.id, s.name, s.color
FROM project_template_services ts
JOIN services s ON s.id = ts.service_id
WHERE ts.template_id = $1
ORDER BY s.name
`

type ListTemplateServicesRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Color string    `json:"color"`
}

func (q *Queries) ListTemplateServices(ctx context.Context, templateID uuid.UUID) ([]ListTemplateServicesRow, error) {
	rows, err := q.db.Query(ctx, listTemplateServices, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateServicesRow{}
	for rows.Next() {
		var i ListTemplateServicesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateTasks = `-- name: ListTemplateTasks :many
SELECT id, template_id, title, description, priority, offset_days, position FROM project_template_tasks
WHERE template_id = $1
ORDER BY position
LIMIT 300
`

func (q *Queries) ListTemplateTasks(ctx context.Context, templateID uuid.UUID) ([]ProjectTemplateTask, error) {
	rows, err := q.db.Query(ctx, listTemplateTasks, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTemplateTask{}
	for rows.Next() {
		var i ProjectTemplateTask
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.OffsetDays,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectTemplate = `-- name: UpdateProjectTemplate :one
UPDATE project_templates SET
    name        = $2,
    description = $3,
    updated_at  = now()
WHERE id = $1
RETURNING id, name, description, created_by, created_at, updated_at
`

type UpdateProjectTemplateParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateProjectTemplate(ctx context.Context, arg UpdateProjectTemplateParams) (ProjectTemplate, error) {
	row := q.db.QueryRow(ctx, updateProjectTemplate, arg.ID, arg.Name, arg.Description)
	var i ProjectTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
