// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const addProjectFavorite = `-- name: AddProjectFavorite :exec
INSERT INTO project_favorites (user_id, project_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProjectFavoriteParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// Poser deux fois la meme etoile n'est pas une erreur : c'est un bouton qu'on
// peut recliquer, pas une creation.
func (q *Queries) AddProjectFavorite(ctx context.Context, arg AddProjectFavoriteParams) error {
	_, err := q.db.Exec(ctx, addProjectFavorite, arg.UserID, arg.ProjectID)
	return err
}

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const addProjectService = `-- name: AddProjectService :exec
INSERT INTO project_services (project_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProjectServiceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ServiceID uuid.UUID `json:"service_id"`
}

func (q *Queries) AddProjectService(ctx context.Context, arg AddProjectServiceParams) error {
	_, err := q.db.Exec(ctx, addProjectService, arg.ProjectID, arg.ServiceID)
	return err
}

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects p
WHERE p.deleted_at IS NULL
  AND ($1::text IS NULL OR p.status = $1::text)
  AND ($2::uuid IS NULL OR p.client_id = $2::uuid)
  AND ($3::text IS NULL OR p.name ILIKE '%' || $3::text || '%')
`

type CountProjectsParams struct {
	Status   *string    `json:"status"`
	ClientID *uuid.UUID `json:"client_id"`
	Search   *string    `json:"search"`
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, arg.Status, arg.ClientID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (client_id, name, description, status, priority, progress, hours_sold, starts_on, due_on, figma_url, prod_url, preprod_url, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, client_id, name, status, progress, hours_sold, hours_spent, starts_on, due_on, tasks_total, tasks_done, created_by, created_at, updated_at, deleted_at, description, priority, figma_url, prod_url, preprod_url, deliverables_pending
`

type CreateProjectParams struct {
	ClientID    uuid.UUID  `json:"client_id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Status      string     `json:"status"`
	Priority    string     `json:"priority"`
	Progress    int16      `json:"progress"`
	HoursSold   float64    `json:"hours_sold"`
	StartsOn    *time.Time `json:"starts_on"`
	DueOn       *time.Time `json:"due_on"`
	FigmaUrl    string     `json:"figma_url"`
	ProdUrl     string     `json:"prod_url"`
	PreprodUrl  string     `json:"preprod_url"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Progress,
		arg.HoursSold,
		arg.StartsOn,
		arg.DueOn,
		arg.FigmaUrl,
		arg.ProdUrl,
		arg.PreprodUrl,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Status,
		&i.Progress,
		&i.HoursSold,
		&i.HoursSpent,
		&i.StartsOn,
		&i.DueOn,
		&i.TasksTotal,
		&i.TasksDone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Description,
		&i.Priority,
		&i.FigmaUrl,
		&i.ProdUrl,
		&i.PreprodUrl,
		&i.DeliverablesPending,
	)
	return i, err
}

const createProjectFile = `-- name: CreateProjectFile :one
INSERT INTO attachments (project_id, filename, content_type, size_bytes, storage_key, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, filename, content_type, size_bytes, storage_key, uploaded_by, created_at, task_id
`

type CreateProjectFileParams struct {
	ProjectID   *uuid.UUID `json:"project_id"`
	Filename    string     `json:"filename"`
	ContentType string     `json:"content_type"`
	SizeBytes   int64      `json:"size_bytes"`
	StorageKey  string     `json:"storage_key"`
	UploadedBy  *uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateProjectFile(ctx context.Context, arg CreateProjectFileParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createProjectFile,
		arg.ProjectID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.UploadedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.TaskID,
	)
	return i, err
}

const createTaskFile = `-- name: CreateTaskFile :one
INSERT INTO attachments (task_id, filename, content_type, size_bytes, storage_key, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, filename, content_type, size_bytes, storage_key, uploaded_by, created_at, task_id
`

type CreateTaskFileParams struct {
	TaskID      *uuid.UUID `json:"task_id"`
	Filename    string     `json:"filename"`
	ContentType string     `json:"content_type"`
	SizeBytes   int64      `json:"size_bytes"`
	StorageKey  string     `json:"storage_key"`
	UploadedBy  *uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateTaskFile(ctx context.Context, arg CreateTaskFileParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createTaskFile,
		arg.TaskID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.UploadedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.TaskID,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :one
DELETE FROM attachments WHERE id = $1 RETURNING id, project_id, filename, content_type, size_bytes, storage_key, uploaded_by, created_at, task_id
`

// Rend la ligne supprimee : l'appelant a besoin de sa cle de stockage pour
// effacer le fichier du disque dans la foulee.
func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, deleteAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.TaskID,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, project_id, filename, content_type, size_bytes, storage_key, uploaded_by, created_at, task_id FROM attachments WHERE id = $1
`

// Une piece jointe se lit par son seul identifiant, quel que soit son
// proprietaire : c'est ce qui permet a un unique endpoint de telechargement
// de servir celles des projets comme celles des taches.
func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.TaskID,
	)
	return i, err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT count(*) FROM projects WHERE deleted_at IS NULL)                       AS projects_total,
    (SELECT count(*) FROM projects
     WHERE deleted_at IS NULL AND created_at >= now() - interval '30 days')        AS projects_recent,
    (SELECT count(*) FROM projects
     WHERE deleted_at IS NULL
       AND created_at >= now() - interval '60 days'
       AND created_at <  now() - interval '30 days')                               AS projects_previous,

    (SELECT count(*) FROM clients WHERE deleted_at IS NULL)                        AS clients_total,
    (SELECT count(*) FROM clients
     WHERE deleted_at IS NULL AND created_at >= now() - interval '30 days')        AS clients_recent,
    (SELECT count(*) FROM clients
     WHERE deleted_at IS NULL
       AND created_at >= now() - interval '60 days'
       AND created_at <  now() - interval '30 days')                               AS clients_previous,

    (SELECT coalesce(sum(hours_sold), 0)::numeric FROM projects WHERE deleted_at IS NULL) AS hours_total,
    (SELECT coalesce(sum(hours_sold), 0)::numeric FROM projects
     WHERE deleted_at IS NULL AND created_at >= now() - interval '30 days')        AS hours_recent,
    (SELECT coalesce(sum(hours_sold), 0)::numeric FROM projects
     WHERE deleted_at IS NULL
       AND created_at >= now() - interval '60 days'
       AND created_at <  now() - interval '30 days')                               AS hours_previous
`

type GetDashboardStatsRow struct {
	ProjectsTotal    int64   `json:"projects_total"`
	ProjectsRecent   int64   `json:"projects_recent"`
	ProjectsPrevious int64   `json:"projects_previous"`
	ClientsTotal     int64   `json:"clients_total"`
	ClientsRecent    int64   `json:"clients_recent"`
	ClientsPrevious  int64   `json:"clients_previous"`
	HoursTotal       float64 `json:"hours_total"`
	HoursRecent      float64 `json:"hours_recent"`
	HoursPrevious    float64 `json:"hours_previous"`
}

// Chiffres d'en-tete du tableau de bord.
//
// Une seule requete pour les trois tuiles, comparaison comprise : chaque
// chiffre est donne sur les trente derniers jours et sur les trente qui
// precedent, ce qui permet d'afficher une variation sans stocker d'historique.
//
// Ce sont des COUNT au rendu, contrairement a la regle du projet — ils sont
// admis ici parce qu'ils portent sur deux tables bornees (les projets et les
// clients d'une agence, quelques centaines de lignes) et qu'ils passent par
// les index partiels `deleted_at IS NULL`. Le jour ou ces tables grossissent,
// c'est un instantane quotidien qu'il faudra stocker, pas un index de plus.
func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.ProjectsTotal,
		&i.ProjectsRecent,
		&i.ProjectsPrevious,
		&i.ClientsTotal,
		&i.ClientsRecent,
		&i.ClientsPrevious,
		&i.HoursTotal,
		&i.HoursRecent,
		&i.HoursPrevious,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT
    p.id, p.client_id, p.name, p.status, p.progress, p.hours_sold, p.hours_spent, p.starts_on, p.due_on, p.tasks_total, p.tasks_done, p.created_by, p.created_at, p.updated_at, p.deleted_at, p.description, p.priority, p.figma_url, p.prod_url, p.preprod_url, p.deliverables_pending,
    c.name AS client_name,
    -- L'interlocuteur du projet est le contact principal de son client. Joint
    -- a gauche : un client sans contact ne doit pas faire disparaitre le
    -- projet de la fiche.
    btrim(coalesce(ct.firstname, '') || ' ' || coalesce(ct.lastname, '')) AS client_contact_name,
    coalesce(ct.role, '')                                                 AS client_contact_role,
    ct.email                                                              AS client_contact_email,
    EXISTS (
        SELECT 1 FROM project_favorites f
        WHERE f.project_id = p.id AND f.user_id = $1
    ) AS is_favorite
FROM projects p
JOIN clients c ON c.id = p.client_id
LEFT JOIN contacts ct ON ct.id = c.primary_contact_id AND ct.deleted_at IS NULL
WHERE p.id = $2 AND p.deleted_at IS NULL
`

type GetProjectParams struct {
	ViewerID uuid.UUID `json:"viewer_id"`
	ID       uuid.UUID `json:"id"`
}

type GetProjectRow struct {
	ID                  uuid.UUID  `json:"id"`
	ClientID            uuid.UUID  `json:"client_id"`
	Name                string     `json:"name"`
	Status              string     `json:"status"`
	Progress            int16      `json:"progress"`
	HoursSold           float64    `json:"hours_sold"`
	HoursSpent          float64    `json:"hours_spent"`
	StartsOn            *time.Time `json:"starts_on"`
	DueOn               *time.Time `json:"due_on"`
	TasksTotal          int32      `json:"tasks_total"`
	TasksDone           int32      `json:"tasks_done"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	DeletedAt           *time.Time `json:"deleted_at"`
	Description         string     `json:"description"`
	Priority            string     `json:"priority"`
	FigmaUrl            string     `json:"figma_url"`
	ProdUrl             string     `json:"prod_url"`
	PreprodUrl          string     `json:"preprod_url"`
	DeliverablesPending int32      `json:"deliverables_pending"`
	ClientName          string     `json:"client_name"`
	ClientContactName   string     `json:"client_contact_name"`
	ClientContactRole   string     `json:"client_contact_role"`
	ClientContactEmail  *string    `json:"client_contact_email"`
	IsFavorite          bool       `json:"is_favorite"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ViewerID, arg.ID)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Status,
		&i.Progress,
		&i.HoursSold,
		&i.HoursSpent,
		&i.StartsOn,
		&i.DueOn,
		&i.TasksTotal,
		&i.TasksDone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Description,
		&i.Priority,
		&i.FigmaUrl,
		&i.ProdUrl,
		&i.PreprodUrl,
		&i.DeliverablesPending,
		&i.ClientName,
		&i.ClientContactName,
		&i.ClientContactRole,
		&i.ClientContactEmail,
		&i.IsFavorite,
	)
	return i, err
}

const listFavoriteProjects = `-- name: ListFavoriteProjects :many
SELECT
    p.id,
    p.name,
    p.status
FROM project_favorites f
JOIN projects p ON p.id = f.project_id AND p.deleted_at IS NULL
WHERE f.user_id = $1
ORDER BY p.name, p.id
LIMIT 20
`

type ListFavoriteProjectsRow struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Status string    `json:"status"`
}

// Projets etoiles par l'appelant, pour les raccourcis de la barre laterale.
//
// Bornee en dur : c'est une liste de navigation, pas un ecran. Vingt raccourcis
// tiennent dans un panneau, au-dela l'etoile ne trie plus rien et c'est la
// liste des projets qu'il faut ouvrir. La regle du projet veut un LIMIT partout
// — ici il n'a pas de page suivante, il a une fin.
func (q *Queries) ListFavoriteProjects(ctx context.Context, userID uuid.UUID) ([]ListFavoriteProjectsRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoriteProjectsRow{}
	for rows.Next() {
		var i ListFavoriteProjectsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersOfProjects = `-- name: ListMembersOfProjects :many
SELECT
    pm.project_id,
    u.id,
    u.firstname,
    u.lastname,
    u.avatar_url
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = ANY($1::uuid[])
  AND u.deleted_at IS NULL
ORDER BY pm.project_id, u.firstname, u.lastname
`

type ListMembersOfProjectsRow struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	AvatarUrl *string   `json:"avatar_url"`
}

// Equipes de plusieurs projets en une requete.
//
// C'est la parade au N+1 de la liste : le handler passe les identifiants de la
// page entiere et repartit les lignes ensuite. Une requete par projet aurait
// fait vingt allers-retours pour afficher vingt lignes.
func (q *Queries) ListMembersOfProjects(ctx context.Context, projectIds []uuid.UUID) ([]ListMembersOfProjectsRow, error) {
	rows, err := q.db.Query(ctx, listMembersOfProjects, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersOfProjectsRow{}
	for rows.Next() {
		var i ListMembersOfProjectsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectFiles = `-- name: ListProjectFiles :many
SELECT id, project_id, filename, content_type, size_bytes, storage_key, uploaded_by, created_at, task_id FROM attachments WHERE project_id = $1 ORDER BY created_at DESC
`

// Pieces jointes d'un projet, la derniere deposee en premier.
func (q *Queries) ListProjectFiles(ctx context.Context, projectID *uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listProjectFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id, p.client_id, p.name, p.status, p.progress, p.hours_sold, p.hours_spent, p.starts_on, p.due_on, p.tasks_total, p.tasks_done, p.created_by, p.created_at, p.updated_at, p.deleted_at, p.description, p.priority, p.figma_url, p.prod_url, p.preprod_url, p.deliverables_pending,
    c.name AS client_name,
    -- L'etoile est personnelle : elle se lit pour l'appelant, pas dans l'absolu.
    EXISTS (
        SELECT 1 FROM project_favorites f
        WHERE f.project_id = p.id AND f.user_id = $1
    ) AS is_favorite
FROM projects p
JOIN clients c ON c.id = p.client_id
WHERE p.deleted_at IS NULL
  AND ($2::text IS NULL OR p.status = $2::text)
  AND ($3::uuid IS NULL OR p.client_id = $3::uuid)
  AND ($4::text IS NULL OR p.name ILIKE '%' || $4::text || '%')
ORDER BY
    -- Les favoris remontent avant tout le reste, quel que soit le tri demande :
    -- c'est ce que promet une etoile — epingler, pas ajouter un critere de plus
    -- qu'un changement de colonne ferait oublier. Le tri choisi s'applique
    -- ensuite, a l'interieur de chaque groupe.
    is_favorite DESC,
    -- Un seul ORDER BY parametre plutot que quatre requetes : le tri vient de
    -- l'ecran, et les colonnes possibles sont closes par le handler.
    CASE WHEN $5::text = 'name' AND $6::text = 'asc' THEN p.name END ASC,
    CASE WHEN $5::text = 'name' AND $6::text = 'desc' THEN p.name END DESC,
    CASE WHEN $5::text = 'progress' AND $6::text = 'asc' THEN p.progress END ASC,
    CASE WHEN $5::text = 'progress' AND $6::text = 'desc' THEN p.progress END DESC,
    CASE WHEN $5::text = 'budget' AND $6::text = 'asc' THEN p.hours_spent END ASC,
    CASE WHEN $5::text = 'budget' AND $6::text = 'desc' THEN p.hours_spent END DESC,
    CASE WHEN $6::text = 'desc' THEN p.due_on END DESC NULLS LAST,
    p.due_on ASC NULLS LAST,
    -- Depart d'egalite stable : sans lui, deux projets de meme echeance
    -- peuvent changer de place d'une page a l'autre et l'un des deux disparait.
    p.id ASC
LIMIT $8 OFFSET $7
`

type ListProjectsParams struct {
	ViewerID   uuid.UUID  `json:"viewer_id"`
	Status     *string    `json:"status"`
	ClientID   *uuid.UUID `json:"client_id"`
	Search     *string    `json:"search"`
	Sort       string     `json:"sort"`
	Dir        string     `json:"dir"`
	PageOffset int32      `json:"page_offset"`
	PageSize   int32      `json:"page_size"`
}

type ListProjectsRow struct {
	ID                  uuid.UUID  `json:"id"`
	ClientID            uuid.UUID  `json:"client_id"`
	Name                string     `json:"name"`
	Status              string     `json:"status"`
	Progress            int16      `json:"progress"`
	HoursSold           float64    `json:"hours_sold"`
	HoursSpent          float64    `json:"hours_spent"`
	StartsOn            *time.Time `json:"starts_on"`
	DueOn               *time.Time `json:"due_on"`
	TasksTotal          int32      `json:"tasks_total"`
	TasksDone           int32      `json:"tasks_done"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	DeletedAt           *time.Time `json:"deleted_at"`
	Description         string     `json:"description"`
	Priority            string     `json:"priority"`
	FigmaUrl            string     `json:"figma_url"`
	ProdUrl             string     `json:"prod_url"`
	PreprodUrl          string     `json:"preprod_url"`
	DeliverablesPending int32      `json:"deliverables_pending"`
	ClientName          string     `json:"client_name"`
	IsFavorite          bool       `json:"is_favorite"`
}

// Liste paginee du back-office.
//
// Le nom du client est joint ici plutot que ramene par une seconde requete :
// c'est une valeur scalaire par ligne, la jointure ne multiplie rien. L'equipe,
// elle, est une collection : elle passe par ListMembersOfProjects, qui charge
// d'un coup les membres de toute la page.
//
// Les compteurs de taches sont lus tels quels : ce sont des colonnes tenues par
// declencheur, aucun COUNT n'est fait au rendu.
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.ViewerID,
		arg.Status,
		arg.ClientID,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Status,
			&i.Progress,
			&i.HoursSold,
			&i.HoursSpent,
			&i.StartsOn,
			&i.DueOn,
			&i.TasksTotal,
			&i.TasksDone,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Description,
			&i.Priority,
			&i.FigmaUrl,
			&i.ProdUrl,
			&i.PreprodUrl,
			&i.DeliverablesPending,
			&i.ClientName,
			&i.IsFavorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesOfProjects = `-- name: ListServicesOfProjects :many
SELECT
    ps.project_id,
    s.id,
    s.name,
    s.color
FROM project_services ps
JOIN services s ON s.id = ps.service_id AND s.deleted_at IS NULL
WHERE ps.project_id = ANY($1::uuid[])
ORDER BY ps.project_id, s.name, s.id
`

type ListServicesOfProjectsRow struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
}

// Services de plusieurs projets en une requete.
//
// Meme parade au N+1 que pour les equipes : une collection ne se joint pas a la
// liste — elle multiplierait les lignes — elle se charge d'un coup pour la page
// entiere, et le service la repartit ensuite.
func (q *Queries) ListServicesOfProjects(ctx context.Context, projectIds []uuid.UUID) ([]ListServicesOfProjectsRow, error) {
	rows, err := q.db.Query(ctx, listServicesOfProjects, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesOfProjectsRow{}
	for rows.Next() {
		var i ListServicesOfProjectsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskFiles = `-- name: ListTaskFiles :many
SELECT id, project_id, filename, content_type, size_bytes, storage_key, uploaded_by, created_at, task_id FROM attachments
WHERE task_id = ANY($1::uuid[])
ORDER BY task_id, created_at DESC
`

// Pieces jointes de plusieurs taches, pour le tiroir et le tableau.
func (q *Queries) ListTaskFiles(ctx context.Context, taskIds []uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listTaskFiles, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectFavorite = `-- name: RemoveProjectFavorite :exec
DELETE FROM project_favorites WHERE user_id = $1 AND project_id = $2
`

type RemoveProjectFavoriteParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) RemoveProjectFavorite(ctx context.Context, arg RemoveProjectFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeProjectFavorite, arg.UserID, arg.ProjectID)
	return err
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const setProjectServices = `-- name: SetProjectServices :exec
DELETE FROM project_services WHERE project_id = $1
`

// Remplace les services d'un projet par la liste fournie.
//
// Effacer puis reinserer plutot que calculer une difference : la liste est
// courte, et le formulaire envoie toujours l'etat complet qu'il veut voir.
func (q *Queries) SetProjectServices(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setProjectServices, projectID)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name        = COALESCE($1::text, name),
    -- La description se vide en envoyant la chaine vide, pas en omettant le
    -- champ : COALESCE ne distingue pas « absent » de « efface », et un projet
    -- doit pouvoir perdre son resume.
    description = COALESCE($2::text, description),
    status      = COALESCE($3::text, status),
    priority    = COALESCE($4::text, priority),
    figma_url   = COALESCE($5::text, figma_url),
    prod_url    = COALESCE($6::text, prod_url),
    preprod_url = COALESCE($7::text, preprod_url),
    progress    = COALESCE($8::smallint, progress),
    hours_sold  = COALESCE($9::numeric, hours_sold),
    client_id   = COALESCE($10::uuid, client_id),
    starts_on   = CASE WHEN $11::boolean THEN NULL
                       ELSE COALESCE($12::date, starts_on) END,
    due_on      = CASE WHEN $13::boolean THEN NULL
                       ELSE COALESCE($14::date, due_on) END,
    updated_at  = now()
WHERE id = $15 AND deleted_at IS NULL
RETURNING id, client_id, name, status, progress, hours_sold, hours_spent, starts_on, due_on, tasks_total, tasks_done, created_by, created_at, updated_at, deleted_at, description, priority, figma_url, prod_url, preprod_url, deliverables_pending
`

type UpdateProjectParams struct {
	Name          *string    `json:"name"`
	Description   *string    `json:"description"`
	Status        *string    `json:"status"`
	Priority      *string    `json:"priority"`
	FigmaUrl      *string    `json:"figma_url"`
	ProdUrl       *string    `json:"prod_url"`
	PreprodUrl    *string    `json:"preprod_url"`
	Progress      *int16     `json:"progress"`
	HoursSold     *float64   `json:"hours_sold"`
	ClientID      *uuid.UUID `json:"client_id"`
	ClearStartsOn bool       `json:"clear_starts_on"`
	StartsOn      *time.Time `json:"starts_on"`
	ClearDueOn    bool       `json:"clear_due_on"`
	DueOn         *time.Time `json:"due_on"`
	ID            uuid.UUID  `json:"id"`
}

// Mise a jour partielle : chaque champ absent de la requete garde sa valeur.
// COALESCE sur un parametre nullable dit exactement cela, et evite d'ecrire
// une requete par champ modifiable.
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.FigmaUrl,
		arg.ProdUrl,
		arg.PreprodUrl,
		arg.Progress,
		arg.HoursSold,
		arg.ClientID,
		arg.ClearStartsOn,
		arg.StartsOn,
		arg.ClearDueOn,
		arg.DueOn,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Status,
		&i.Progress,
		&i.HoursSold,
		&i.HoursSpent,
		&i.StartsOn,
		&i.DueOn,
		&i.TasksTotal,
		&i.TasksDone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Description,
		&i.Priority,
		&i.FigmaUrl,
		&i.ProdUrl,
		&i.PreprodUrl,
		&i.DeliverablesPending,
	)
	return i, err
}
