// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Poser deux fois la meme etoile n'est pas une erreur : c'est un bouton qu'on
	// peut recliquer, pas une creation.
	AddProjectFavorite(ctx context.Context, arg AddProjectFavoriteParams) error
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error
	AddProjectService(ctx context.Context, arg AddProjectServiceParams) error
	AddTaskService(ctx context.Context, arg AddTaskServiceParams) error
	AssignTask(ctx context.Context, arg AssignTaskParams) error
	// Rattache un contact libre a un client.
	//
	// La condition sur `client_id IS NULL` fait de cette requete une prise de
	// possession sure : deux clients crees en meme temps avec le meme contact, un
	// seul l'obtient, et l'autre ne touche aucune ligne.
	AttachContactToClient(ctx context.Context, arg AttachContactToClientParams) (Contact, error)
	// Une adresse de photo est-elle celle d'un compte ?
	//
	// Le magasin de fichiers est commun aux pieces jointes et aux photos : sans
	// cette verification, l'endpoint des photos servirait n'importe quelle image
	// du magasin a qui en devinerait la cle, court-circuitant les droits du projet
	// qui la porte.
	AvatarURLExists(ctx context.Context, avatarUrl *string) (bool, error)
	// Retire la designation qui pointe vers ce contact, quel que soit le client.
	// Appelee avant la suppression logique : la cle etrangere ne se declenche que
	// sur un DELETE reel, et laisserait sinon un client designant un contact mort.
	ClearPrimaryContactOf(ctx context.Context, primaryContactID *uuid.UUID) error
	ClearTaskServices(ctx context.Context, taskID uuid.UUID) error
	CountCrmClients(ctx context.Context, arg CountCrmClientsParams) (int64, error)
	CountCrmContacts(ctx context.Context, arg CountCrmContactsParams) (int64, error)
	// Total pour la pagination, aux memes conditions que la liste.
	CountDeliverables(ctx context.Context, arg CountDeliverablesParams) (int64, error)
	CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error)
	// Tous statuts confondus, livres compris : c'est ce qui decide si un client
	// peut disparaitre. Un projet livre garde la trace de qui l'a commande.
	CountProjectsOfClient(ctx context.Context, clientID uuid.UUID) (int64, error)
	CountServices(ctx context.Context, search *string) (int64, error)
	CountTasks(ctx context.Context, arg CountTasksParams) (int64, error)
	CountTasksOfProject(ctx context.Context, projectID uuid.UUID) (int64, error)
	// Total pour la pagination, aux memes conditions que la liste.
	CountTicketsAssignedTo(ctx context.Context, arg CountTicketsAssignedToParams) (int64, error)
	// Total pour la pagination, aux memes conditions que la liste.
	CountTicketsByProject(ctx context.Context, arg CountTicketsByProjectParams) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context, role *string) (int64, error)
	// Le client naît sans interlocuteur : ses contacts sont crees ensuite, et la
	// cle etrangere composite exige qu'un contact principal lui appartienne deja.
	CreateClient(ctx context.Context, name string) (Client, error)
	// `client_id` peut etre nul : le contact est alors libre, en attente d'une
	// entreprise.
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	// Le livrable nait sans version : c'est la soumission qui lui en donne une.
	CreateDeliverable(ctx context.Context, arg CreateDeliverableParams) (uuid.UUID, error)
	CreateDeliverableVersion(ctx context.Context, arg CreateDeliverableVersionParams) (uuid.UUID, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectFile(ctx context.Context, arg CreateProjectFileParams) (Attachment, error)
	// Le jeton n'est jamais stocke en clair : seul son empreinte SHA-256 entre en
	// base, si bien qu'une fuite de la table ne permet pas de rejouer une session.
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (CreateServiceRow, error)
	// Le rang par defaut place la nouvelle app en queue : on ajoute au bout, on
	// reordonne ensuite si besoin.
	CreateSidebarApp(ctx context.Context, arg CreateSidebarAppParams) (CreateSidebarAppRow, error)
	CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Subtask, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTaskComment(ctx context.Context, arg CreateTaskCommentParams) (TaskComment, error)
	CreateTaskFile(ctx context.Context, arg CreateTaskFileParams) (Attachment, error)
	// Depot d'un ticket.
	//
	// Le numero n'est pas fourni : l'identite de la colonne l'attribue, ce qui
	// rend deux creations simultanees incapables d'obtenir le meme.
	//
	// La CTE evite un second aller-retour pour le nom du projet : la ligne rendue a
	// la meme forme que celles de la liste, et l'ecran peut l'afficher telle quelle.
	CreateTicket(ctx context.Context, arg CreateTicketParams) (CreateTicketRow, error)
	// Inscrit un changement au journal.
	CreateTicketEvent(ctx context.Context, arg CreateTicketEventParams) (CreateTicketEventRow, error)
	// Inscrit un message au registre.
	CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (CreateTicketMessageRow, error)
	CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Enregistre la reponse du client sur une version precise.
	//
	// La clause sur `decision` rend la requete rejouable sans degat : une decision
	// deja prise ne se reecrit pas, et l'appelant lit zero ligne touchee plutot que
	// d'ecraser la date et l'auteur d'origine.
	DecideDeliverableVersion(ctx context.Context, arg DecideDeliverableVersionParams) error
	// Rend la ligne supprimee : l'appelant a besoin de sa cle de stockage pour
	// effacer le fichier du disque dans la foulee.
	DeleteAttachment(ctx context.Context, id uuid.UUID) (Attachment, error)
	// Purge des jetons expires depuis assez longtemps pour ne plus rien prouver.
	// Les jetons revoques recents sont conserves : ce sont eux qui permettent de
	// reconnaitre un rejeu.
	DeleteExpiredRefreshTokens(ctx context.Context, retention pgtype.Interval) error
	// Suppression douce, comme partout : un service retire d'un referentiel a pu
	// etre porte par des donnees passees.
	DeleteService(ctx context.Context, id uuid.UUID) (int64, error)
	// Suppression douce, comme partout. Rend la cle du logo pour que l'appelant
	// decide du sort du fichier.
	DeleteSidebarApp(ctx context.Context, id uuid.UUID) (*string, error)
	// Suppression reelle : une sous-tache n'a pas d'histoire propre, et le
	// « Annuler » du rappel la recree telle quelle.
	DeleteSubtask(ctx context.Context, id uuid.UUID) error
	DeleteTimeEntry(ctx context.Context, arg DeleteTimeEntryParams) (int64, error)
	// Une piece jointe se lit par son seul identifiant, quel que soit son
	// proprietaire : c'est ce qui permet a un unique endpoint de telechargement
	// de servir celles des projets comme celles des taches.
	GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error)
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
	// Recherche exacte, insensible a la casse : c'est elle qui evite de creer
	// « Novaterre » a cote de « novaterre » quand le nom est saisi a la volee.
	GetClientByName(ctx context.Context, name string) (Client, error)
	GetContact(ctx context.Context, id uuid.UUID) (GetContactRow, error)
	// Fiche d'un client : son en-tete, avec le contact principal et les compteurs
	// que le tableau montre deja.
	GetCrmClient(ctx context.Context, id uuid.UUID) (GetCrmClientRow, error)
	// Chiffres d'en-tete du tableau de bord.
	//
	// Une seule requete pour les trois tuiles, comparaison comprise : chaque
	// chiffre est donne sur les trente derniers jours et sur les trente qui
	// precedent, ce qui permet d'afficher une variation sans stocker d'historique.
	//
	// Ce sont des COUNT au rendu, contrairement a la regle du projet — ils sont
	// admis ici parce qu'ils portent sur deux tables bornees (les projets et les
	// clients d'une agence, quelques centaines de lignes) et qu'ils passent par
	// les index partiels `deleted_at IS NULL`. Le jour ou ces tables grossissent,
	// c'est un instantane quotidien qu'il faudra stocker, pas un index de plus.
	GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error)
	// Un livrable et sa version courante, aux memes colonnes que la liste : le
	// depot et la decision rendent la ligne telle que l'ecran la reaffiche.
	GetDeliverable(ctx context.Context, id uuid.UUID) (GetDeliverableRow, error)
	GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error)
	// Le refresh a besoin du jeton ET de l'etat du compte pour decider. Les lire
	// en une jointure plutot qu'en deux requetes evite qu'un compte supprime entre
	// les deux obtienne un nouvel acces.
	//
	// La ligne est renvoyee meme revoquee ou expiree : c'est l'appelant qui
	// tranche, parce qu'un jeton revoque presente a nouveau signale un rejeu et
	// doit declencher la revocation de toute la famille.
	GetRefreshTokenWithUser(ctx context.Context, tokenHash []byte) (GetRefreshTokenWithUserRow, error)
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	GetSidebarApp(ctx context.Context, id uuid.UUID) (GetSidebarAppRow, error)
	GetSubtask(ctx context.Context, id uuid.UUID) (Subtask, error)
	// Tache et son contexte de projet : le tiroir affiche le nom du projet, et
	// l'aller chercher a part ferait une requete de plus pour un seul mot.
	GetTask(ctx context.Context, id uuid.UUID) (GetTaskRow, error)
	// Avancement des taches par nature, pour le tableau de bord.
	//
	// La nature est le champ libre `tag` — « Design », « Integration », « Contenu »
	// — c'est-a-dire l'axe que le graphique appelle « domaine ». Les taches qui
	// n'en portent pas sont regroupees plutot qu'ecartees : les omettre donnerait
	// un graphique qui ne compte pas tout ce qui existe.
	//
	// « En cours » agrege `progress` et `review` : le dessin n'a que trois etats
	// places, et une tache en relecture est commencee sans etre finie.
	//
	// Bornee a cinq lignes, les natures les plus portees devant : le panneau a la
	// place de quelques barres, et une agence qui inventerait trente etiquettes
	// n'y lirait plus rien.
	GetTaskProgressByTag(ctx context.Context) ([]GetTaskProgressByTagRow, error)
	// Fiche d'un ticket : son en-tete et ses coordonnees.
	//
	// Les messages et les evenements font l'objet de deux requetes a part : les
	// ramener par jointure multiplierait l'en-tete par le nombre de lignes du
	// registre.
	GetTicket(ctx context.Context, id uuid.UUID) (GetTicketRow, error)
	GetTimeEntry(ctx context.Context, arg GetTimeEntryParams) (GetTimeEntryRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Affectations de plusieurs taches en une requete : meme parade au N+1 que
	// pour les equipes de projets.
	ListAssigneesOfTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListAssigneesOfTasksRow, error)
	// Sert le champ « Client » du formulaire de projet. Pagine comme le reste,
	// meme si une agence en compte quelques dizaines : la regle ne souffre pas
	// d'exception, sinon elle finit par etre oubliee la ou elle compte.
	//
	// L'interlocuteur affiche est le contact principal, joint a gauche : un client
	// sans contact reste proposable.
	ListClients(ctx context.Context, arg ListClientsParams) ([]ListClientsRow, error)
	// Toutes les cartes du kanban, tous statuts confondus.
	//
	// Bornee et non paginee, comme le tableau des taches : un kanban se lit en
	// entier ou pas du tout. Le handler previent quand la borne est atteinte.
	ListClientsBoard(ctx context.Context, arg ListClientsBoardParams) ([]ListClientsBoardRow, error)
	// Alimente le menu deroulant qui designe le contact principal d'un client.
	//
	// Il propose deux ensembles : les contacts du client, et les contacts libres —
	// ces derniers etant rattaches au moment ou on les choisit. Sans eux, un
	// contact cree sans entreprise n'aurait aucun moyen d'en rejoindre une.
	//
	// Les contacts d'un AUTRE client restent exclus : la cle etrangere composite
	// les refuserait, et les proposer laisserait croire qu'on peut se les prendre.
	// Cast explicite pour sqlc, qui sans lui rend un `interface{}`.
	// Les siens d'abord : ce sont eux qu'on cherche le plus souvent.
	ListContactsOfClient(ctx context.Context, arg ListContactsOfClientParams) ([]ListContactsOfClientRow, error)
	// Liste paginee de l'ecran CRM.
	//
	// Distincte de ListClients, qui sert le champ « Client » d'un formulaire :
	// celle-la remplit un tableau, avec sa recherche, son filtre et son tri. Les
	// confondre reviendrait a faire porter a un menu deroulant les besoins d'un
	// ecran, et inversement.
	//
	// `projects_active` et `portal_users` sont lus tels quels : colonnes tenues
	// par declencheur, aucun COUNT au rendu. `contacts_count` en est un vrai, mais
	// sur un index partiel et pour la seule page affichee.
	ListCrmClients(ctx context.Context, arg ListCrmClientsParams) ([]ListCrmClientsRow, error)
	// Liste paginee de l'ecran « Contacts ».
	//
	// Jointure a gauche : un contact libre n'a pas encore d'entreprise, et doit
	// rester visible — c'est meme la seule liste ou on le retrouve.
	//
	// `is_primary` dit si la personne est l'interlocuteur principal de son client.
	// `coalesce` et non la seule egalite : chez un client qui n'a designe
	// personne, `primary_contact_id` est NULL et la comparaison rendrait NULL —
	// que le scan Go refuserait dans un booleen. Le cast explicite est la pour
	// sqlc, qui sans lui rend un `interface{}`.
	ListCrmContacts(ctx context.Context, arg ListCrmContactsParams) ([]ListCrmContactsRow, error)
	// Le fil complet d'un livrable, de la premiere version a la derniere : c'est
	// la trace que le module existe pour garder.
	ListDeliverableVersions(ctx context.Context, deliverableID uuid.UUID) ([]ListDeliverableVersionsRow, error)
	// Livrables.
	//
	// L'etat d'un livrable n'est pas une colonne : c'est la decision de sa version
	// courante, et l'absence de version vaut brouillon. Toutes les requetes qui
	// l'affichent joignent donc `deliverable_versions` sur `current_version_id` —
	// une jointure sur cle primaire, pas un LATERAL par ligne.
	// L'ecran « Livrables » du module, qui traverse les projets.
	//
	// Trie du plus recemment soumis au plus ancien, les brouillons en queue : c'est
	// l'ordre dans lequel on reprend un dossier. L'anciennete d'une attente se lit
	// sur `submitted_at`, que l'ecran compare a maintenant — une duree renvoyee ici
	// serait fausse des la seconde suivante.
	ListDeliverables(ctx context.Context, arg ListDeliverablesParams) ([]ListDeliverablesRow, error)
	// Projets etoiles par l'appelant, pour les raccourcis de la barre laterale.
	//
	// Bornee en dur : c'est une liste de navigation, pas un ecran. Vingt raccourcis
	// tiennent dans un panneau, au-dela l'etoile ne trie plus rien et c'est la
	// liste des projets qu'il faut ouvrir. La regle du projet veut un LIMIT partout
	// — ici il n'a pas de page suivante, il a une fin.
	ListFavoriteProjects(ctx context.Context, userID uuid.UUID) ([]ListFavoriteProjectsRow, error)
	// Contacts sans entreprise, tels que le formulaire de creation d'un client les
	// propose. Un contact deja rattache n'y figure pas : il appartient a un autre
	// client, et le nouveau ne peut pas le lui prendre.
	ListFreeContacts(ctx context.Context, arg ListFreeContactsParams) ([]Contact, error)
	// Equipes de plusieurs projets en une requete.
	//
	// C'est la parade au N+1 de la liste : le handler passe les identifiants de la
	// page entiere et repartit les lignes ensuite. Une requete par projet aurait
	// fait vingt allers-retours pour afficher vingt lignes.
	ListMembersOfProjects(ctx context.Context, projectIds []uuid.UUID) ([]ListMembersOfProjectsRow, error)
	// Qui prevenir pour un geste pose sur une tache.
	//
	// Les administrateurs suivent tout ce qui se passe ; les personnes affectees a
	// la tache suivent la leur. L'auteur du geste est exclu ici plutot que dans
	// chaque appelant : personne n'a besoin d'etre prevenu de ce qu'il vient de
	// faire, et l'oubli ne se verrait qu'a l'usage.
	ListNotificationRecipients(ctx context.Context, arg ListNotificationRecipientsParams) ([]uuid.UUID, error)
	// Les notifications d'une personne, les plus recentes d'abord.
	//
	// Pagination par curseur et non par offset : la liste s'allonge par le haut,
	// et un OFFSET ferait reapparaitre une ligne deja lue des qu'une notification
	// arrive pendant la lecture.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	// Permissions d'un role, servies telles quelles au front pour qu'il masque les
	// actions inaccessibles. Le front cache des boutons, il ne protege rien : la
	// garde reste la seule autorite.
	ListPermissionsByRole(ctx context.Context, roleCode string) ([]string, error)
	// Comptes de portail rattaches au client. La colonne existe, l'ecran qui la
	// remplit non : la fiche la montre pour que le jour ou on rattachera quelqu'un,
	// ce soit visible.
	ListPortalUsersOfClient(ctx context.Context, arg ListPortalUsersOfClientParams) ([]ListPortalUsersOfClientRow, error)
	// Pieces jointes d'un projet, la derniere deposee en premier.
	ListProjectFiles(ctx context.Context, projectID *uuid.UUID) ([]Attachment, error)
	// Liste paginee du back-office.
	//
	// Le nom du client est joint ici plutot que ramene par une seconde requete :
	// c'est une valeur scalaire par ligne, la jointure ne multiplie rien. L'equipe,
	// elle, est une collection : elle passe par ListMembersOfProjects, qui charge
	// d'un coup les membres de toute la page.
	//
	// Les compteurs de taches sont lus tels quels : ce sont des colonnes tenues par
	// declencheur, aucun COUNT n'est fait au rendu.
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	// Projets du client, tels que sa fiche les liste. Bornee : une fiche montre ce
	// qui se lit d'un coup d'oeil, pas tout l'historique d'un gros compte.
	ListProjectsOfClient(ctx context.Context, arg ListProjectsOfClientParams) ([]ListProjectsOfClientRow, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	// Services : referentiel des prestations de l'agence.
	// Page du tableau, par ordre alphabetique.
	ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error)
	// Services de plusieurs projets en une requete.
	//
	// Meme parade au N+1 que pour les equipes : une collection ne se joint pas a la
	// liste — elle multiplierait les lignes — elle se charge d'un coup pour la page
	// entiere, et le service la repartit ensuite.
	ListServicesOfProjects(ctx context.Context, projectIds []uuid.UUID) ([]ListServicesOfProjectsRow, error)
	// Services de plusieurs taches en une requete, comme pour les affectations.
	ListServicesOfTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListServicesOfTasksRow, error)
	// Applications jointes depuis le rail.
	// Toutes les apps, dans l'ordre du rail.
	//
	// Bornee en dur : c'est une liste de navigation, pas un ecran. Vingt raccourcis
	// tiennent dans un rail, au-dela ce n'est plus un rail. La regle du projet veut
	// un LIMIT partout — ici il n'a pas de page suivante, il a une fin.
	ListSidebarApps(ctx context.Context) ([]ListSidebarAppsRow, error)
	// Apps dont le logo reste a chercher.
	//
	// Celles qui n'ont pas de logo et qu'on n'a jamais tentees, ou tentees avant la
	// borne passee en parametre. Un echec n'est donc pas rejoue en boucle : il
	// attend son tour de reessai.
	//
	// Bornee : un passage traite une poignee d'apps, le suivant prendra la suite.
	ListSidebarAppsNeedingFavicon(ctx context.Context, arg ListSidebarAppsNeedingFaviconParams) ([]ListSidebarAppsNeedingFaviconRow, error)
	ListSubtasks(ctx context.Context, taskID uuid.UUID) ([]Subtask, error)
	ListTaskActivity(ctx context.Context, arg ListTaskActivityParams) ([]ListTaskActivityRow, error)
	ListTaskComments(ctx context.Context, arg ListTaskCommentsParams) ([]ListTaskCommentsRow, error)
	// Pieces jointes de plusieurs taches, pour le tiroir et le tableau.
	ListTaskFiles(ctx context.Context, taskIds []uuid.UUID) ([]Attachment, error)
	// Taches de toute l'agence, pour l'ecran « Taches » du module.
	//
	// Le nom du projet est joint ici : une tache sortie de sa fiche ne dit plus
	// d'ou elle vient, et l'aller chercher ensuite ferait une requete par ligne.
	//
	// Meme borne que le tableau d'un projet, et pour la meme raison : l'ecran a
	// une vue kanban, et on ne tourne pas la page d'un kanban. Le total part a
	// cote pour que la vue puisse dire qu'elle n'affiche pas tout.
	//
	// La jointure sur les projets vivants fait le reste du filtrage : les taches
	// d'un projet supprime ne doivent pas reapparaitre dans une liste globale.
	ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error)
	// Tableau des taches d'un projet.
	//
	// Bornee comme toutes les listes. Un tableau n'a pas de pagination visible —
	// on ne tourne pas la page d'un kanban — mais la borne existe quand meme :
	// c'est elle qui empeche un projet devenu fourre-tout de ramener dix mille
	// lignes. Le handler renvoie le total a cote, pour que l'ecran puisse dire
	// qu'il n'affiche pas tout.
	ListTasksOfProject(ctx context.Context, arg ListTasksOfProjectParams) ([]Task, error)
	// Ce qui est arrive au ticket, dans le meme ordre.
	ListTicketEvents(ctx context.Context, ticketID uuid.UUID) ([]ListTicketEventsRow, error)
	// Ce qui s'est dit sur un ticket, du plus ancien au plus recent.
	ListTicketMessages(ctx context.Context, ticketID uuid.UUID) ([]ListTicketMessagesRow, error)
	// Tickets.
	//
	// Les trois vues de l'ecran — tableau, kanban par projet, kanban par statut —
	// partagent la meme barre d'outils, donc les memes filtres. Ils sont ecrits une
	// fois par requete plutot que composes en Go : sqlc verifie alors le SQL a la
	// generation, ce qu'une concatenation de chaines interdirait.
	//
	// `assignee_id` n'est pas un filtre mais une clause : l'ecran ne montre que les
	// tickets du compte appelant, et l'identifiant vient de la session.
	// Page du tableau, du plus recemment mis a jour au plus ancien — l'ordre dans
	// lequel on reprend son travail.
	//
	// La recherche porte sur le sujet et sur le numero : « 47 » doit retrouver le
	// ticket #47, c'est ainsi qu'on le designe a l'oral.
	ListTicketsAssignedTo(ctx context.Context, arg ListTicketsAssignedToParams) ([]ListTicketsAssignedToRow, error)
	// Toutes les cartes des deux kanbans, aux memes filtres que le tableau.
	//
	// Bornee et non paginee, comme les kanbans des taches et des clients : un
	// tableau se lit en entier ou pas du tout, et paginer une colonne n'aurait
	// aucun sens. Le handler previent quand la borne a coupe.
	//
	// Trie par numero decroissant et non par mise a jour : dans un tableau, c'est
	// la colonne qui porte le classement, et l'ordre a l'interieur doit rester
	// stable d'un affichage a l'autre.
	ListTicketsBoardAssignedTo(ctx context.Context, arg ListTicketsBoardAssignedToParams) ([]ListTicketsBoardAssignedToRow, error)
	// Toutes les cartes du kanban d'un projet.
	//
	// Bornee et non paginee comme le kanban personnel, et triee par numero
	// decroissant pour la meme raison : dans un tableau, c'est la colonne qui porte
	// le classement, et l'ordre a l'interieur doit rester stable.
	//
	// Un seul regroupement ici, par statut : repartir par projet les tickets d'un
	// projet donnerait une colonne unique.
	ListTicketsBoardByProject(ctx context.Context, arg ListTicketsBoardByProjectParams) ([]ListTicketsBoardByProjectRow, error)
	// Les tickets d'un projet, pour l'onglet « Tickets » de sa fiche.
	//
	// `project_id` y est la clause que `assignee_id` est au tableau personnel : on
	// lit la fiche d'un projet, pas une liste qu'on filtrerait ensuite. L'assigne
	// n'est donc plus une clause mais une colonne — la question qu'on se pose
	// devant un projet est « qui a quoi », quand devant son propre tableau elle ne
	// se pose pas.
	// Page de l'onglet, du plus recemment mis a jour au plus ancien, comme le
	// tableau personnel. tickets_project_idx porte les deux colonnes dans cet
	// ordre : la premiere page se lit sans tri.
	ListTicketsByProject(ctx context.Context, arg ListTicketsByProjectParams) ([]ListTicketsByProjectRow, error)
	// Temps passe.
	//
	// Chaque requete porte `user_id` en clause et non en filtre : on saisit et on
	// relit son propre temps, et l'identifiant vient de la session. Un ecran qui
	// accepterait un parametre laisserait lire le pointage de n'importe qui.
	// Saisies d'une personne sur une plage de jours.
	//
	// L'ecran montre une journee ou une semaine : les deux bornes disent laquelle,
	// et la meme requete sert les deux.
	ListTimeEntries(ctx context.Context, arg ListTimeEntriesParams) ([]ListTimeEntriesRow, error)
	// Pagination cote serveur systematique : jamais de SELECT sans LIMIT.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Verrou avant d'ajouter une version ou de trancher : deux soumissions
	// simultanees prendraient sinon le meme numero.
	LockDeliverable(ctx context.Context, id uuid.UUID) (LockDeliverableRow, error)
	// Prend le verrou d'ecriture sur un ticket, le temps de la transaction.
	//
	// Sans lui, deux ecritures concurrentes lisent toutes deux l'etat d'avant et
	// inscrivent chacune sa ligne au journal : on se retrouve avec deux
	// « renomme de A vers B » pour un seul renommage. Le verrou les met en file,
	// la seconde voit le travail de la premiere et n'a plus rien a journaliser.
	LockTicket(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	LogTaskActivity(ctx context.Context, arg LogTaskActivityParams) error
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	// Le destinataire est dans la clause : sans lui, connaitre un identifiant
	// suffirait a marquer comme lue la notification de quelqu'un d'autre.
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	// Inscrit la tentative, qu'elle ait abouti ou non.
	MarkSidebarAppFaviconAttempted(ctx context.Context, id uuid.UUID) error
	// Deplacement d'une carte du kanban. Distincte de UpdateClient : glisser une
	// carte ne doit pas reecrire les coordonnees de l'entreprise avec ce que
	// l'ecran avait en memoire.
	MoveClientStatus(ctx context.Context, arg MoveClientStatusParams) (Client, error)
	// Deplacement dans le tableau : la colonne, et le rang dans cette colonne.
	// Separe de UpdateTask parce que c'est le seul mouvement qui journalise un
	// changement de statut, et que le tableau l'appelle a chaque glissement.
	MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error)
	// Le numero suivant, sous le verrou pose juste avant.
	NextDeliverableVersionNumero(ctx context.Context, deliverableID uuid.UUID) (int32, error)
	RemoveProjectFavorite(ctx context.Context, arg RemoveProjectFavoriteParams) error
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error
	// Repasse le logo en automatique.
	//
	// Efface le logo courant et rouvre la recuperation : le job exige un logo nul,
	// et ne retente qu'au bout de plusieurs heures. Remettre la date a zero le fait
	// reprendre l'app a son prochain passage, donc dans la minute.
	//
	// La recuperation elle-meme n'a pas sa place ici : elle sort vers un serveur
	// tiers, et aucune requete HTTP de l'application ne doit attendre cela.
	ResetSidebarAppFavicon(ctx context.Context, id uuid.UUID) (ResetSidebarAppFaviconRow, error)
	// Deconnexion de toutes les sessions : rejeu detecte, changement de mot de
	// passe, ou compte desactive.
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	// Idempotent : revoquer deux fois ne change pas la date de la premiere
	// revocation, ce qui garde intacte la trace d'un rejeu.
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	// Question posee par la garde a chaque requete protegee. Les deux jointures
	// portent sur des cles primaires et des index uniques : c'est une lecture
	// indexee, pas un balayage.
	RoleHasPermission(ctx context.Context, arg RoleHasPermissionParams) (bool, error)
	// La version qui vient d'etre soumise devient celle que l'ecran montre.
	SetDeliverableCurrentVersion(ctx context.Context, arg SetDeliverableCurrentVersionParams) error
	// Designe le contact principal. `NULL` le retire.
	//
	// La condition sur `client_id` est une ceinture : la cle etrangere composite
	// refuse deja le contact d'un autre client, mais elle rendrait une erreur de
	// contrainte la ou un zero ligne touchee se traduit en « introuvable ».
	SetPrimaryContact(ctx context.Context, arg SetPrimaryContactParams) error
	// Remplace les services d'un projet par la liste fournie.
	//
	// Effacer puis reinserer plutot que calculer une difference : la liste est
	// courte, et le formulaire envoie toujours l'etat complet qu'il veut voir.
	SetProjectServices(ctx context.Context, projectID uuid.UUID) error
	// Range le favicon recupere.
	//
	// La clause sur `logo_key` protege un depot manuel : si quelqu'un a pose un
	// logo entre la lecture et l'ecriture, la recuperation ne l'ecrase pas.
	SetSidebarAppFavicon(ctx context.Context, arg SetSidebarAppFaviconParams) error
	// L'appelant lit l'app avant d'appeler : c'est lui qui connait l'ancienne cle
	// et qui efface le fichier qu'elle designait, sans quoi le magasin garderait
	// tous les logos jamais deposes.
	SetSidebarAppLogo(ctx context.Context, arg SetSidebarAppLogoParams) (SetSidebarAppLogoRow, error)
	// Vrai quand la cle designe encore le logo d'une app vivante : c'est ce qui
	// autorise a servir le fichier.
	SidebarAppLogoKeyInUse(ctx context.Context, logoKey *string) (bool, error)
	// Suppression logique, comme partout ailleurs : un client efface par erreur
	// doit pouvoir revenir. La designation du contact principal est retiree par la
	// meme occasion, sans quoi elle pointerait depuis une ligne morte.
	SoftDeleteClient(ctx context.Context, id uuid.UUID) error
	SoftDeleteContact(ctx context.Context, id uuid.UUID) error
	// Les contacts d'un client efface le sont avec lui : ils n'existaient que pour
	// lui. La suppression est logique, comme celle du client, et se defait donc de
	// la meme facon.
	SoftDeleteContactsOfClient(ctx context.Context, clientID *uuid.UUID) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteTask(ctx context.Context, id uuid.UUID) error
	SoftDeleteTaskComment(ctx context.Context, arg SoftDeleteTaskCommentParams) error
	// Total de la plage, en minutes. Calcule par la base plutot qu'en additionnant
	// les lignes rendues : la liste est bornee, le total ne doit pas l'etre.
	SumTimeEntries(ctx context.Context, arg SumTimeEntriesParams) (int64, error)
	// Total par jour de la plage, pour la barre de la semaine.
	SumTimeEntriesByDay(ctx context.Context, arg SumTimeEntriesByDayParams) ([]SumTimeEntriesByDayRow, error)
	// Detail des saisies, la plus recente en tete. Sert la liste paginee et
	// l'export, qui la parcourt avec une borne haute.
	TimeReportEntries(ctx context.Context, arg TimeReportEntriesParams) ([]TimeReportEntriesRow, error)
	// Temps regroupe par projet, personne, service ou client, le plus gros poste
	// en tete. Une seule requete pour les quatre axes : la cle et le libelle se
	// choisissent par CASE, le reste est commun.
	//
	// La cle est du texte et non un uuid : le temps sans service se regroupe sous
	// une cle vide, qu'un uuid ne saurait pas porter.
	// Sans filtre de suppression : le temps d'un compte parti reste du temps passe.
	TimeReportGroups(ctx context.Context, arg TimeReportGroupsParams) ([]TimeReportGroupsRow, error)
	// Temps par tranche (jour, semaine ou mois), pour le graphique d'evolution.
	// Les tranches vides n'y figurent pas : c'est le service qui connait la
	// periode et les complete.
	TimeReportSeries(ctx context.Context, arg TimeReportSeriesParams) ([]TimeReportSeriesRow, error)
	// Rapports de temps.
	//
	// Contrairement a l'ecran « Saisie », ces requetes lisent le temps de toute
	// l'equipe : c'est la permission `time.read` qui en decide, pas la session.
	//
	// Les sommes se font au rendu, en exception assumee a la regle des agregats
	// precalcules : un rapport porte sur une periode et des filtres choisis a la
	// volee, qu'aucun cumul stocke ne peut anticiper. Elles restent bornees — la
	// periode ne depasse pas un an, et l'index (spent_on) la parcourt seul. Un
	// cumul quotidien ne ferait rien gagner : une saisie est deja une ligne par
	// personne, projet et jour.
	//
	// Une heure est facturable quand son projet n'est pas interne. Le caractere
	// se lit sur le projet a la lecture, jamais stocke sur la saisie.
	//
	// Chaque requete repete le meme bloc de filtres : sqlc n'a pas de fragment
	// reutilisable, et un filtre oublie dans une seule d'entre elles ferait
	// mentir le total ou le detail.
	TimeReportTotals(ctx context.Context, arg TimeReportTotalsParams) (TimeReportTotalsRow, error)
	TouchDeliverable(ctx context.Context, id uuid.UUID) error
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
	UnassignTask(ctx context.Context, arg UnassignTaskParams) error
	// Modification de la fiche. Les compteurs n'y sont pas — ils sont tenus par
	// declencheur — ni le contact principal, qui a sa propre route parce que la
	// cle etrangere composite impose un ordre.
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	// Modification de l'identite. Le rattachement a un client n'est pas ici : il
	// passe par la designation du contact principal, qui sait tenir la cle
	// etrangere composite dans le bon ordre.
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	// Mise a jour partielle : chaque champ absent de la requete garde sa valeur.
	// COALESCE sur un parametre nullable dit exactement cela, et evite d'ecrire
	// une requete par champ modifiable.
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	// Les trois champs partent ensemble : le formulaire les montre tous, et une
	// mise a jour partielle demanderait de distinguer « vide » de « inchange ».
	UpdateService(ctx context.Context, arg UpdateServiceParams) (UpdateServiceRow, error)
	UpdateSidebarApp(ctx context.Context, arg UpdateSidebarAppParams) (UpdateSidebarAppRow, error)
	UpdateSubtask(ctx context.Context, arg UpdateSubtaskParams) (Subtask, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	// Applique les changements qu'une entree du registre porte.
	//
	// Un `coalesce` par champ : ce qui n'est pas demande garde sa valeur, ce qui
	// evite de relire puis reecrire les deux autres colonnes a chaque fois.
	//
	// L'assigne a son propre drapeau parce que NULL y est une valeur qui veut dire
	// quelque chose — « remettre a prendre ». Sans lui, on ne saurait pas
	// distinguer « ne touche pas a l'assignation » de « retire-la ».
	//
	// Ne rend rien : le service relit la fiche dans la meme transaction pour
	// comparer l'avant et l'apres, et en tirer les lignes du journal.
	UpdateTicketFields(ctx context.Context, arg UpdateTicketFieldsParams) error
	// Renomme un ticket. Le numero, lui, ne bouge jamais.
	UpdateTicketSubject(ctx context.Context, arg UpdateTicketSubjectParams) error
	// La clause sur `user_id` fait le controle d'acces : une saisie qui n'est pas
	// la sienne ne correspond a aucune ligne, et l'appelant lit un 404.
	UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) (uuid.UUID, error)
	// La photo se retire en passant NULL, d'ou un parametre nullable plutot qu'un
	// COALESCE : « absent » et « efface » doivent se distinguer.
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error)
	// L'empreinte est calculee par l'appelant : la base ne voit jamais le mot de
	// passe en clair.
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Mise a jour partielle du compte par son titulaire.
	//
	// Ni le role ni l'etat du compte n'y figurent : ce sont des droits, ils se
	// changent depuis l'administration des comptes, pas depuis ses propres
	// reglages.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
