// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time_timers.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const deleteTimer = `-- name: DeleteTimer :execrows
DELETE FROM time_timers WHERE user_id = $1
`

func (q *Queries) DeleteTimer(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTimer, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTimer = `-- name: GetTimer :one
SELECT
    tm.user_id, tm.project_id, tm.task_id, tm.note, tm.started_at,
    p.name  AS project_name,
    t.title AS task_title
FROM time_timers tm
JOIN projects p ON p.id = tm.project_id
LEFT JOIN tasks t ON t.id = tm.task_id AND t.deleted_at IS NULL
WHERE tm.user_id = $1
`

type GetTimerRow struct {
	UserID      uuid.UUID  `json:"user_id"`
	ProjectID   uuid.UUID  `json:"project_id"`
	TaskID      *uuid.UUID `json:"task_id"`
	Note        string     `json:"note"`
	StartedAt   time.Time  `json:"started_at"`
	ProjectName string     `json:"project_name"`
	TaskTitle   *string    `json:"task_title"`
}

// Le chrono d'une personne, avec de quoi le nommer a l'ecran.
func (q *Queries) GetTimer(ctx context.Context, userID uuid.UUID) (GetTimerRow, error) {
	row := q.db.QueryRow(ctx, getTimer, userID)
	var i GetTimerRow
	err := row.Scan(
		&i.UserID,
		&i.ProjectID,
		&i.TaskID,
		&i.Note,
		&i.StartedAt,
		&i.ProjectName,
		&i.TaskTitle,
	)
	return i, err
}

const startTimer = `-- name: StartTimer :exec
INSERT INTO time_timers (user_id, project_id, task_id, note)
VALUES ($1, $2, $3::uuid, $4)
`

type StartTimerParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	ProjectID uuid.UUID  `json:"project_id"`
	TaskID    *uuid.UUID `json:"task_id"`
	Note      string     `json:"note"`
}

// Un chrono qui tourne deja fait echouer l'insertion : c'est a l'appelant de
// l'arreter d'abord, et de choisir ce qu'il en fait.
func (q *Queries) StartTimer(ctx context.Context, arg StartTimerParams) error {
	_, err := q.db.Exec(ctx, startTimer,
		arg.UserID,
		arg.ProjectID,
		arg.TaskID,
		arg.Note,
	)
	return err
}
