// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updates.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const abandonStaleUpdateRequests = `-- name: AbandonStaleUpdateRequests :exec
UPDATE app_update_requests
SET status = 'failed', error = 'Interrompue : l''updater a redémarré pendant la mise à jour', finished_at = now()
WHERE status = 'running'
`

// Au demarrage de l'updater : une demande restee « en cours » vient d'un
// updater interrompu en pleine mise a jour. Elle est close en echec plutot que
// de bloquer toute nouvelle demande.
func (q *Queries) AbandonStaleUpdateRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, abandonStaleUpdateRequests)
	return err
}

const createUpdateRequest = `-- name: CreateUpdateRequest :one
INSERT INTO app_update_requests (requested_by, from_version, target_version)
VALUES ($1, $2, $3)
RETURNING id, requested_by, from_version, target_version, status, step, error, created_at, started_at, finished_at
`

type CreateUpdateRequestParams struct {
	RequestedBy   *uuid.UUID `json:"requested_by"`
	FromVersion   string     `json:"from_version"`
	TargetVersion string     `json:"target_version"`
}

func (q *Queries) CreateUpdateRequest(ctx context.Context, arg CreateUpdateRequestParams) (AppUpdateRequest, error) {
	row := q.db.QueryRow(ctx, createUpdateRequest, arg.RequestedBy, arg.FromVersion, arg.TargetVersion)
	var i AppUpdateRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.FromVersion,
		&i.TargetVersion,
		&i.Status,
		&i.Step,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishUpdateRequest = `-- name: FinishUpdateRequest :exec
UPDATE app_update_requests
SET status = $2, error = $3, finished_at = now()
WHERE id = $1
`

type FinishUpdateRequestParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  string    `json:"error"`
}

func (q *Queries) FinishUpdateRequest(ctx context.Context, arg FinishUpdateRequestParams) error {
	_, err := q.db.Exec(ctx, finishUpdateRequest, arg.ID, arg.Status, arg.Error)
	return err
}

const getLatestUpdateRequest = `-- name: GetLatestUpdateRequest :one
SELECT r.id, r.requested_by, r.from_version, r.target_version, r.status, r.step, r.error, r.created_at, r.started_at, r.finished_at, coalesce(btrim(u.firstname || ' ' || u.lastname), '')::text AS requested_by_name
FROM app_update_requests r
LEFT JOIN users u ON u.id = r.requested_by
ORDER BY r.created_at DESC
LIMIT 1
`

type GetLatestUpdateRequestRow struct {
	ID              uuid.UUID  `json:"id"`
	RequestedBy     *uuid.UUID `json:"requested_by"`
	FromVersion     string     `json:"from_version"`
	TargetVersion   string     `json:"target_version"`
	Status          string     `json:"status"`
	Step            string     `json:"step"`
	Error           string     `json:"error"`
	CreatedAt       time.Time  `json:"created_at"`
	StartedAt       *time.Time `json:"started_at"`
	FinishedAt      *time.Time `json:"finished_at"`
	RequestedByName string     `json:"requested_by_name"`
}

// Derniere demande, pour l'etat affiche a l'ecran.
func (q *Queries) GetLatestUpdateRequest(ctx context.Context) (GetLatestUpdateRequestRow, error) {
	row := q.db.QueryRow(ctx, getLatestUpdateRequest)
	var i GetLatestUpdateRequestRow
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.FromVersion,
		&i.TargetVersion,
		&i.Status,
		&i.Step,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RequestedByName,
	)
	return i, err
}

const getReleaseCheck = `-- name: GetReleaseCheck :one
SELECT id, version, name, url, published_at, checked_at, error FROM app_release_check WHERE id
`

func (q *Queries) GetReleaseCheck(ctx context.Context) (AppReleaseCheck, error) {
	row := q.db.QueryRow(ctx, getReleaseCheck)
	var i AppReleaseCheck
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Url,
		&i.PublishedAt,
		&i.CheckedAt,
		&i.Error,
	)
	return i, err
}

const getUpdater = `-- name: GetUpdater :one
SELECT id, version, target, error, last_seen FROM app_updater WHERE id
`

func (q *Queries) GetUpdater(ctx context.Context) (AppUpdater, error) {
	row := q.db.QueryRow(ctx, getUpdater)
	var i AppUpdater
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Target,
		&i.Error,
		&i.LastSeen,
	)
	return i, err
}

const saveReleaseCheck = `-- name: SaveReleaseCheck :exec
INSERT INTO app_release_check (id, version, name, url, published_at, checked_at, error)
VALUES (true, $1, $2, $3, $4, now(), '')
ON CONFLICT (id) DO UPDATE SET
    version      = EXCLUDED.version,
    name         = EXCLUDED.name,
    url          = EXCLUDED.url,
    published_at = EXCLUDED.published_at,
    checked_at   = now(),
    error        = ''
`

type SaveReleaseCheckParams struct {
	Version     string     `json:"version"`
	Name        string     `json:"name"`
	Url         string     `json:"url"`
	PublishedAt *time.Time `json:"published_at"`
}

// Resultat d'un passage reussi : la version vue remplace la precedente.
func (q *Queries) SaveReleaseCheck(ctx context.Context, arg SaveReleaseCheckParams) error {
	_, err := q.db.Exec(ctx, saveReleaseCheck,
		arg.Version,
		arg.Name,
		arg.Url,
		arg.PublishedAt,
	)
	return err
}

const saveReleaseCheckError = `-- name: SaveReleaseCheckError :exec
INSERT INTO app_release_check (id, checked_at, error)
VALUES (true, now(), $1)
ON CONFLICT (id) DO UPDATE SET checked_at = now(), error = EXCLUDED.error
`

// Passage rate : on garde la derniere version connue, on note l'erreur.
func (q *Queries) SaveReleaseCheckError(ctx context.Context, error string) error {
	_, err := q.db.Exec(ctx, saveReleaseCheckError, error)
	return err
}

const saveUpdaterHeartbeat = `-- name: SaveUpdaterHeartbeat :exec
INSERT INTO app_updater (id, version, target, error, last_seen)
VALUES (true, $1, $2, $3, now())
ON CONFLICT (id) DO UPDATE SET
    version   = EXCLUDED.version,
    target    = EXCLUDED.target,
    error     = EXCLUDED.error,
    last_seen = now()
`

type SaveUpdaterHeartbeatParams struct {
	Version string `json:"version"`
	Target  string `json:"target"`
	Error   string `json:"error"`
}

func (q *Queries) SaveUpdaterHeartbeat(ctx context.Context, arg SaveUpdaterHeartbeatParams) error {
	_, err := q.db.Exec(ctx, saveUpdaterHeartbeat, arg.Version, arg.Target, arg.Error)
	return err
}

const setUpdateRequestStep = `-- name: SetUpdateRequestStep :exec
UPDATE app_update_requests SET step = $2 WHERE id = $1 AND status = 'running'
`

type SetUpdateRequestStepParams struct {
	ID   uuid.UUID `json:"id"`
	Step string    `json:"step"`
}

func (q *Queries) SetUpdateRequestStep(ctx context.Context, arg SetUpdateRequestStepParams) error {
	_, err := q.db.Exec(ctx, setUpdateRequestStep, arg.ID, arg.Step)
	return err
}

const startPendingUpdateRequest = `-- name: StartPendingUpdateRequest :one
UPDATE app_update_requests
SET status = 'running', started_at = now(), step = 'Démarrage'
WHERE id = (
    SELECT id FROM app_update_requests
    WHERE status = 'pending'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, requested_by, from_version, target_version, status, step, error, created_at, started_at, finished_at
`

// L'updater prend la demande en attente et la passe en cours, d'un seul
// geste : une demande n'est jamais executee deux fois.
func (q *Queries) StartPendingUpdateRequest(ctx context.Context) (AppUpdateRequest, error) {
	row := q.db.QueryRow(ctx, startPendingUpdateRequest)
	var i AppUpdateRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.FromVersion,
		&i.TargetVersion,
		&i.Status,
		&i.Step,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
