// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, contact_name, contact_email, contact_role)
VALUES ($1, $2, $3, $4)
RETURNING id, name, contact_name, contact_email, contact_role, created_at, updated_at, deleted_at
`

type CreateClientParams struct {
	Name         string  `json:"name"`
	ContactName  string  `json:"contact_name"`
	ContactEmail *string `json:"contact_email"`
	ContactRole  string  `json:"contact_role"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Name,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactRole,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, contact_name, contact_email, contact_role, created_at, updated_at, deleted_at FROM clients
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getClientByName = `-- name: GetClientByName :one
SELECT id, name, contact_name, contact_email, contact_role, created_at, updated_at, deleted_at FROM clients
WHERE lower(name) = lower($1::text) AND deleted_at IS NULL
`

// Recherche exacte, insensible a la casse : c'est elle qui evite de creer
// « Novaterre » a cote de « novaterre » quand le nom est saisi a la volee.
func (q *Queries) GetClientByName(ctx context.Context, name string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByName, name)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, contact_name, contact_email, contact_role, created_at, updated_at, deleted_at FROM clients
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR name ILIKE '%' || $1::text || '%')
ORDER BY name
LIMIT $3 OFFSET $2
`

type ListClientsParams struct {
	Search     *string `json:"search"`
	PageOffset int32   `json:"page_offset"`
	PageSize   int32   `json:"page_size"`
}

// Sert le champ « Client » du formulaire de projet. Pagine comme le reste,
// meme si une agence en compte quelques dizaines : la regle ne souffre pas
// d'exception, sinon elle finit par etre oubliee la ou elle compte.
func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Search, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactRole,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
