// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const attachContactToClient = `-- name: AttachContactToClient :one
UPDATE contacts
SET client_id = $1,
    updated_at = now()
WHERE id = $2
  AND client_id IS NULL
  AND deleted_at IS NULL
RETURNING id, client_id, firstname, lastname, role, email, phone, created_at, updated_at, deleted_at
`

type AttachContactToClientParams struct {
	ClientID  *uuid.UUID `json:"client_id"`
	ContactID uuid.UUID  `json:"contact_id"`
}

// Rattache un contact libre a un client.
//
// La condition sur `client_id IS NULL` fait de cette requete une prise de
// possession sure : deux clients crees en meme temps avec le meme contact, un
// seul l'obtient, et l'autre ne touche aucune ligne.
func (q *Queries) AttachContactToClient(ctx context.Context, arg AttachContactToClientParams) (Contact, error) {
	row := q.db.QueryRow(ctx, attachContactToClient, arg.ClientID, arg.ContactID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const clearPrimaryContactOf = `-- name: ClearPrimaryContactOf :exec
UPDATE clients
SET primary_contact_id = NULL,
    updated_at = now()
WHERE primary_contact_id = $1
`

// Retire la designation qui pointe vers ce contact, quel que soit le client.
// Appelee avant la suppression logique : la cle etrangere ne se declenche que
// sur un DELETE reel, et laisserait sinon un client designant un contact mort.
func (q *Queries) ClearPrimaryContactOf(ctx context.Context, primaryContactID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryContactOf, primaryContactID)
	return err
}

const countCrmContacts = `-- name: CountCrmContacts :one
SELECT count(*)
FROM contacts ct
LEFT JOIN clients c ON c.id = ct.client_id AND c.deleted_at IS NULL
WHERE ct.deleted_at IS NULL
  AND ($1::uuid IS NULL OR ct.client_id = $1::uuid)
  AND (NOT $2::boolean OR ct.client_id IS NULL)
  AND (
      $3::text IS NULL
      OR (ct.firstname || ' ' || ct.lastname) ILIKE '%' || $3::text || '%'
      OR ct.email ILIKE '%' || $3::text || '%'
      OR c.name ILIKE '%' || $3::text || '%'
  )
`

type CountCrmContactsParams struct {
	ClientID *uuid.UUID `json:"client_id"`
	OnlyFree bool       `json:"only_free"`
	Search   *string    `json:"search"`
}

func (q *Queries) CountCrmContacts(ctx context.Context, arg CountCrmContactsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCrmContacts, arg.ClientID, arg.OnlyFree, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (client_id, firstname, lastname, role, email, phone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, client_id, firstname, lastname, role, email, phone, created_at, updated_at, deleted_at
`

type CreateContactParams struct {
	ClientID  *uuid.UUID `json:"client_id"`
	Firstname string     `json:"firstname"`
	Lastname  string     `json:"lastname"`
	Role      string     `json:"role"`
	Email     *string    `json:"email"`
	Phone     string     `json:"phone"`
}

// `client_id` peut etre nul : le contact est alors libre, en attente d'une
// entreprise.
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.ClientID,
		arg.Firstname,
		arg.Lastname,
		arg.Role,
		arg.Email,
		arg.Phone,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT ct.id, ct.client_id, ct.firstname, ct.lastname, ct.role, ct.email, ct.phone, ct.created_at, ct.updated_at, ct.deleted_at, c.name AS client_name
FROM contacts ct
LEFT JOIN clients c ON c.id = ct.client_id AND c.deleted_at IS NULL
WHERE ct.id = $1 AND ct.deleted_at IS NULL
`

type GetContactRow struct {
	ID         uuid.UUID  `json:"id"`
	ClientID   *uuid.UUID `json:"client_id"`
	Firstname  string     `json:"firstname"`
	Lastname   string     `json:"lastname"`
	Role       string     `json:"role"`
	Email      *string    `json:"email"`
	Phone      string     `json:"phone"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
	ClientName *string    `json:"client_name"`
}

func (q *Queries) GetContact(ctx context.Context, id uuid.UUID) (GetContactRow, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i GetContactRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ClientName,
	)
	return i, err
}

const listContactsOfClient = `-- name: ListContactsOfClient :many
SELECT id, client_id, firstname, lastname, role, email, phone, created_at, updated_at, deleted_at, (client_id IS NULL)::boolean AS is_free
FROM contacts
WHERE deleted_at IS NULL
  AND (client_id = $1 OR client_id IS NULL)
  AND (
      $2::text IS NULL
      OR (firstname || ' ' || lastname) ILIKE '%' || $2::text || '%'
  )
ORDER BY (client_id IS NULL), lastname, firstname, id
LIMIT $3
`

type ListContactsOfClientParams struct {
	ClientID *uuid.UUID `json:"client_id"`
	Search   *string    `json:"search"`
	PageSize int32      `json:"page_size"`
}

type ListContactsOfClientRow struct {
	ID        uuid.UUID  `json:"id"`
	ClientID  *uuid.UUID `json:"client_id"`
	Firstname string     `json:"firstname"`
	Lastname  string     `json:"lastname"`
	Role      string     `json:"role"`
	Email     *string    `json:"email"`
	Phone     string     `json:"phone"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	IsFree    bool       `json:"is_free"`
}

// Alimente le menu deroulant qui designe le contact principal d'un client.
//
// Il propose deux ensembles : les contacts du client, et les contacts libres —
// ces derniers etant rattaches au moment ou on les choisit. Sans eux, un
// contact cree sans entreprise n'aurait aucun moyen d'en rejoindre une.
//
// Les contacts d'un AUTRE client restent exclus : la cle etrangere composite
// les refuserait, et les proposer laisserait croire qu'on peut se les prendre.
// Cast explicite pour sqlc, qui sans lui rend un `interface{}`.
// Les siens d'abord : ce sont eux qu'on cherche le plus souvent.
func (q *Queries) ListContactsOfClient(ctx context.Context, arg ListContactsOfClientParams) ([]ListContactsOfClientRow, error) {
	rows, err := q.db.Query(ctx, listContactsOfClient, arg.ClientID, arg.Search, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsOfClientRow{}
	for rows.Next() {
		var i ListContactsOfClientRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Firstname,
			&i.Lastname,
			&i.Role,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsFree,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrmContacts = `-- name: ListCrmContacts :many
SELECT
    ct.id, ct.client_id, ct.firstname, ct.lastname, ct.role, ct.email, ct.phone, ct.created_at, ct.updated_at, ct.deleted_at,
    c.name AS client_name,
    coalesce(c.primary_contact_id = ct.id, false)::boolean AS is_primary
FROM contacts ct
LEFT JOIN clients c ON c.id = ct.client_id AND c.deleted_at IS NULL
WHERE ct.deleted_at IS NULL
  AND ($1::uuid IS NULL OR ct.client_id = $1::uuid)
  AND (NOT $2::boolean OR ct.client_id IS NULL)
  AND (
      $3::text IS NULL
      OR (ct.firstname || ' ' || ct.lastname) ILIKE '%' || $3::text || '%'
      OR ct.email ILIKE '%' || $3::text || '%'
      OR c.name ILIKE '%' || $3::text || '%'
  )
ORDER BY
    CASE WHEN $4::text = 'name' AND $5::text = 'desc'
         THEN ct.lastname || ' ' || ct.firstname END DESC,
    CASE WHEN $4::text = 'client' AND $5::text = 'asc' THEN c.name END ASC,
    CASE WHEN $4::text = 'client' AND $5::text = 'desc' THEN c.name END DESC,
    CASE WHEN $4::text = 'name' AND $5::text = 'asc'
         THEN ct.lastname || ' ' || ct.firstname END ASC,
    ct.lastname ASC,
    ct.firstname ASC,
    -- Depart d'egalite stable : deux homonymes ne doivent pas changer de place
    -- d'une page a l'autre, sinon l'un des deux disparait.
    ct.id ASC
LIMIT $7 OFFSET $6
`

type ListCrmContactsParams struct {
	ClientID   *uuid.UUID `json:"client_id"`
	OnlyFree   bool       `json:"only_free"`
	Search     *string    `json:"search"`
	Sort       string     `json:"sort"`
	Dir        string     `json:"dir"`
	PageOffset int32      `json:"page_offset"`
	PageSize   int32      `json:"page_size"`
}

type ListCrmContactsRow struct {
	ID         uuid.UUID  `json:"id"`
	ClientID   *uuid.UUID `json:"client_id"`
	Firstname  string     `json:"firstname"`
	Lastname   string     `json:"lastname"`
	Role       string     `json:"role"`
	Email      *string    `json:"email"`
	Phone      string     `json:"phone"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
	ClientName *string    `json:"client_name"`
	IsPrimary  bool       `json:"is_primary"`
}

// Liste paginee de l'ecran « Contacts ».
//
// Jointure a gauche : un contact libre n'a pas encore d'entreprise, et doit
// rester visible — c'est meme la seule liste ou on le retrouve.
//
// `is_primary` dit si la personne est l'interlocuteur principal de son client.
// `coalesce` et non la seule egalite : chez un client qui n'a designe
// personne, `primary_contact_id` est NULL et la comparaison rendrait NULL —
// que le scan Go refuserait dans un booleen. Le cast explicite est la pour
// sqlc, qui sans lui rend un `interface{}`.
func (q *Queries) ListCrmContacts(ctx context.Context, arg ListCrmContactsParams) ([]ListCrmContactsRow, error) {
	rows, err := q.db.Query(ctx, listCrmContacts,
		arg.ClientID,
		arg.OnlyFree,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCrmContactsRow{}
	for rows.Next() {
		var i ListCrmContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Firstname,
			&i.Lastname,
			&i.Role,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ClientName,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFreeContacts = `-- name: ListFreeContacts :many
SELECT id, client_id, firstname, lastname, role, email, phone, created_at, updated_at, deleted_at FROM contacts
WHERE client_id IS NULL
  AND deleted_at IS NULL
  AND (
      $1::text IS NULL
      OR (firstname || ' ' || lastname) ILIKE '%' || $1::text || '%'
  )
ORDER BY lastname, firstname, id
LIMIT $2
`

type ListFreeContactsParams struct {
	Search   *string `json:"search"`
	PageSize int32   `json:"page_size"`
}

// Contacts sans entreprise, tels que le formulaire de creation d'un client les
// propose. Un contact deja rattache n'y figure pas : il appartient a un autre
// client, et le nouveau ne peut pas le lui prendre.
func (q *Queries) ListFreeContacts(ctx context.Context, arg ListFreeContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listFreeContacts, arg.Search, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Firstname,
			&i.Lastname,
			&i.Role,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryContact = `-- name: SetPrimaryContact :exec
UPDATE clients
SET primary_contact_id = $1,
    updated_at = now()
WHERE clients.id = $2
  AND clients.deleted_at IS NULL
  AND (
      $1::uuid IS NULL
      OR EXISTS (
          SELECT 1 FROM contacts ct
          WHERE ct.id = $1::uuid
            AND ct.client_id = $2
            AND ct.deleted_at IS NULL
      )
  )
`

type SetPrimaryContactParams struct {
	ContactID *uuid.UUID `json:"contact_id"`
	ClientID  uuid.UUID  `json:"client_id"`
}

// Designe le contact principal. `NULL` le retire.
//
// La condition sur `client_id` est une ceinture : la cle etrangere composite
// refuse deja le contact d'un autre client, mais elle rendrait une erreur de
// contrainte la ou un zero ligne touchee se traduit en « introuvable ».
func (q *Queries) SetPrimaryContact(ctx context.Context, arg SetPrimaryContactParams) error {
	_, err := q.db.Exec(ctx, setPrimaryContact, arg.ContactID, arg.ClientID)
	return err
}

const softDeleteContact = `-- name: SoftDeleteContact :exec
UPDATE contacts
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteContact(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteContact, id)
	return err
}

const softDeleteContactsOfClient = `-- name: SoftDeleteContactsOfClient :exec
UPDATE contacts
SET deleted_at = now(),
    updated_at = now()
WHERE client_id = $1 AND deleted_at IS NULL
`

// Les contacts d'un client efface le sont avec lui : ils n'existaient que pour
// lui. La suppression est logique, comme celle du client, et se defait donc de
// la meme facon.
func (q *Queries) SoftDeleteContactsOfClient(ctx context.Context, clientID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteContactsOfClient, clientID)
	return err
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET firstname = $1,
    lastname  = $2,
    role      = $3,
    email     = $4,
    phone     = $5,
    updated_at = now()
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, client_id, firstname, lastname, role, email, phone, created_at, updated_at, deleted_at
`

type UpdateContactParams struct {
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Role      string    `json:"role"`
	Email     *string   `json:"email"`
	Phone     string    `json:"phone"`
	ID        uuid.UUID `json:"id"`
}

// Modification de l'identite. Le rattachement a un client n'est pas ici : il
// passe par la designation du contact principal, qui sait tenir la cle
// etrangere composite dans le bon ordre.
func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.Firstname,
		arg.Lastname,
		arg.Role,
		arg.Email,
		arg.Phone,
		arg.ID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
