// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Permission struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash []byte      `json:"token_hash"`
	UserAgent string      `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
	ExpiresAt time.Time   `json:"expires_at"`
	RevokedAt *time.Time  `json:"revoked_at"`
	CreatedAt time.Time   `json:"created_at"`
}

type Role struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Label     string    `json:"label"`
	IsSystem  bool      `json:"is_system"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	Firstname    string     `json:"firstname"`
	Lastname     string     `json:"lastname"`
	Role         string     `json:"role"`
	AvatarUrl    *string    `json:"avatar_url"`
	TotpSecret   *string    `json:"totp_secret"`
	LastLoginAt  *time.Time `json:"last_login_at"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}
