// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects p
WHERE p.deleted_at IS NULL
  AND ($1::text IS NULL OR p.status = $1::text)
  AND ($2::uuid IS NULL OR p.client_id = $2::uuid)
  AND ($3::text IS NULL OR p.name ILIKE '%' || $3::text || '%')
`

type CountProjectsParams struct {
	Status   *string    `json:"status"`
	ClientID *uuid.UUID `json:"client_id"`
	Search   *string    `json:"search"`
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, arg.Status, arg.ClientID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (client_id, name, status, progress, hours_sold, starts_on, due_on, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, client_id, name, status, progress, hours_sold, hours_spent, starts_on, due_on, tasks_total, tasks_done, created_by, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	ClientID  uuid.UUID  `json:"client_id"`
	Name      string     `json:"name"`
	Status    string     `json:"status"`
	Progress  int16      `json:"progress"`
	HoursSold float64    `json:"hours_sold"`
	StartsOn  *time.Time `json:"starts_on"`
	DueOn     *time.Time `json:"due_on"`
	CreatedBy *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ClientID,
		arg.Name,
		arg.Status,
		arg.Progress,
		arg.HoursSold,
		arg.StartsOn,
		arg.DueOn,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Status,
		&i.Progress,
		&i.HoursSold,
		&i.HoursSpent,
		&i.StartsOn,
		&i.DueOn,
		&i.TasksTotal,
		&i.TasksDone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT count(*) FROM projects WHERE deleted_at IS NULL)                       AS projects_total,
    (SELECT count(*) FROM projects
     WHERE deleted_at IS NULL AND created_at >= now() - interval '30 days')        AS projects_recent,
    (SELECT count(*) FROM projects
     WHERE deleted_at IS NULL
       AND created_at >= now() - interval '60 days'
       AND created_at <  now() - interval '30 days')                               AS projects_previous,

    (SELECT count(*) FROM clients WHERE deleted_at IS NULL)                        AS clients_total,
    (SELECT count(*) FROM clients
     WHERE deleted_at IS NULL AND created_at >= now() - interval '30 days')        AS clients_recent,
    (SELECT count(*) FROM clients
     WHERE deleted_at IS NULL
       AND created_at >= now() - interval '60 days'
       AND created_at <  now() - interval '30 days')                               AS clients_previous,

    (SELECT coalesce(sum(hours_sold), 0)::numeric FROM projects WHERE deleted_at IS NULL) AS hours_total,
    (SELECT coalesce(sum(hours_sold), 0)::numeric FROM projects
     WHERE deleted_at IS NULL AND created_at >= now() - interval '30 days')        AS hours_recent,
    (SELECT coalesce(sum(hours_sold), 0)::numeric FROM projects
     WHERE deleted_at IS NULL
       AND created_at >= now() - interval '60 days'
       AND created_at <  now() - interval '30 days')                               AS hours_previous
`

type GetDashboardStatsRow struct {
	ProjectsTotal    int64   `json:"projects_total"`
	ProjectsRecent   int64   `json:"projects_recent"`
	ProjectsPrevious int64   `json:"projects_previous"`
	ClientsTotal     int64   `json:"clients_total"`
	ClientsRecent    int64   `json:"clients_recent"`
	ClientsPrevious  int64   `json:"clients_previous"`
	HoursTotal       float64 `json:"hours_total"`
	HoursRecent      float64 `json:"hours_recent"`
	HoursPrevious    float64 `json:"hours_previous"`
}

// Chiffres d'en-tete du tableau de bord.
//
// Une seule requete pour les trois tuiles, comparaison comprise : chaque
// chiffre est donne sur les trente derniers jours et sur les trente qui
// precedent, ce qui permet d'afficher une variation sans stocker d'historique.
//
// Ce sont des COUNT au rendu, contrairement a la regle du projet — ils sont
// admis ici parce qu'ils portent sur deux tables bornees (les projets et les
// clients d'une agence, quelques centaines de lignes) et qu'ils passent par
// les index partiels `deleted_at IS NULL`. Le jour ou ces tables grossissent,
// c'est un instantane quotidien qu'il faudra stocker, pas un index de plus.
func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.ProjectsTotal,
		&i.ProjectsRecent,
		&i.ProjectsPrevious,
		&i.ClientsTotal,
		&i.ClientsRecent,
		&i.ClientsPrevious,
		&i.HoursTotal,
		&i.HoursRecent,
		&i.HoursPrevious,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT
    p.id, p.client_id, p.name, p.status, p.progress, p.hours_sold, p.hours_spent, p.starts_on, p.due_on, p.tasks_total, p.tasks_done, p.created_by, p.created_at, p.updated_at, p.deleted_at,
    c.name          AS client_name,
    c.contact_name  AS client_contact_name,
    c.contact_role  AS client_contact_role,
    c.contact_email AS client_contact_email
FROM projects p
JOIN clients c ON c.id = p.client_id
WHERE p.id = $1 AND p.deleted_at IS NULL
`

type GetProjectRow struct {
	ID                 uuid.UUID  `json:"id"`
	ClientID           uuid.UUID  `json:"client_id"`
	Name               string     `json:"name"`
	Status             string     `json:"status"`
	Progress           int16      `json:"progress"`
	HoursSold          float64    `json:"hours_sold"`
	HoursSpent         float64    `json:"hours_spent"`
	StartsOn           *time.Time `json:"starts_on"`
	DueOn              *time.Time `json:"due_on"`
	TasksTotal         int32      `json:"tasks_total"`
	TasksDone          int32      `json:"tasks_done"`
	CreatedBy          *uuid.UUID `json:"created_by"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
	DeletedAt          *time.Time `json:"deleted_at"`
	ClientName         string     `json:"client_name"`
	ClientContactName  string     `json:"client_contact_name"`
	ClientContactRole  string     `json:"client_contact_role"`
	ClientContactEmail *string    `json:"client_contact_email"`
}

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Status,
		&i.Progress,
		&i.HoursSold,
		&i.HoursSpent,
		&i.StartsOn,
		&i.DueOn,
		&i.TasksTotal,
		&i.TasksDone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ClientName,
		&i.ClientContactName,
		&i.ClientContactRole,
		&i.ClientContactEmail,
	)
	return i, err
}

const listMembersOfProjects = `-- name: ListMembersOfProjects :many
SELECT
    pm.project_id,
    u.id,
    u.firstname,
    u.lastname,
    u.avatar_url
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = ANY($1::uuid[])
  AND u.deleted_at IS NULL
ORDER BY pm.project_id, u.firstname, u.lastname
`

type ListMembersOfProjectsRow struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	AvatarUrl *string   `json:"avatar_url"`
}

// Equipes de plusieurs projets en une requete.
//
// C'est la parade au N+1 de la liste : le handler passe les identifiants de la
// page entiere et repartit les lignes ensuite. Une requete par projet aurait
// fait vingt allers-retours pour afficher vingt lignes.
func (q *Queries) ListMembersOfProjects(ctx context.Context, projectIds []uuid.UUID) ([]ListMembersOfProjectsRow, error) {
	rows, err := q.db.Query(ctx, listMembersOfProjects, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersOfProjectsRow{}
	for rows.Next() {
		var i ListMembersOfProjectsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id, p.client_id, p.name, p.status, p.progress, p.hours_sold, p.hours_spent, p.starts_on, p.due_on, p.tasks_total, p.tasks_done, p.created_by, p.created_at, p.updated_at, p.deleted_at,
    c.name AS client_name
FROM projects p
JOIN clients c ON c.id = p.client_id
WHERE p.deleted_at IS NULL
  AND ($1::text IS NULL OR p.status = $1::text)
  AND ($2::uuid IS NULL OR p.client_id = $2::uuid)
  AND ($3::text IS NULL OR p.name ILIKE '%' || $3::text || '%')
ORDER BY
    -- Un seul ORDER BY parametre plutot que quatre requetes : le tri vient de
    -- l'ecran, et les colonnes possibles sont closes par le handler.
    CASE WHEN $4::text = 'name' AND $5::text = 'asc' THEN p.name END ASC,
    CASE WHEN $4::text = 'name' AND $5::text = 'desc' THEN p.name END DESC,
    CASE WHEN $4::text = 'progress' AND $5::text = 'asc' THEN p.progress END ASC,
    CASE WHEN $4::text = 'progress' AND $5::text = 'desc' THEN p.progress END DESC,
    CASE WHEN $4::text = 'budget' AND $5::text = 'asc' THEN p.hours_spent END ASC,
    CASE WHEN $4::text = 'budget' AND $5::text = 'desc' THEN p.hours_spent END DESC,
    CASE WHEN $5::text = 'desc' THEN p.due_on END DESC NULLS LAST,
    p.due_on ASC NULLS LAST,
    -- Depart d'egalite stable : sans lui, deux projets de meme echeance
    -- peuvent changer de place d'une page a l'autre et l'un des deux disparait.
    p.id ASC
LIMIT $7 OFFSET $6
`

type ListProjectsParams struct {
	Status     *string    `json:"status"`
	ClientID   *uuid.UUID `json:"client_id"`
	Search     *string    `json:"search"`
	Sort       string     `json:"sort"`
	Dir        string     `json:"dir"`
	PageOffset int32      `json:"page_offset"`
	PageSize   int32      `json:"page_size"`
}

type ListProjectsRow struct {
	ID         uuid.UUID  `json:"id"`
	ClientID   uuid.UUID  `json:"client_id"`
	Name       string     `json:"name"`
	Status     string     `json:"status"`
	Progress   int16      `json:"progress"`
	HoursSold  float64    `json:"hours_sold"`
	HoursSpent float64    `json:"hours_spent"`
	StartsOn   *time.Time `json:"starts_on"`
	DueOn      *time.Time `json:"due_on"`
	TasksTotal int32      `json:"tasks_total"`
	TasksDone  int32      `json:"tasks_done"`
	CreatedBy  *uuid.UUID `json:"created_by"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
	ClientName string     `json:"client_name"`
}

// Liste paginee du back-office.
//
// Le nom du client est joint ici plutot que ramene par une seconde requete :
// c'est une valeur scalaire par ligne, la jointure ne multiplie rien. L'equipe,
// elle, est une collection : elle passe par ListMembersOfProjects, qui charge
// d'un coup les membres de toute la page.
//
// Les compteurs de taches sont lus tels quels : ce sont des colonnes tenues par
// declencheur, aucun COUNT n'est fait au rendu.
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.Status,
		arg.ClientID,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Status,
			&i.Progress,
			&i.HoursSold,
			&i.HoursSpent,
			&i.StartsOn,
			&i.DueOn,
			&i.TasksTotal,
			&i.TasksDone,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name       = COALESCE($1::text, name),
    status     = COALESCE($2::text, status),
    progress   = COALESCE($3::smallint, progress),
    hours_sold = COALESCE($4::numeric, hours_sold),
    client_id  = COALESCE($5::uuid, client_id),
    starts_on  = CASE WHEN $6::boolean THEN NULL
                      ELSE COALESCE($7::date, starts_on) END,
    due_on     = CASE WHEN $8::boolean THEN NULL
                      ELSE COALESCE($9::date, due_on) END,
    updated_at = now()
WHERE id = $10 AND deleted_at IS NULL
RETURNING id, client_id, name, status, progress, hours_sold, hours_spent, starts_on, due_on, tasks_total, tasks_done, created_by, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	Name          *string    `json:"name"`
	Status        *string    `json:"status"`
	Progress      *int16     `json:"progress"`
	HoursSold     *float64   `json:"hours_sold"`
	ClientID      *uuid.UUID `json:"client_id"`
	ClearStartsOn bool       `json:"clear_starts_on"`
	StartsOn      *time.Time `json:"starts_on"`
	ClearDueOn    bool       `json:"clear_due_on"`
	DueOn         *time.Time `json:"due_on"`
	ID            uuid.UUID  `json:"id"`
}

// Mise a jour partielle : chaque champ absent de la requete garde sa valeur.
// COALESCE sur un parametre nullable dit exactement cela, et evite d'ecrire
// une requete par champ modifiable.
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Status,
		arg.Progress,
		arg.HoursSold,
		arg.ClientID,
		arg.ClearStartsOn,
		arg.StartsOn,
		arg.ClearDueOn,
		arg.DueOn,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Status,
		&i.Progress,
		&i.HoursSold,
		&i.HoursSpent,
		&i.StartsOn,
		&i.DueOn,
		&i.TasksTotal,
		&i.TasksDone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
