// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Poser deux fois la meme etoile n'est pas une erreur : c'est un bouton qu'on
	// peut recliquer, pas une creation.
	AddProjectFavorite(ctx context.Context, arg AddProjectFavoriteParams) error
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error
	AssignTask(ctx context.Context, arg AssignTaskParams) error
	// Rattache un contact libre a un client.
	//
	// La condition sur `client_id IS NULL` fait de cette requete une prise de
	// possession sure : deux clients crees en meme temps avec le meme contact, un
	// seul l'obtient, et l'autre ne touche aucune ligne.
	AttachContactToClient(ctx context.Context, arg AttachContactToClientParams) (Contact, error)
	// Une adresse de photo est-elle celle d'un compte ?
	//
	// Le magasin de fichiers est commun aux pieces jointes et aux photos : sans
	// cette verification, l'endpoint des photos servirait n'importe quelle image
	// du magasin a qui en devinerait la cle, court-circuitant les droits du projet
	// qui la porte.
	AvatarURLExists(ctx context.Context, avatarUrl *string) (bool, error)
	// Retire la designation qui pointe vers ce contact, quel que soit le client.
	// Appelee avant la suppression logique : la cle etrangere ne se declenche que
	// sur un DELETE reel, et laisserait sinon un client designant un contact mort.
	ClearPrimaryContactOf(ctx context.Context, primaryContactID *uuid.UUID) error
	CountCrmClients(ctx context.Context, arg CountCrmClientsParams) (int64, error)
	CountCrmContacts(ctx context.Context, arg CountCrmContactsParams) (int64, error)
	CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error)
	// Tous statuts confondus, livres compris : c'est ce qui decide si un client
	// peut disparaitre. Un projet livre garde la trace de qui l'a commande.
	CountProjectsOfClient(ctx context.Context, clientID uuid.UUID) (int64, error)
	CountTasks(ctx context.Context, arg CountTasksParams) (int64, error)
	CountTasksOfProject(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context, role *string) (int64, error)
	// Le client naît sans interlocuteur : ses contacts sont crees ensuite, et la
	// cle etrangere composite exige qu'un contact principal lui appartienne deja.
	CreateClient(ctx context.Context, name string) (Client, error)
	// `client_id` peut etre nul : le contact est alors libre, en attente d'une
	// entreprise.
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectFile(ctx context.Context, arg CreateProjectFileParams) (Attachment, error)
	// Le jeton n'est jamais stocke en clair : seul son empreinte SHA-256 entre en
	// base, si bien qu'une fuite de la table ne permet pas de rejouer une session.
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Subtask, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTaskComment(ctx context.Context, arg CreateTaskCommentParams) (TaskComment, error)
	CreateTaskFile(ctx context.Context, arg CreateTaskFileParams) (Attachment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Rend la ligne supprimee : l'appelant a besoin de sa cle de stockage pour
	// effacer le fichier du disque dans la foulee.
	DeleteAttachment(ctx context.Context, id uuid.UUID) (Attachment, error)
	// Purge des jetons expires depuis assez longtemps pour ne plus rien prouver.
	// Les jetons revoques recents sont conserves : ce sont eux qui permettent de
	// reconnaitre un rejeu.
	DeleteExpiredRefreshTokens(ctx context.Context, retention pgtype.Interval) error
	// Suppression reelle : une sous-tache n'a pas d'histoire propre, et le
	// « Annuler » du rappel la recree telle quelle.
	DeleteSubtask(ctx context.Context, id uuid.UUID) error
	// Une piece jointe se lit par son seul identifiant, quel que soit son
	// proprietaire : c'est ce qui permet a un unique endpoint de telechargement
	// de servir celles des projets comme celles des taches.
	GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error)
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
	// Recherche exacte, insensible a la casse : c'est elle qui evite de creer
	// « Novaterre » a cote de « novaterre » quand le nom est saisi a la volee.
	GetClientByName(ctx context.Context, name string) (Client, error)
	GetContact(ctx context.Context, id uuid.UUID) (GetContactRow, error)
	// Fiche d'un client : son en-tete, avec le contact principal et les compteurs
	// que le tableau montre deja.
	GetCrmClient(ctx context.Context, id uuid.UUID) (GetCrmClientRow, error)
	// Chiffres d'en-tete du tableau de bord.
	//
	// Une seule requete pour les trois tuiles, comparaison comprise : chaque
	// chiffre est donne sur les trente derniers jours et sur les trente qui
	// precedent, ce qui permet d'afficher une variation sans stocker d'historique.
	//
	// Ce sont des COUNT au rendu, contrairement a la regle du projet — ils sont
	// admis ici parce qu'ils portent sur deux tables bornees (les projets et les
	// clients d'une agence, quelques centaines de lignes) et qu'ils passent par
	// les index partiels `deleted_at IS NULL`. Le jour ou ces tables grossissent,
	// c'est un instantane quotidien qu'il faudra stocker, pas un index de plus.
	GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error)
	GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error)
	// Le refresh a besoin du jeton ET de l'etat du compte pour decider. Les lire
	// en une jointure plutot qu'en deux requetes evite qu'un compte supprime entre
	// les deux obtienne un nouvel acces.
	//
	// La ligne est renvoyee meme revoquee ou expiree : c'est l'appelant qui
	// tranche, parce qu'un jeton revoque presente a nouveau signale un rejeu et
	// doit declencher la revocation de toute la famille.
	GetRefreshTokenWithUser(ctx context.Context, tokenHash []byte) (GetRefreshTokenWithUserRow, error)
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	GetSubtask(ctx context.Context, id uuid.UUID) (Subtask, error)
	// Tache et son contexte de projet : le tiroir affiche le nom du projet, et
	// l'aller chercher a part ferait une requete de plus pour un seul mot.
	GetTask(ctx context.Context, id uuid.UUID) (GetTaskRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Affectations de plusieurs taches en une requete : meme parade au N+1 que
	// pour les equipes de projets.
	ListAssigneesOfTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListAssigneesOfTasksRow, error)
	// Sert le champ « Client » du formulaire de projet. Pagine comme le reste,
	// meme si une agence en compte quelques dizaines : la regle ne souffre pas
	// d'exception, sinon elle finit par etre oubliee la ou elle compte.
	//
	// L'interlocuteur affiche est le contact principal, joint a gauche : un client
	// sans contact reste proposable.
	ListClients(ctx context.Context, arg ListClientsParams) ([]ListClientsRow, error)
	// Toutes les cartes du kanban, tous statuts confondus.
	//
	// Bornee et non paginee, comme le tableau des taches : un kanban se lit en
	// entier ou pas du tout. Le handler previent quand la borne est atteinte.
	ListClientsBoard(ctx context.Context, arg ListClientsBoardParams) ([]ListClientsBoardRow, error)
	// Alimente le menu deroulant qui designe le contact principal d'un client.
	//
	// Il propose deux ensembles : les contacts du client, et les contacts libres —
	// ces derniers etant rattaches au moment ou on les choisit. Sans eux, un
	// contact cree sans entreprise n'aurait aucun moyen d'en rejoindre une.
	//
	// Les contacts d'un AUTRE client restent exclus : la cle etrangere composite
	// les refuserait, et les proposer laisserait croire qu'on peut se les prendre.
	// Cast explicite pour sqlc, qui sans lui rend un `interface{}`.
	// Les siens d'abord : ce sont eux qu'on cherche le plus souvent.
	ListContactsOfClient(ctx context.Context, arg ListContactsOfClientParams) ([]ListContactsOfClientRow, error)
	// Liste paginee de l'ecran CRM.
	//
	// Distincte de ListClients, qui sert le champ « Client » d'un formulaire :
	// celle-la remplit un tableau, avec sa recherche, son filtre et son tri. Les
	// confondre reviendrait a faire porter a un menu deroulant les besoins d'un
	// ecran, et inversement.
	//
	// `projects_active` et `portal_users` sont lus tels quels : colonnes tenues
	// par declencheur, aucun COUNT au rendu. `contacts_count` en est un vrai, mais
	// sur un index partiel et pour la seule page affichee.
	ListCrmClients(ctx context.Context, arg ListCrmClientsParams) ([]ListCrmClientsRow, error)
	// Liste paginee de l'ecran « Contacts ».
	//
	// Jointure a gauche : un contact libre n'a pas encore d'entreprise, et doit
	// rester visible — c'est meme la seule liste ou on le retrouve.
	//
	// `is_primary` dit si la personne est l'interlocuteur principal de son client.
	// `coalesce` et non la seule egalite : chez un client qui n'a designe
	// personne, `primary_contact_id` est NULL et la comparaison rendrait NULL —
	// que le scan Go refuserait dans un booleen. Le cast explicite est la pour
	// sqlc, qui sans lui rend un `interface{}`.
	ListCrmContacts(ctx context.Context, arg ListCrmContactsParams) ([]ListCrmContactsRow, error)
	// Projets etoiles par l'appelant, pour les raccourcis de la barre laterale.
	//
	// Bornee en dur : c'est une liste de navigation, pas un ecran. Vingt raccourcis
	// tiennent dans un panneau, au-dela l'etoile ne trie plus rien et c'est la
	// liste des projets qu'il faut ouvrir. La regle du projet veut un LIMIT partout
	// — ici il n'a pas de page suivante, il a une fin.
	ListFavoriteProjects(ctx context.Context, userID uuid.UUID) ([]ListFavoriteProjectsRow, error)
	// Contacts sans entreprise, tels que le formulaire de creation d'un client les
	// propose. Un contact deja rattache n'y figure pas : il appartient a un autre
	// client, et le nouveau ne peut pas le lui prendre.
	ListFreeContacts(ctx context.Context, arg ListFreeContactsParams) ([]Contact, error)
	// Equipes de plusieurs projets en une requete.
	//
	// C'est la parade au N+1 de la liste : le handler passe les identifiants de la
	// page entiere et repartit les lignes ensuite. Une requete par projet aurait
	// fait vingt allers-retours pour afficher vingt lignes.
	ListMembersOfProjects(ctx context.Context, projectIds []uuid.UUID) ([]ListMembersOfProjectsRow, error)
	// Qui prevenir pour un geste pose sur une tache.
	//
	// Les administrateurs suivent tout ce qui se passe ; les personnes affectees a
	// la tache suivent la leur. L'auteur du geste est exclu ici plutot que dans
	// chaque appelant : personne n'a besoin d'etre prevenu de ce qu'il vient de
	// faire, et l'oubli ne se verrait qu'a l'usage.
	ListNotificationRecipients(ctx context.Context, arg ListNotificationRecipientsParams) ([]uuid.UUID, error)
	// Les notifications d'une personne, les plus recentes d'abord.
	//
	// Pagination par curseur et non par offset : la liste s'allonge par le haut,
	// et un OFFSET ferait reapparaitre une ligne deja lue des qu'une notification
	// arrive pendant la lecture.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	// Permissions d'un role, servies telles quelles au front pour qu'il masque les
	// actions inaccessibles. Le front cache des boutons, il ne protege rien : la
	// garde reste la seule autorite.
	ListPermissionsByRole(ctx context.Context, roleCode string) ([]string, error)
	// Comptes de portail rattaches au client. La colonne existe, l'ecran qui la
	// remplit non : la fiche la montre pour que le jour ou on rattachera quelqu'un,
	// ce soit visible.
	ListPortalUsersOfClient(ctx context.Context, arg ListPortalUsersOfClientParams) ([]ListPortalUsersOfClientRow, error)
	// Pieces jointes d'un projet, la derniere deposee en premier.
	ListProjectFiles(ctx context.Context, projectID *uuid.UUID) ([]Attachment, error)
	// Liste paginee du back-office.
	//
	// Le nom du client est joint ici plutot que ramene par une seconde requete :
	// c'est une valeur scalaire par ligne, la jointure ne multiplie rien. L'equipe,
	// elle, est une collection : elle passe par ListMembersOfProjects, qui charge
	// d'un coup les membres de toute la page.
	//
	// Les compteurs de taches sont lus tels quels : ce sont des colonnes tenues par
	// declencheur, aucun COUNT n'est fait au rendu.
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	// Projets du client, tels que sa fiche les liste. Bornee : une fiche montre ce
	// qui se lit d'un coup d'oeil, pas tout l'historique d'un gros compte.
	ListProjectsOfClient(ctx context.Context, arg ListProjectsOfClientParams) ([]ListProjectsOfClientRow, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	ListSubtasks(ctx context.Context, taskID uuid.UUID) ([]Subtask, error)
	ListTaskActivity(ctx context.Context, arg ListTaskActivityParams) ([]ListTaskActivityRow, error)
	ListTaskComments(ctx context.Context, arg ListTaskCommentsParams) ([]ListTaskCommentsRow, error)
	// Pieces jointes de plusieurs taches, pour le tiroir et le tableau.
	ListTaskFiles(ctx context.Context, taskIds []uuid.UUID) ([]Attachment, error)
	// Taches de toute l'agence, pour l'ecran « Taches » du module.
	//
	// Le nom du projet est joint ici : une tache sortie de sa fiche ne dit plus
	// d'ou elle vient, et l'aller chercher ensuite ferait une requete par ligne.
	//
	// Meme borne que le tableau d'un projet, et pour la meme raison : l'ecran a
	// une vue kanban, et on ne tourne pas la page d'un kanban. Le total part a
	// cote pour que la vue puisse dire qu'elle n'affiche pas tout.
	//
	// La jointure sur les projets vivants fait le reste du filtrage : les taches
	// d'un projet supprime ne doivent pas reapparaitre dans une liste globale.
	ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error)
	// Tableau des taches d'un projet.
	//
	// Bornee comme toutes les listes. Un tableau n'a pas de pagination visible —
	// on ne tourne pas la page d'un kanban — mais la borne existe quand meme :
	// c'est elle qui empeche un projet devenu fourre-tout de ramener dix mille
	// lignes. Le handler renvoie le total a cote, pour que l'ecran puisse dire
	// qu'il n'affiche pas tout.
	ListTasksOfProject(ctx context.Context, arg ListTasksOfProjectParams) ([]Task, error)
	// Pagination cote serveur systematique : jamais de SELECT sans LIMIT.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LogTaskActivity(ctx context.Context, arg LogTaskActivityParams) error
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	// Le destinataire est dans la clause : sans lui, connaitre un identifiant
	// suffirait a marquer comme lue la notification de quelqu'un d'autre.
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	// Deplacement d'une carte du kanban. Distincte de UpdateClient : glisser une
	// carte ne doit pas reecrire les coordonnees de l'entreprise avec ce que
	// l'ecran avait en memoire.
	MoveClientStatus(ctx context.Context, arg MoveClientStatusParams) (Client, error)
	// Deplacement dans le tableau : la colonne, et le rang dans cette colonne.
	// Separe de UpdateTask parce que c'est le seul mouvement qui journalise un
	// changement de statut, et que le tableau l'appelle a chaque glissement.
	MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error)
	RemoveProjectFavorite(ctx context.Context, arg RemoveProjectFavoriteParams) error
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error
	// Deconnexion de toutes les sessions : rejeu detecte, changement de mot de
	// passe, ou compte desactive.
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	// Idempotent : revoquer deux fois ne change pas la date de la premiere
	// revocation, ce qui garde intacte la trace d'un rejeu.
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	// Question posee par la garde a chaque requete protegee. Les deux jointures
	// portent sur des cles primaires et des index uniques : c'est une lecture
	// indexee, pas un balayage.
	RoleHasPermission(ctx context.Context, arg RoleHasPermissionParams) (bool, error)
	// Designe le contact principal. `NULL` le retire.
	//
	// La condition sur `client_id` est une ceinture : la cle etrangere composite
	// refuse deja le contact d'un autre client, mais elle rendrait une erreur de
	// contrainte la ou un zero ligne touchee se traduit en « introuvable ».
	SetPrimaryContact(ctx context.Context, arg SetPrimaryContactParams) error
	// Suppression logique, comme partout ailleurs : un client efface par erreur
	// doit pouvoir revenir. La designation du contact principal est retiree par la
	// meme occasion, sans quoi elle pointerait depuis une ligne morte.
	SoftDeleteClient(ctx context.Context, id uuid.UUID) error
	SoftDeleteContact(ctx context.Context, id uuid.UUID) error
	// Les contacts d'un client efface le sont avec lui : ils n'existaient que pour
	// lui. La suppression est logique, comme celle du client, et se defait donc de
	// la meme facon.
	SoftDeleteContactsOfClient(ctx context.Context, clientID *uuid.UUID) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteTask(ctx context.Context, id uuid.UUID) error
	SoftDeleteTaskComment(ctx context.Context, arg SoftDeleteTaskCommentParams) error
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
	UnassignTask(ctx context.Context, arg UnassignTaskParams) error
	// Modification de la fiche. Les compteurs n'y sont pas — ils sont tenus par
	// declencheur — ni le contact principal, qui a sa propre route parce que la
	// cle etrangere composite impose un ordre.
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	// Modification de l'identite. Le rattachement a un client n'est pas ici : il
	// passe par la designation du contact principal, qui sait tenir la cle
	// etrangere composite dans le bon ordre.
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	// Mise a jour partielle : chaque champ absent de la requete garde sa valeur.
	// COALESCE sur un parametre nullable dit exactement cela, et evite d'ecrire
	// une requete par champ modifiable.
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSubtask(ctx context.Context, arg UpdateSubtaskParams) (Subtask, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	// La photo se retire en passant NULL, d'ou un parametre nullable plutot qu'un
	// COALESCE : « absent » et « efface » doivent se distinguer.
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error)
	// L'empreinte est calculee par l'appelant : la base ne voit jamais le mot de
	// passe en clair.
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Mise a jour partielle du compte par son titulaire.
	//
	// Ni le role ni l'etat du compte n'y figurent : ce sont des droits, ils se
	// changent depuis l'administration des comptes, pas depuis ses propres
	// reglages.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
