// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUsers(ctx context.Context, role *string) (int64, error)
	// Le jeton n'est jamais stocke en clair : seul son empreinte SHA-256 entre en
	// base, si bien qu'une fuite de la table ne permet pas de rejouer une session.
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Purge des jetons expires depuis assez longtemps pour ne plus rien prouver.
	// Les jetons revoques recents sont conserves : ce sont eux qui permettent de
	// reconnaitre un rejeu.
	DeleteExpiredRefreshTokens(ctx context.Context, retention pgtype.Interval) error
	// Le refresh a besoin du jeton ET de l'etat du compte pour decider. Les lire
	// en une jointure plutot qu'en deux requetes evite qu'un compte supprime entre
	// les deux obtienne un nouvel acces.
	//
	// La ligne est renvoyee meme revoquee ou expiree : c'est l'appelant qui
	// tranche, parce qu'un jeton revoque presente a nouveau signale un rejeu et
	// doit declencher la revocation de toute la famille.
	GetRefreshTokenWithUser(ctx context.Context, tokenHash []byte) (GetRefreshTokenWithUserRow, error)
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Permissions d'un role, servies telles quelles au front pour qu'il masque les
	// actions inaccessibles. Le front cache des boutons, il ne protege rien : la
	// garde reste la seule autorite.
	ListPermissionsByRole(ctx context.Context, roleCode string) ([]string, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	// Pagination cote serveur systematique : jamais de SELECT sans LIMIT.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Deconnexion de toutes les sessions : rejeu detecte, changement de mot de
	// passe, ou compte desactive.
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	// Idempotent : revoquer deux fois ne change pas la date de la premiere
	// revocation, ce qui garde intacte la trace d'un rejeu.
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	// Question posee par la garde a chaque requete protegee. Les deux jointures
	// portent sur des cles primaires et des index uniques : c'est une lecture
	// indexee, pas un balayage.
	RoleHasPermission(ctx context.Context, arg RoleHasPermissionParams) (bool, error)
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
