// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package db

import (
	"context"
	"net/netip"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, user_agent, ip, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash []byte      `json:"token_hash"`
	UserAgent string      `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
	ExpiresAt time.Time   `json:"expires_at"`
}

// Le jeton n'est jamais stocke en clair : seul son empreinte SHA-256 entre en
// base, si bien qu'une fuite de la table ne permet pas de rejouer une session.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < now() - $1::interval
`

// Purge des jetons expires depuis assez longtemps pour ne plus rien prouver.
// Les jetons revoques recents sont conserves : ce sont eux qui permettent de
// reconnaitre un rejeu.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, retention pgtype.Interval) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, retention)
	return err
}

const getRefreshTokenWithUser = `-- name: GetRefreshTokenWithUser :one
SELECT
    rt.id          AS token_id,
    rt.user_id     AS user_id,
    rt.expires_at  AS expires_at,
    rt.revoked_at  AS revoked_at,
    u.role         AS user_role,
    u.deleted_at   AS user_deleted_at
FROM refresh_tokens rt
JOIN users u ON u.id = rt.user_id
WHERE rt.token_hash = $1
`

type GetRefreshTokenWithUserRow struct {
	TokenID       uuid.UUID  `json:"token_id"`
	UserID        uuid.UUID  `json:"user_id"`
	ExpiresAt     time.Time  `json:"expires_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
	UserRole      string     `json:"user_role"`
	UserDeletedAt *time.Time `json:"user_deleted_at"`
}

// Le refresh a besoin du jeton ET de l'etat du compte pour decider. Les lire
// en une jointure plutot qu'en deux requetes evite qu'un compte supprime entre
// les deux obtienne un nouvel acces.
//
// La ligne est renvoyee meme revoquee ou expiree : c'est l'appelant qui
// tranche, parce qu'un jeton revoque presente a nouveau signale un rejeu et
// doit declencher la revocation de toute la famille.
func (q *Queries) GetRefreshTokenWithUser(ctx context.Context, tokenHash []byte) (GetRefreshTokenWithUserRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenWithUser, tokenHash)
	var i GetRefreshTokenWithUserRow
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserRole,
		&i.UserDeletedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// Deconnexion de toutes les sessions : rejeu detecte, changement de mot de
// passe, ou compte desactive.
func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

// Idempotent : revoquer deux fois ne change pas la date de la premiere
// revocation, ce qui garde intacte la trace d'un rejeu.
func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
