// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const countServices = `-- name: CountServices :one
SELECT count(*)
FROM services
WHERE deleted_at IS NULL
  AND ($1::text IS NULL
       OR name ILIKE '%' || $1::text || '%'
       OR description ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountServices(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countServices, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (name, description, color)
VALUES ($1, $2, $3)
RETURNING id, name, description, color, created_at, updated_at
`

type CreateServiceParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Color       string `json:"color"`
}

type CreateServiceRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Color       string    `json:"color"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (CreateServiceRow, error) {
	row := q.db.QueryRow(ctx, createService, arg.Name, arg.Description, arg.Color)
	var i CreateServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :execrows
UPDATE services
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Suppression douce, comme partout : un service retire d'un referentiel a pu
// etre porte par des donnees passees.
func (q *Queries) DeleteService(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteService, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listServices = `-- name: ListServices :many

SELECT id, name, description, color, created_at, updated_at
FROM services
WHERE deleted_at IS NULL
  AND ($1::text IS NULL
       OR name ILIKE '%' || $1::text || '%'
       OR description ILIKE '%' || $1::text || '%')
ORDER BY name, id
LIMIT $3 OFFSET $2
`

type ListServicesParams struct {
	Search     *string `json:"search"`
	PageOffset int32   `json:"page_offset"`
	PageSize   int32   `json:"page_size"`
}

type ListServicesRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Color       string    `json:"color"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Services : referentiel des prestations de l'agence.
// Page du tableau, par ordre alphabetique.
func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices, arg.Search, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesRow{}
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name        = $1,
    description = $2,
    color       = $3,
    updated_at  = now()
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, name, description, color, created_at, updated_at
`

type UpdateServiceParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Color       string    `json:"color"`
	ID          uuid.UUID `json:"id"`
}

type UpdateServiceRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Color       string    `json:"color"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Les trois champs partent ensemble : le formulaire les montre tous, et une
// mise a jour partielle demanderait de distinguer « vide » de « inchange ».
func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (UpdateServiceRow, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.ID,
	)
	var i UpdateServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
