// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const assignTask = `-- name: AssignTask :exec
INSERT INTO task_assignees (task_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignTaskParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AssignTask(ctx context.Context, arg AssignTaskParams) error {
	_, err := q.db.Exec(ctx, assignTask, arg.TaskID, arg.UserID)
	return err
}

const countTasks = `-- name: CountTasks :one
SELECT count(*)
FROM tasks t
JOIN projects p ON p.id = t.project_id AND p.deleted_at IS NULL
WHERE t.deleted_at IS NULL
  AND ($1::text IS NULL OR t.status = $1::text)
  AND ($2::text IS NULL OR t.priority = $2::text)
  AND ($3::uuid IS NULL OR t.project_id = $3::uuid)
  AND ($4::text IS NULL OR t.title ILIKE '%' || $4::text || '%')
`

type CountTasksParams struct {
	Status    *string    `json:"status"`
	Priority  *string    `json:"priority"`
	ProjectID *uuid.UUID `json:"project_id"`
	Search    *string    `json:"search"`
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks,
		arg.Status,
		arg.Priority,
		arg.ProjectID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksOfProject = `-- name: CountTasksOfProject :one
SELECT count(*) FROM tasks
WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTasksOfProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksOfProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubtask = `-- name: CreateSubtask :one
INSERT INTO subtasks (task_id, label, position)
VALUES (
    $1, $2,
    (SELECT coalesce(max(position), 0) + 1 FROM subtasks WHERE task_id = $1)
)
RETURNING id, task_id, label, done, position, created_at, updated_at
`

type CreateSubtaskParams struct {
	TaskID uuid.UUID `json:"task_id"`
	Label  string    `json:"label"`
}

func (q *Queries) CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Subtask, error) {
	row := q.db.QueryRow(ctx, createSubtask, arg.TaskID, arg.Label)
	var i Subtask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Label,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, status, tag, priority, starts_on, due_on, hours, note, position, created_by)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    -- Rang calcule dans la requete d'insertion : un SELECT max() suivi d'un
    -- INSERT laisserait deux creations simultanees se donner le meme rang.
    (SELECT coalesce(max(position), 0) + 1 FROM tasks
     WHERE project_id = $1 AND status = $4 AND deleted_at IS NULL),
    $11
)
RETURNING id, project_id, title, description, status, tag, starts_on, due_on, hours, note, position, completed_at, created_by, created_at, updated_at, deleted_at, priority, subtasks_total, subtasks_done, comments_count, attachments_count
`

type CreateTaskParams struct {
	ProjectID   uuid.UUID  `json:"project_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Status      string     `json:"status"`
	Tag         string     `json:"tag"`
	Priority    string     `json:"priority"`
	StartsOn    *time.Time `json:"starts_on"`
	DueOn       *time.Time `json:"due_on"`
	Hours       *float64   `json:"hours"`
	Note        string     `json:"note"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Tag,
		arg.Priority,
		arg.StartsOn,
		arg.DueOn,
		arg.Hours,
		arg.Note,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Tag,
		&i.StartsOn,
		&i.DueOn,
		&i.Hours,
		&i.Note,
		&i.Position,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Priority,
		&i.SubtasksTotal,
		&i.SubtasksDone,
		&i.CommentsCount,
		&i.AttachmentsCount,
	)
	return i, err
}

const createTaskComment = `-- name: CreateTaskComment :one
INSERT INTO task_comments (task_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, task_id, author_id, body, created_at, updated_at, deleted_at
`

type CreateTaskCommentParams struct {
	TaskID   uuid.UUID  `json:"task_id"`
	AuthorID *uuid.UUID `json:"author_id"`
	Body     string     `json:"body"`
}

func (q *Queries) CreateTaskComment(ctx context.Context, arg CreateTaskCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, createTaskComment, arg.TaskID, arg.AuthorID, arg.Body)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSubtask = `-- name: DeleteSubtask :exec
DELETE FROM subtasks WHERE id = $1
`

// Suppression reelle : une sous-tache n'a pas d'histoire propre, et le
// « Annuler » du rappel la recree telle quelle.
func (q *Queries) DeleteSubtask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubtask, id)
	return err
}

const getSubtask = `-- name: GetSubtask :one
SELECT id, task_id, label, done, position, created_at, updated_at FROM subtasks WHERE id = $1
`

func (q *Queries) GetSubtask(ctx context.Context, id uuid.UUID) (Subtask, error) {
	row := q.db.QueryRow(ctx, getSubtask, id)
	var i Subtask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Label,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT
    t.id, t.project_id, t.title, t.description, t.status, t.tag, t.starts_on, t.due_on, t.hours, t.note, t.position, t.completed_at, t.created_by, t.created_at, t.updated_at, t.deleted_at, t.priority, t.subtasks_total, t.subtasks_done, t.comments_count, t.attachments_count,
    p.name AS project_name,
    c.name AS client_name
FROM tasks t
JOIN projects p ON p.id = t.project_id
JOIN clients c ON c.id = p.client_id
WHERE t.id = $1 AND t.deleted_at IS NULL
`

type GetTaskRow struct {
	ID               uuid.UUID  `json:"id"`
	ProjectID        uuid.UUID  `json:"project_id"`
	Title            string     `json:"title"`
	Description      string     `json:"description"`
	Status           string     `json:"status"`
	Tag              string     `json:"tag"`
	StartsOn         *time.Time `json:"starts_on"`
	DueOn            *time.Time `json:"due_on"`
	Hours            *float64   `json:"hours"`
	Note             string     `json:"note"`
	Position         int32      `json:"position"`
	CompletedAt      *time.Time `json:"completed_at"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	DeletedAt        *time.Time `json:"deleted_at"`
	Priority         string     `json:"priority"`
	SubtasksTotal    int32      `json:"subtasks_total"`
	SubtasksDone     int32      `json:"subtasks_done"`
	CommentsCount    int32      `json:"comments_count"`
	AttachmentsCount int32      `json:"attachments_count"`
	ProjectName      string     `json:"project_name"`
	ClientName       string     `json:"client_name"`
}

// Tache et son contexte de projet : le tiroir affiche le nom du projet, et
// l'aller chercher a part ferait une requete de plus pour un seul mot.
func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Tag,
		&i.StartsOn,
		&i.DueOn,
		&i.Hours,
		&i.Note,
		&i.Position,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Priority,
		&i.SubtasksTotal,
		&i.SubtasksDone,
		&i.CommentsCount,
		&i.AttachmentsCount,
		&i.ProjectName,
		&i.ClientName,
	)
	return i, err
}

const listAssigneesOfTasks = `-- name: ListAssigneesOfTasks :many
SELECT
    ta.task_id,
    u.id,
    u.firstname,
    u.lastname,
    u.avatar_url
FROM task_assignees ta
JOIN users u ON u.id = ta.user_id
WHERE ta.task_id = ANY($1::uuid[])
  AND u.deleted_at IS NULL
ORDER BY ta.task_id, u.firstname, u.lastname
`

type ListAssigneesOfTasksRow struct {
	TaskID    uuid.UUID `json:"task_id"`
	ID        uuid.UUID `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	AvatarUrl *string   `json:"avatar_url"`
}

// Affectations de plusieurs taches en une requete : meme parade au N+1 que
// pour les equipes de projets.
func (q *Queries) ListAssigneesOfTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListAssigneesOfTasksRow, error) {
	rows, err := q.db.Query(ctx, listAssigneesOfTasks, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssigneesOfTasksRow{}
	for rows.Next() {
		var i ListAssigneesOfTasksRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasks = `-- name: ListSubtasks :many
SELECT id, task_id, label, done, position, created_at, updated_at FROM subtasks
WHERE task_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListSubtasks(ctx context.Context, taskID uuid.UUID) ([]Subtask, error) {
	rows, err := q.db.Query(ctx, listSubtasks, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subtask{}
	for rows.Next() {
		var i Subtask
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Label,
			&i.Done,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskActivity = `-- name: ListTaskActivity :many
SELECT
    ta.id, ta.task_id, ta.actor_id, ta.kind, ta.payload, ta.created_at,
    u.firstname,
    u.lastname,
    u.avatar_url
FROM task_activity ta
LEFT JOIN users u ON u.id = ta.actor_id
WHERE ta.task_id = $1
ORDER BY ta.created_at DESC
LIMIT $2
`

type ListTaskActivityParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	PageSize int32     `json:"page_size"`
}

type ListTaskActivityRow struct {
	ID        uuid.UUID  `json:"id"`
	TaskID    uuid.UUID  `json:"task_id"`
	ActorID   *uuid.UUID `json:"actor_id"`
	Kind      string     `json:"kind"`
	Payload   []byte     `json:"payload"`
	CreatedAt time.Time  `json:"created_at"`
	Firstname *string    `json:"firstname"`
	Lastname  *string    `json:"lastname"`
	AvatarUrl *string    `json:"avatar_url"`
}

func (q *Queries) ListTaskActivity(ctx context.Context, arg ListTaskActivityParams) ([]ListTaskActivityRow, error) {
	rows, err := q.db.Query(ctx, listTaskActivity, arg.TaskID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskActivityRow{}
	for rows.Next() {
		var i ListTaskActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActorID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
			&i.Firstname,
			&i.Lastname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT
    tc.id, tc.task_id, tc.author_id, tc.body, tc.created_at, tc.updated_at, tc.deleted_at,
    u.firstname,
    u.lastname,
    u.avatar_url
FROM task_comments tc
LEFT JOIN users u ON u.id = tc.author_id
WHERE tc.task_id = $1 AND tc.deleted_at IS NULL
ORDER BY tc.created_at DESC
LIMIT $2
`

type ListTaskCommentsParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	PageSize int32     `json:"page_size"`
}

type ListTaskCommentsRow struct {
	ID        uuid.UUID  `json:"id"`
	TaskID    uuid.UUID  `json:"task_id"`
	AuthorID  *uuid.UUID `json:"author_id"`
	Body      string     `json:"body"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	Firstname *string    `json:"firstname"`
	Lastname  *string    `json:"lastname"`
	AvatarUrl *string    `json:"avatar_url"`
}

func (q *Queries) ListTaskComments(ctx context.Context, arg ListTaskCommentsParams) ([]ListTaskCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskComments, arg.TaskID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskCommentsRow{}
	for rows.Next() {
		var i ListTaskCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Firstname,
			&i.Lastname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT
    t.id, t.project_id, t.title, t.description, t.status, t.tag, t.starts_on, t.due_on, t.hours, t.note, t.position, t.completed_at, t.created_by, t.created_at, t.updated_at, t.deleted_at, t.priority, t.subtasks_total, t.subtasks_done, t.comments_count, t.attachments_count,
    p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id AND p.deleted_at IS NULL
WHERE t.deleted_at IS NULL
  AND ($1::text IS NULL OR t.status = $1::text)
  AND ($2::text IS NULL OR t.priority = $2::text)
  AND ($3::uuid IS NULL OR t.project_id = $3::uuid)
  AND ($4::text IS NULL OR t.title ILIKE '%' || $4::text || '%')
ORDER BY t.status, t.position, t.created_at, t.id
LIMIT $5
`

type ListTasksParams struct {
	Status    *string    `json:"status"`
	Priority  *string    `json:"priority"`
	ProjectID *uuid.UUID `json:"project_id"`
	Search    *string    `json:"search"`
	PageSize  int32      `json:"page_size"`
}

type ListTasksRow struct {
	ID               uuid.UUID  `json:"id"`
	ProjectID        uuid.UUID  `json:"project_id"`
	Title            string     `json:"title"`
	Description      string     `json:"description"`
	Status           string     `json:"status"`
	Tag              string     `json:"tag"`
	StartsOn         *time.Time `json:"starts_on"`
	DueOn            *time.Time `json:"due_on"`
	Hours            *float64   `json:"hours"`
	Note             string     `json:"note"`
	Position         int32      `json:"position"`
	CompletedAt      *time.Time `json:"completed_at"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	DeletedAt        *time.Time `json:"deleted_at"`
	Priority         string     `json:"priority"`
	SubtasksTotal    int32      `json:"subtasks_total"`
	SubtasksDone     int32      `json:"subtasks_done"`
	CommentsCount    int32      `json:"comments_count"`
	AttachmentsCount int32      `json:"attachments_count"`
	ProjectName      string     `json:"project_name"`
}

// Taches de toute l'agence, pour l'ecran « Taches » du module.
//
// Le nom du projet est joint ici : une tache sortie de sa fiche ne dit plus
// d'ou elle vient, et l'aller chercher ensuite ferait une requete par ligne.
//
// Meme borne que le tableau d'un projet, et pour la meme raison : l'ecran a
// une vue kanban, et on ne tourne pas la page d'un kanban. Le total part a
// cote pour que la vue puisse dire qu'elle n'affiche pas tout.
//
// La jointure sur les projets vivants fait le reste du filtrage : les taches
// d'un projet supprime ne doivent pas reapparaitre dans une liste globale.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.Status,
		arg.Priority,
		arg.ProjectID,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Tag,
			&i.StartsOn,
			&i.DueOn,
			&i.Hours,
			&i.Note,
			&i.Position,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Priority,
			&i.SubtasksTotal,
			&i.SubtasksDone,
			&i.CommentsCount,
			&i.AttachmentsCount,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksOfProject = `-- name: ListTasksOfProject :many
SELECT id, project_id, title, description, status, tag, starts_on, due_on, hours, note, position, completed_at, created_by, created_at, updated_at, deleted_at, priority, subtasks_total, subtasks_done, comments_count, attachments_count FROM tasks
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY status, position, created_at
LIMIT $2
`

type ListTasksOfProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	PageSize  int32     `json:"page_size"`
}

// Tableau des taches d'un projet.
//
// Bornee comme toutes les listes. Un tableau n'a pas de pagination visible —
// on ne tourne pas la page d'un kanban — mais la borne existe quand meme :
// c'est elle qui empeche un projet devenu fourre-tout de ramener dix mille
// lignes. Le handler renvoie le total a cote, pour que l'ecran puisse dire
// qu'il n'affiche pas tout.
func (q *Queries) ListTasksOfProject(ctx context.Context, arg ListTasksOfProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksOfProject, arg.ProjectID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Tag,
			&i.StartsOn,
			&i.DueOn,
			&i.Hours,
			&i.Note,
			&i.Position,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Priority,
			&i.SubtasksTotal,
			&i.SubtasksDone,
			&i.CommentsCount,
			&i.AttachmentsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logTaskActivity = `-- name: LogTaskActivity :exec
INSERT INTO task_activity (task_id, actor_id, kind, payload)
VALUES ($1, $2, $3, $4)
`

type LogTaskActivityParams struct {
	TaskID  uuid.UUID  `json:"task_id"`
	ActorID *uuid.UUID `json:"actor_id"`
	Kind    string     `json:"kind"`
	Payload []byte     `json:"payload"`
}

func (q *Queries) LogTaskActivity(ctx context.Context, arg LogTaskActivityParams) error {
	_, err := q.db.Exec(ctx, logTaskActivity,
		arg.TaskID,
		arg.ActorID,
		arg.Kind,
		arg.Payload,
	)
	return err
}

const moveTask = `-- name: MoveTask :one
UPDATE tasks AS t SET
    status     = $1::text,
    -- La table cible est aliasee : sans cela, le ` + "`" + `tasks` + "`" + ` de la sous-requete
    -- masque celui de l'UPDATE et la colonne devient ambigue.
    position   = COALESCE(
        $2::integer,
        (SELECT coalesce(max(sibling.position), 0) + 1 FROM tasks AS sibling
         WHERE sibling.project_id = t.project_id
           AND sibling.status = $1::text
           AND sibling.deleted_at IS NULL)
    ),
    updated_at = now()
WHERE t.id = $3 AND t.deleted_at IS NULL
RETURNING t.id, t.project_id, t.title, t.description, t.status, t.tag, t.starts_on, t.due_on, t.hours, t.note, t.position, t.completed_at, t.created_by, t.created_at, t.updated_at, t.deleted_at, t.priority, t.subtasks_total, t.subtasks_done, t.comments_count, t.attachments_count
`

type MoveTaskParams struct {
	Status   string    `json:"status"`
	Position *int32    `json:"position"`
	ID       uuid.UUID `json:"id"`
}

// Deplacement dans le tableau : la colonne, et le rang dans cette colonne.
// Separe de UpdateTask parce que c'est le seul mouvement qui journalise un
// changement de statut, et que le tableau l'appelle a chaque glissement.
func (q *Queries) MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, moveTask, arg.Status, arg.Position, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Tag,
		&i.StartsOn,
		&i.DueOn,
		&i.Hours,
		&i.Note,
		&i.Position,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Priority,
		&i.SubtasksTotal,
		&i.SubtasksDone,
		&i.CommentsCount,
		&i.AttachmentsCount,
	)
	return i, err
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTask, id)
	return err
}

const softDeleteTaskComment = `-- name: SoftDeleteTaskComment :exec
UPDATE task_comments SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND author_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTaskCommentParams struct {
	ID       uuid.UUID  `json:"id"`
	AuthorID *uuid.UUID `json:"author_id"`
}

func (q *Queries) SoftDeleteTaskComment(ctx context.Context, arg SoftDeleteTaskCommentParams) error {
	_, err := q.db.Exec(ctx, softDeleteTaskComment, arg.ID, arg.AuthorID)
	return err
}

const unassignTask = `-- name: UnassignTask :exec
DELETE FROM task_assignees WHERE task_id = $1 AND user_id = $2
`

type UnassignTaskParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnassignTask(ctx context.Context, arg UnassignTaskParams) error {
	_, err := q.db.Exec(ctx, unassignTask, arg.TaskID, arg.UserID)
	return err
}

const updateSubtask = `-- name: UpdateSubtask :one
UPDATE subtasks SET
    label      = COALESCE($1::text, label),
    done       = COALESCE($2::boolean, done),
    position   = COALESCE($3::integer, position),
    updated_at = now()
WHERE id = $4
RETURNING id, task_id, label, done, position, created_at, updated_at
`

type UpdateSubtaskParams struct {
	Label    *string   `json:"label"`
	Done     *bool     `json:"done"`
	Position *int32    `json:"position"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSubtask(ctx context.Context, arg UpdateSubtaskParams) (Subtask, error) {
	row := q.db.QueryRow(ctx, updateSubtask,
		arg.Label,
		arg.Done,
		arg.Position,
		arg.ID,
	)
	var i Subtask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Label,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    title       = COALESCE($1::text, title),
    description = COALESCE($2::text, description),
    tag         = COALESCE($3::text, tag),
    priority    = COALESCE($4::text, priority),
    note        = COALESCE($5::text, note),
    hours       = CASE WHEN $6::boolean THEN NULL
                       ELSE COALESCE($7::numeric, hours) END,
    starts_on   = CASE WHEN $8::boolean THEN NULL
                       ELSE COALESCE($9::date, starts_on) END,
    due_on      = CASE WHEN $10::boolean THEN NULL
                       ELSE COALESCE($11::date, due_on) END,
    updated_at  = now()
WHERE id = $12 AND deleted_at IS NULL
RETURNING id, project_id, title, description, status, tag, starts_on, due_on, hours, note, position, completed_at, created_by, created_at, updated_at, deleted_at, priority, subtasks_total, subtasks_done, comments_count, attachments_count
`

type UpdateTaskParams struct {
	Title         *string    `json:"title"`
	Description   *string    `json:"description"`
	Tag           *string    `json:"tag"`
	Priority      *string    `json:"priority"`
	Note          *string    `json:"note"`
	ClearHours    bool       `json:"clear_hours"`
	Hours         *float64   `json:"hours"`
	ClearStartsOn bool       `json:"clear_starts_on"`
	StartsOn      *time.Time `json:"starts_on"`
	ClearDueOn    bool       `json:"clear_due_on"`
	DueOn         *time.Time `json:"due_on"`
	ID            uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Tag,
		arg.Priority,
		arg.Note,
		arg.ClearHours,
		arg.Hours,
		arg.ClearStartsOn,
		arg.StartsOn,
		arg.ClearDueOn,
		arg.DueOn,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Tag,
		&i.StartsOn,
		&i.DueOn,
		&i.Hours,
		&i.Note,
		&i.Position,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Priority,
		&i.SubtasksTotal,
		&i.SubtasksDone,
		&i.CommentsCount,
		&i.AttachmentsCount,
	)
	return i, err
}
