// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const countTicketsAssignedTo = `-- name: CountTicketsAssignedTo :one
SELECT count(*)
FROM tickets t
JOIN projects p ON p.id = t.project_id AND p.deleted_at IS NULL
WHERE t.deleted_at IS NULL
  AND t.assignee_id = $1
  AND ($2::text IS NULL OR t.status = $2::text)
  AND ($3::text IS NULL OR t.tracker = $3::text)
  AND ($4::text IS NULL OR t.priority = $4::text)
  AND ($5::uuid IS NULL OR t.project_id = $5::uuid)
  AND (
      $6::text IS NULL
      OR t.subject ILIKE '%' || $6::text || '%'
      OR t.numero::text = $6::text
  )
`

type CountTicketsAssignedToParams struct {
	AssigneeID *uuid.UUID `json:"assignee_id"`
	Status     *string    `json:"status"`
	Tracker    *string    `json:"tracker"`
	Priority   *string    `json:"priority"`
	ProjectID  *uuid.UUID `json:"project_id"`
	Search     *string    `json:"search"`
}

// Total pour la pagination, aux memes conditions que la liste.
func (q *Queries) CountTicketsAssignedTo(ctx context.Context, arg CountTicketsAssignedToParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsAssignedTo,
		arg.AssigneeID,
		arg.Status,
		arg.Tracker,
		arg.Priority,
		arg.ProjectID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :one
WITH nouveau AS (
    INSERT INTO tickets (
        project_id, subject, description, tracker, status, priority,
        assignee_id, created_by
    )
    VALUES (
        $1, $2, $3,
        $4, $5, $6,
        $7, $8
    )
    RETURNING id, numero, project_id, subject, description, tracker, status, priority, assignee_id, created_by, created_at, updated_at, deleted_at
)
SELECT
    n.id,
    n.numero,
    n.subject,
    n.tracker,
    n.status,
    n.priority,
    n.created_at,
    n.updated_at,
    p.id   AS project_id,
    p.name AS project_name
FROM nouveau n
JOIN projects p ON p.id = n.project_id
`

type CreateTicketParams struct {
	ProjectID   uuid.UUID  `json:"project_id"`
	Subject     string     `json:"subject"`
	Description string     `json:"description"`
	Tracker     string     `json:"tracker"`
	Status      string     `json:"status"`
	Priority    string     `json:"priority"`
	AssigneeID  *uuid.UUID `json:"assignee_id"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

type CreateTicketRow struct {
	ID          uuid.UUID `json:"id"`
	Numero      int64     `json:"numero"`
	Subject     string    `json:"subject"`
	Tracker     string    `json:"tracker"`
	Status      string    `json:"status"`
	Priority    string    `json:"priority"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ProjectID   uuid.UUID `json:"project_id"`
	ProjectName string    `json:"project_name"`
}

// Depot d'un ticket.
//
// Le numero n'est pas fourni : l'identite de la colonne l'attribue, ce qui
// rend deux creations simultanees incapables d'obtenir le meme.
//
// La CTE evite un second aller-retour pour le nom du projet : la ligne rendue a
// la meme forme que celles de la liste, et l'ecran peut l'afficher telle quelle.
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (CreateTicketRow, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ProjectID,
		arg.Subject,
		arg.Description,
		arg.Tracker,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.CreatedBy,
	)
	var i CreateTicketRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Subject,
		&i.Tracker,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.ProjectName,
	)
	return i, err
}

const createTicketEvent = `-- name: CreateTicketEvent :one
INSERT INTO ticket_events (ticket_id, actor_id, field, old_value, new_value)
VALUES (
    $1, $2,
    $3, $4, $5
)
RETURNING id, created_at
`

type CreateTicketEventParams struct {
	TicketID uuid.UUID  `json:"ticket_id"`
	ActorID  *uuid.UUID `json:"actor_id"`
	Field    string     `json:"field"`
	OldValue string     `json:"old_value"`
	NewValue string     `json:"new_value"`
}

type CreateTicketEventRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

// Inscrit un changement au journal.
func (q *Queries) CreateTicketEvent(ctx context.Context, arg CreateTicketEventParams) (CreateTicketEventRow, error) {
	row := q.db.QueryRow(ctx, createTicketEvent,
		arg.TicketID,
		arg.ActorID,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
	)
	var i CreateTicketEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createTicketMessage = `-- name: CreateTicketMessage :one
INSERT INTO ticket_messages (ticket_id, author_id, body, is_internal)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateTicketMessageParams struct {
	TicketID   uuid.UUID  `json:"ticket_id"`
	AuthorID   *uuid.UUID `json:"author_id"`
	Body       string     `json:"body"`
	IsInternal bool       `json:"is_internal"`
}

type CreateTicketMessageRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

// Inscrit un message au registre.
func (q *Queries) CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (CreateTicketMessageRow, error) {
	row := q.db.QueryRow(ctx, createTicketMessage,
		arg.TicketID,
		arg.AuthorID,
		arg.Body,
		arg.IsInternal,
	)
	var i CreateTicketMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT
    t.id,
    t.numero,
    t.subject,
    t.description,
    t.tracker,
    t.status,
    t.priority,
    t.created_at,
    t.updated_at,
    p.id   AS project_id,
    p.name AS project_name,
    c.id   AS client_id,
    c.name AS client_name,
    t.assignee_id,
    a.firstname  AS assignee_firstname,
    a.lastname   AS assignee_lastname,
    a.avatar_url AS assignee_avatar_url,
    t.created_by,
    r.firstname  AS reporter_firstname,
    r.lastname   AS reporter_lastname,
    r.avatar_url AS reporter_avatar_url
FROM tickets t
JOIN projects p ON p.id = t.project_id AND p.deleted_at IS NULL
LEFT JOIN clients c ON c.id = p.client_id AND c.deleted_at IS NULL
LEFT JOIN users a ON a.id = t.assignee_id AND a.deleted_at IS NULL
LEFT JOIN users r ON r.id = t.created_by AND r.deleted_at IS NULL
WHERE t.id = $1 AND t.deleted_at IS NULL
`

type GetTicketRow struct {
	ID                uuid.UUID  `json:"id"`
	Numero            int64      `json:"numero"`
	Subject           string     `json:"subject"`
	Description       string     `json:"description"`
	Tracker           string     `json:"tracker"`
	Status            string     `json:"status"`
	Priority          string     `json:"priority"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	ProjectID         uuid.UUID  `json:"project_id"`
	ProjectName       string     `json:"project_name"`
	ClientID          *uuid.UUID `json:"client_id"`
	ClientName        *string    `json:"client_name"`
	AssigneeID        *uuid.UUID `json:"assignee_id"`
	AssigneeFirstname *string    `json:"assignee_firstname"`
	AssigneeLastname  *string    `json:"assignee_lastname"`
	AssigneeAvatarUrl *string    `json:"assignee_avatar_url"`
	CreatedBy         *uuid.UUID `json:"created_by"`
	ReporterFirstname *string    `json:"reporter_firstname"`
	ReporterLastname  *string    `json:"reporter_lastname"`
	ReporterAvatarUrl *string    `json:"reporter_avatar_url"`
}

// Fiche d'un ticket : son en-tete et ses coordonnees.
//
// Les messages et les evenements font l'objet de deux requetes a part : les
// ramener par jointure multiplierait l'en-tete par le nombre de lignes du
// registre.
func (q *Queries) GetTicket(ctx context.Context, id uuid.UUID) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Subject,
		&i.Description,
		&i.Tracker,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.ProjectName,
		&i.ClientID,
		&i.ClientName,
		&i.AssigneeID,
		&i.AssigneeFirstname,
		&i.AssigneeLastname,
		&i.AssigneeAvatarUrl,
		&i.CreatedBy,
		&i.ReporterFirstname,
		&i.ReporterLastname,
		&i.ReporterAvatarUrl,
	)
	return i, err
}

const listTicketEvents = `-- name: ListTicketEvents :many
SELECT
    e.id,
    e.field,
    e.old_value,
    e.new_value,
    e.created_at,
    e.actor_id,
    u.firstname  AS actor_firstname,
    u.lastname   AS actor_lastname,
    u.avatar_url AS actor_avatar_url
FROM ticket_events e
LEFT JOIN users u ON u.id = e.actor_id AND u.deleted_at IS NULL
WHERE e.ticket_id = $1
ORDER BY e.created_at, e.id
`

type ListTicketEventsRow struct {
	ID             uuid.UUID  `json:"id"`
	Field          string     `json:"field"`
	OldValue       string     `json:"old_value"`
	NewValue       string     `json:"new_value"`
	CreatedAt      time.Time  `json:"created_at"`
	ActorID        *uuid.UUID `json:"actor_id"`
	ActorFirstname *string    `json:"actor_firstname"`
	ActorLastname  *string    `json:"actor_lastname"`
	ActorAvatarUrl *string    `json:"actor_avatar_url"`
}

// Ce qui est arrive au ticket, dans le meme ordre.
func (q *Queries) ListTicketEvents(ctx context.Context, ticketID uuid.UUID) ([]ListTicketEventsRow, error) {
	rows, err := q.db.Query(ctx, listTicketEvents, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketEventsRow{}
	for rows.Next() {
		var i ListTicketEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.ActorID,
			&i.ActorFirstname,
			&i.ActorLastname,
			&i.ActorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketMessages = `-- name: ListTicketMessages :many
SELECT
    m.id,
    m.body,
    m.is_internal,
    m.created_at,
    m.author_id,
    u.firstname  AS author_firstname,
    u.lastname   AS author_lastname,
    u.avatar_url AS author_avatar_url,
    u.role       AS author_role
FROM ticket_messages m
LEFT JOIN users u ON u.id = m.author_id AND u.deleted_at IS NULL
WHERE m.ticket_id = $1 AND m.deleted_at IS NULL
ORDER BY m.created_at, m.id
`

type ListTicketMessagesRow struct {
	ID              uuid.UUID  `json:"id"`
	Body            string     `json:"body"`
	IsInternal      bool       `json:"is_internal"`
	CreatedAt       time.Time  `json:"created_at"`
	AuthorID        *uuid.UUID `json:"author_id"`
	AuthorFirstname *string    `json:"author_firstname"`
	AuthorLastname  *string    `json:"author_lastname"`
	AuthorAvatarUrl *string    `json:"author_avatar_url"`
	AuthorRole      *string    `json:"author_role"`
}

// Ce qui s'est dit sur un ticket, du plus ancien au plus recent.
func (q *Queries) ListTicketMessages(ctx context.Context, ticketID uuid.UUID) ([]ListTicketMessagesRow, error) {
	rows, err := q.db.Query(ctx, listTicketMessages, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketMessagesRow{}
	for rows.Next() {
		var i ListTicketMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.IsInternal,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorFirstname,
			&i.AuthorLastname,
			&i.AuthorAvatarUrl,
			&i.AuthorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsAssignedTo = `-- name: ListTicketsAssignedTo :many

SELECT
    t.id,
    t.numero,
    t.subject,
    t.tracker,
    t.status,
    t.priority,
    t.created_at,
    t.updated_at,
    p.id   AS project_id,
    p.name AS project_name
FROM tickets t
JOIN projects p ON p.id = t.project_id AND p.deleted_at IS NULL
WHERE t.deleted_at IS NULL
  AND t.assignee_id = $1
  AND ($2::text IS NULL OR t.status = $2::text)
  AND ($3::text IS NULL OR t.tracker = $3::text)
  AND ($4::text IS NULL OR t.priority = $4::text)
  AND ($5::uuid IS NULL OR t.project_id = $5::uuid)
  AND (
      $6::text IS NULL
      OR t.subject ILIKE '%' || $6::text || '%'
      OR t.numero::text = $6::text
  )
ORDER BY t.updated_at DESC, t.numero DESC
LIMIT $8 OFFSET $7
`

type ListTicketsAssignedToParams struct {
	AssigneeID *uuid.UUID `json:"assignee_id"`
	Status     *string    `json:"status"`
	Tracker    *string    `json:"tracker"`
	Priority   *string    `json:"priority"`
	ProjectID  *uuid.UUID `json:"project_id"`
	Search     *string    `json:"search"`
	PageOffset int32      `json:"page_offset"`
	PageSize   int32      `json:"page_size"`
}

type ListTicketsAssignedToRow struct {
	ID          uuid.UUID `json:"id"`
	Numero      int64     `json:"numero"`
	Subject     string    `json:"subject"`
	Tracker     string    `json:"tracker"`
	Status      string    `json:"status"`
	Priority    string    `json:"priority"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ProjectID   uuid.UUID `json:"project_id"`
	ProjectName string    `json:"project_name"`
}

// Tickets.
//
// Les trois vues de l'ecran — tableau, kanban par projet, kanban par statut —
// partagent la meme barre d'outils, donc les memes filtres. Ils sont ecrits une
// fois par requete plutot que composes en Go : sqlc verifie alors le SQL a la
// generation, ce qu'une concatenation de chaines interdirait.
//
// `assignee_id` n'est pas un filtre mais une clause : l'ecran ne montre que les
// tickets du compte appelant, et l'identifiant vient de la session.
// Page du tableau, du plus recemment mis a jour au plus ancien — l'ordre dans
// lequel on reprend son travail.
//
// La recherche porte sur le sujet et sur le numero : « 47 » doit retrouver le
// ticket #47, c'est ainsi qu'on le designe a l'oral.
func (q *Queries) ListTicketsAssignedTo(ctx context.Context, arg ListTicketsAssignedToParams) ([]ListTicketsAssignedToRow, error) {
	rows, err := q.db.Query(ctx, listTicketsAssignedTo,
		arg.AssigneeID,
		arg.Status,
		arg.Tracker,
		arg.Priority,
		arg.ProjectID,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsAssignedToRow{}
	for rows.Next() {
		var i ListTicketsAssignedToRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Subject,
			&i.Tracker,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsBoardAssignedTo = `-- name: ListTicketsBoardAssignedTo :many
SELECT
    t.id,
    t.numero,
    t.subject,
    t.tracker,
    t.status,
    t.priority,
    t.created_at,
    t.updated_at,
    p.id   AS project_id,
    p.name AS project_name
FROM tickets t
JOIN projects p ON p.id = t.project_id AND p.deleted_at IS NULL
WHERE t.deleted_at IS NULL
  AND t.assignee_id = $1
  AND ($2::text IS NULL OR t.status = $2::text)
  AND ($3::text IS NULL OR t.tracker = $3::text)
  AND ($4::text IS NULL OR t.priority = $4::text)
  AND ($5::uuid IS NULL OR t.project_id = $5::uuid)
  AND (
      $6::text IS NULL
      OR t.subject ILIKE '%' || $6::text || '%'
      OR t.numero::text = $6::text
  )
ORDER BY t.numero DESC
LIMIT $7
`

type ListTicketsBoardAssignedToParams struct {
	AssigneeID *uuid.UUID `json:"assignee_id"`
	Status     *string    `json:"status"`
	Tracker    *string    `json:"tracker"`
	Priority   *string    `json:"priority"`
	ProjectID  *uuid.UUID `json:"project_id"`
	Search     *string    `json:"search"`
	PageSize   int32      `json:"page_size"`
}

type ListTicketsBoardAssignedToRow struct {
	ID          uuid.UUID `json:"id"`
	Numero      int64     `json:"numero"`
	Subject     string    `json:"subject"`
	Tracker     string    `json:"tracker"`
	Status      string    `json:"status"`
	Priority    string    `json:"priority"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ProjectID   uuid.UUID `json:"project_id"`
	ProjectName string    `json:"project_name"`
}

// Toutes les cartes des deux kanbans, aux memes filtres que le tableau.
//
// Bornee et non paginee, comme les kanbans des taches et des clients : un
// tableau se lit en entier ou pas du tout, et paginer une colonne n'aurait
// aucun sens. Le handler previent quand la borne a coupe.
//
// Trie par numero decroissant et non par mise a jour : dans un tableau, c'est
// la colonne qui porte le classement, et l'ordre a l'interieur doit rester
// stable d'un affichage a l'autre.
func (q *Queries) ListTicketsBoardAssignedTo(ctx context.Context, arg ListTicketsBoardAssignedToParams) ([]ListTicketsBoardAssignedToRow, error) {
	rows, err := q.db.Query(ctx, listTicketsBoardAssignedTo,
		arg.AssigneeID,
		arg.Status,
		arg.Tracker,
		arg.Priority,
		arg.ProjectID,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsBoardAssignedToRow{}
	for rows.Next() {
		var i ListTicketsBoardAssignedToRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Subject,
			&i.Tracker,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTicket = `-- name: LockTicket :one
SELECT id
FROM tickets
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// Prend le verrou d'ecriture sur un ticket, le temps de la transaction.
//
// Sans lui, deux ecritures concurrentes lisent toutes deux l'etat d'avant et
// inscrivent chacune sa ligne au journal : on se retrouve avec deux
// « renomme de A vers B » pour un seul renommage. Le verrou les met en file,
// la seconde voit le travail de la premiere et n'a plus rien a journaliser.
func (q *Queries) LockTicket(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockTicket, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const updateTicketFields = `-- name: UpdateTicketFields :exec
UPDATE tickets
SET status      = coalesce($1::text, status),
    priority    = coalesce($2::text, priority),
    assignee_id = CASE
                      WHEN $3::boolean
                          THEN $4::uuid
                      ELSE assignee_id
                  END,
    updated_at  = now()
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateTicketFieldsParams struct {
	Status         *string    `json:"status"`
	Priority       *string    `json:"priority"`
	ChangeAssignee bool       `json:"change_assignee"`
	AssigneeID     *uuid.UUID `json:"assignee_id"`
	ID             uuid.UUID  `json:"id"`
}

// Applique les changements qu'une entree du registre porte.
//
// Un `coalesce` par champ : ce qui n'est pas demande garde sa valeur, ce qui
// evite de relire puis reecrire les deux autres colonnes a chaque fois.
//
// L'assigne a son propre drapeau parce que NULL y est une valeur qui veut dire
// quelque chose — « remettre a prendre ». Sans lui, on ne saurait pas
// distinguer « ne touche pas a l'assignation » de « retire-la ».
//
// Ne rend rien : le service relit la fiche dans la meme transaction pour
// comparer l'avant et l'apres, et en tirer les lignes du journal.
func (q *Queries) UpdateTicketFields(ctx context.Context, arg UpdateTicketFieldsParams) error {
	_, err := q.db.Exec(ctx, updateTicketFields,
		arg.Status,
		arg.Priority,
		arg.ChangeAssignee,
		arg.AssigneeID,
		arg.ID,
	)
	return err
}

const updateTicketSubject = `-- name: UpdateTicketSubject :exec
UPDATE tickets
SET subject = $1,
    updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateTicketSubjectParams struct {
	Subject string    `json:"subject"`
	ID      uuid.UUID `json:"id"`
}

// Renomme un ticket. Le numero, lui, ne bouge jamais.
func (q *Queries) UpdateTicketSubject(ctx context.Context, arg UpdateTicketSubjectParams) error {
	_, err := q.db.Exec(ctx, updateTicketSubject, arg.Subject, arg.ID)
	return err
}
