// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR role = $1::text)
`

func (q *Queries) CountUsers(ctx context.Context, role *string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, firstname, lastname, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, firstname, lastname, role, avatar_url, totp_secret, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Firstname,
		arg.Lastname,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.AvatarUrl,
		&i.TotpSecret,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, firstname, lastname, role, avatar_url, totp_secret, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.AvatarUrl,
		&i.TotpSecret,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, firstname, lastname, role, avatar_url, totp_secret, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.AvatarUrl,
		&i.TotpSecret,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, firstname, lastname, role, avatar_url, totp_secret, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR role = $1::text)
ORDER BY firstname, lastname
LIMIT $3 OFFSET $2
`

type ListUsersParams struct {
	Role       *string `json:"role"`
	PageOffset int32   `json:"page_offset"`
	PageSize   int32   `json:"page_size"`
}

// Pagination cote serveur systematique : jamais de SELECT sans LIMIT.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Role, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Firstname,
			&i.Lastname,
			&i.Role,
			&i.AvatarUrl,
			&i.TotpSecret,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}
