-- Integration Git : les pull requests et les mises en ligne de GitHub et
-- GitLab, recues par webhook.
--
-- Rien n'est tire de chez eux : ils poussent, Piilot ecrit, les ecrans
-- lisent. Un seul secret pour toute l'installation, a copier dans chaque
-- webhook d'organisation ou de depot ; chaque projet dit quel depot est le
-- sien, et c'est l'adresse du depot recue dans l'evenement qui retrouve le
-- projet.

-- Le depot d'un projet, sous forme normalisee (https://hote/groupe/depot).
ALTER TABLE projects ADD COLUMN repo_url text NOT NULL DEFAULT '';
CREATE INDEX projects_repo_url_idx ON projects (repo_url) WHERE repo_url <> '' AND deleted_at IS NULL;

-- Un numero lisible par tache, comme les tickets en ont deja : c'est ce qu'on
-- ecrit dans le nom d'une branche ou le titre d'une pull request (T-123).
ALTER TABLE tasks ADD COLUMN numero bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE;

-- Le secret du webhook, une seule ligne. Vide tant qu'un admin n'a pas ouvert
-- l'ecran, qui en tire un. GIT_WEBHOOK_SECRET, s'il est defini, prime.
CREATE TABLE git_webhook (
    id         boolean PRIMARY KEY DEFAULT true CHECK (id),
    secret     text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE pull_requests (
    id         uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    provider   text NOT NULL,
    number     bigint NOT NULL,
    title      text NOT NULL DEFAULT '',
    url        text NOT NULL DEFAULT '',
    branch     text NOT NULL DEFAULT '',
    author     text NOT NULL DEFAULT '',
    state      text NOT NULL,
    opened_at  timestamptz,
    merged_at  timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pull_requests_provider_check CHECK (provider IN ('github', 'gitlab')),
    CONSTRAINT pull_requests_state_check CHECK (state IN ('open', 'merged', 'closed')),
    CONSTRAINT pull_requests_unique UNIQUE (project_id, provider, number)
);

-- Ce qu'une pull request fait avancer : un ticket ou une tache, retrouves
-- par leur numero dans son titre, sa branche ou sa description.
CREATE TABLE pull_request_links (
    pull_request_id uuid NOT NULL REFERENCES pull_requests (id) ON DELETE CASCADE,
    ticket_id       uuid REFERENCES tickets (id) ON DELETE CASCADE,
    task_id         uuid REFERENCES tasks (id) ON DELETE CASCADE,

    CONSTRAINT pull_request_links_one_target CHECK ((ticket_id IS NULL) <> (task_id IS NULL)),
    CONSTRAINT pull_request_links_ticket_unique UNIQUE (pull_request_id, ticket_id),
    CONSTRAINT pull_request_links_task_unique UNIQUE (pull_request_id, task_id)
);
CREATE INDEX pull_request_links_ticket_idx ON pull_request_links (ticket_id) WHERE ticket_id IS NOT NULL;
CREATE INDEX pull_request_links_task_idx ON pull_request_links (task_id) WHERE task_id IS NOT NULL;

-- Une mise en ligne : release publiee, tag pousse ou deploiement reussi.
CREATE TABLE deployments (
    id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id  uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    provider    text NOT NULL,
    kind        text NOT NULL,
    name        text NOT NULL,
    url         text NOT NULL DEFAULT '',
    environment text NOT NULL DEFAULT '',
    deployed_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT deployments_kind_check CHECK (kind IN ('release', 'tag', 'deployment')),
    CONSTRAINT deployments_unique UNIQUE (project_id, provider, kind, name)
);
CREATE INDEX deployments_project_idx ON deployments (project_id, deployed_at DESC);

-- Une mise en ligne s'inscrit au journal du client.
ALTER TABLE client_interactions DROP CONSTRAINT client_interactions_kind_check;
ALTER TABLE client_interactions
    ADD CONSTRAINT client_interactions_kind_check CHECK (kind IN (
        'note', 'call', 'meeting', 'email',
        'project_created', 'deliverable_validated', 'ticket_opened', 'deployment'
    ));
