-- Tickets.
--
-- Le suivi des demandes : anomalies, evolutions et assistance. Distinct des
-- taches, qui decoupent un travail decide ; un ticket est une demande recue,
-- qui peut etre refusee, et qui vit avec son propre cycle.

CREATE TABLE tickets (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Numero lisible, unique pour toute l'agence et jamais reutilise.
    --
    -- C'est ce qu'on echange a l'oral et dans un e-mail : « regarde le #47 »
    -- doit designer un seul ticket, sans avoir a preciser le projet. Une
    -- identite Postgres s'en charge — deux creations simultanees ne peuvent pas
    -- obtenir le meme numero, la ou un `max(numero) + 1` calcule dans le
    -- service en donnerait deux identiques.
    --
    -- L'uuid reste la cle : le numero sert aux humains, pas aux jointures.
    numero bigint NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,

    -- Un ticket vise toujours un projet. Le client se lit par jointure et n'est
    -- pas recopie ici : deux sources pour la meme information finissent par
    -- diverger, et c'est le projet qui decide de qui releve le ticket.
    project_id uuid NOT NULL REFERENCES projects (id) ON DELETE CASCADE,

    subject     text NOT NULL,
    description text NOT NULL DEFAULT '',

    -- Nature de la demande, et etat d'avancement. Des CHECK plutot que des
    -- tables de reference, comme `projects.status` et `tasks.status` : des
    -- valeurs figees que le front connait par coeur ne valent pas une jointure
    -- sur chaque ligne, ni un ecran d'administration pour les gerer.
    --
    -- Les libelles francais vivent dans le front. La base stocke des cles
    -- stables : traduire en base obligerait a migrer les donnees le jour ou
    -- l'on reformule un intitule.
    tracker  text NOT NULL DEFAULT 'anomalie',
    status   text NOT NULL DEFAULT 'backlog',
    priority text NOT NULL DEFAULT 'normal',

    -- A qui revient le ticket. Nul tant que personne ne l'a pris — c'est l'etat
    -- normal d'une demande qui vient d'arriver, pas une donnee manquante.
    --
    -- `SET NULL` au depart d'un compte : un ticket ne disparait pas parce que
    -- la personne qui le portait a quitte l'agence, il redevient a prendre.
    assignee_id uuid REFERENCES users (id) ON DELETE SET NULL,
    created_by  uuid REFERENCES users (id) ON DELETE SET NULL,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,

    CONSTRAINT tickets_subject_not_blank CHECK (btrim(subject) <> ''),
    CONSTRAINT tickets_tracker_check
        CHECK (tracker IN ('anomalie', 'evolution', 'assistance')),
    CONSTRAINT tickets_status_check
        CHECK (status IN (
            'backlog', 'todo', 'in_progress', 'in_review',
            'ready_to_deploy', 'done', 'annule'
        )),
    CONSTRAINT tickets_priority_check
        CHECK (priority IN ('low', 'normal', 'high', 'urgent', 'critical'))
);

-- L'ecran « Tickets » ne montre que ceux de la personne connectee, du plus
-- recemment mis a jour au plus ancien. L'index porte les deux colonnes dans cet
-- ordre : la premiere page se lit alors sans tri ni balayage.
CREATE INDEX tickets_assignee_idx
    ON tickets (assignee_id, updated_at DESC)
    WHERE deleted_at IS NULL;

-- La fiche d'un projet listera ses tickets.
CREATE INDEX tickets_project_idx
    ON tickets (project_id)
    WHERE deleted_at IS NULL;
