/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contrat HTTP de l'API */
        get: operations["getOpenAPISpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sonde de liveness
         * @description Repond des que le process ecoute. Ne touche aucune dependance : un Postgres momentanement indisponible ne doit pas faire redemarrer le conteneur.
         */
        get: operations["getHealthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sonde de readiness
         * @description Repond 200 seulement si Postgres et Redis repondent. C'est cette sonde qui conditionne la bascule du trafic.
         */
        get: operations["getHealthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ouvre une session
         * @description Pose deux cookies httpOnly : plugiit_access (portee /) et plugiit_refresh (portee /api/v1/auth). Les jetons ne figurent jamais dans le corps de la reponse.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ferme la session courante
         * @description Revoque le jeton de rafraichissement et efface les deux cookies. Idempotent : rappeler cet endpoint sans session valide repond 204.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renouvelle la session
         * @description Consomme le cookie plugiit_refresh et le remplace : un jeton ne sert qu'une fois. Un jeton deja consomme qui se represente est traite comme un rejeu et revoque toutes les sessions du compte.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Identite de l'appelant
         * @description Relue en base a chaque appel : un droit retire ou un compte supprime prend effet immediatement, sans attendre l'expiration du jeton.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tableau de bord de l'agence
         * @description CONTRAT CIBLE — le handler repond encore 501. La reponse 200 decrite ici est ce que la vue attend et ce que l'implementation devra servir ; elle est publiee pour que le front soit type des maintenant.
         */
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste des projets
         * @description CONTRAT CIBLE — le handler repond encore 501. Exige la permission projects.read. La pagination est cote serveur : aucune reponse ne renvoie la collection entiere.
         */
        get: operations["listAdminProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Format d'erreur unique de l'API. Le front branche sur code, jamais sur message. */
        Error: {
            /**
             * @description Code stable, destine au code appelant
             * @example INVALID_CREDENTIALS
             * @example SESSION_EXPIRED
             * @example FORBIDDEN
             * @example VALIDATION_FAILED
             * @example RATE_LIMITED
             * @example NOT_IMPLEMENTED
             */
            code: string;
            /** @description Message affichable a l'utilisateur */
            message: string;
            /** @description Toujours un objet, jamais null. Porte les erreurs par champ en cas de validation. */
            details: {
                [key: string]: unknown;
            };
        };
        /** @description Identite rendue au front. Ne porte ni empreinte de mot de passe ni secret TOTP. */
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            firstname: string;
            lastname: string;
            /**
             * @description Code du role. Les roles vivent en base : cette liste est celle des roles systeme, elle peut s'etendre.
             * @example admin
             * @example team
             * @example client
             */
            role: string;
            avatar_url: string | null;
            /**
             * @description Permissions du role, pour masquer les actions inaccessibles. Confort d'affichage : l'API reste la seule autorite.
             * @example [
             *       "projects.read",
             *       "projects.write"
             *     ]
             */
            permissions: string[];
        };
        /** @description Reponse de login, refresh et me. Les jetons sont dans les cookies, jamais ici. */
        SessionResponse: {
            user: components["schemas"]["User"];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        /** @description CONTRAT CIBLE — le module PM n'est pas ecrit. Ce schema est ce que la vue liste affiche, rien de plus : il ne prejuge pas du modele de donnees. */
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            status: string;
            client_name: string | null;
            /** @description Avancement en pourcentage, precalcule cote serveur */
            completion: number;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Enveloppe de pagination, commune a toutes les listes de l'API. */
        ProjectPage: {
            items: components["schemas"]["Project"][];
            /** @description Nombre total d'elements, tous filtres appliques */
            total: number;
            page: number;
            page_size: number;
        };
        /** @description CONTRAT CIBLE — agregats precalcules, jamais recalcules par COUNT(*) au rendu. */
        DashboardSummary: {
            active_projects: number;
            tasks_in_progress: number;
            overdue_tasks: number;
            open_tickets: number;
        };
        HealthLive: {
            /** @example ok */
            status: string;
            version: string;
            commit: string;
        };
        HealthReady: {
            /**
             * @example ok
             * @example degraded
             */
            status: string;
            /**
             * @description Etat par dependance
             * @example {
             *       "database": "ok",
             *       "redis": "ok"
             *     }
             */
            checks: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description Authentification requise ou session expiree */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentifie, mais sans le droit necessaire */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Corps invalide. details porte un message par champ fautif. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Trop de tentatives. L'en-tete Retry-After donne le delai en secondes. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description La route existe, le handler n'est pas encore ecrit */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOpenAPISpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le present document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getHealthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le process ecoute */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthLive"];
                };
            };
        };
    };
    getHealthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Toutes les dependances repondent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReady"];
                };
            };
            /** @description Une dependance au moins ne repond pas */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReady"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session ouverte, cookies poses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Identifiants incorrects. Ne distingue jamais un email inconnu d'un mot de passe faux. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session fermee, cookies effaces */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session renouvelee, nouveaux cookies poses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Session expiree, revoquee ou rejouee. Le front doit rediriger vers /login plutot que retenter. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil de l'appelant, permissions comprises */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agregats precalcules du tableau de bord */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            501: components["responses"]["NotImplemented"];
        };
    };
    listAdminProjects: {
        parameters: {
            query?: {
                /** @description Numero de page, 1 par defaut */
                page?: number;
                /** @description Taille de page */
                page_size?: number;
                /** @description Recherche partielle sur le nom du projet */
                search?: string;
                /** @description Filtre sur le statut */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page de projets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            501: components["responses"]["NotImplemented"];
        };
    };
}
